/**
 * Declarative slash command metadata — session, workspace, and auth commands.
 */

import type { LioraSlashCommand } from '../types';
import {
  toggleOnOffArgumentCompletions,
  permissionArgumentCompletions,
  contextArgumentCompletions,
  premiumArgumentCompletions,
  planArgumentCompletions,
  swarmArgumentCompletions,
  swarmControlAvailability,
  ultraworkArgumentCompletions,
  ultragoalArgumentCompletions,
  thinkingArgumentCompletions,
  preflightArgumentCompletions,
  helpArgumentCompletions,
  extensionsArgumentCompletions,
  cronArgumentCompletions,
  jobArgumentCompletions,
  jobsArgumentCompletions,
  memoryArgumentCompletions,
  addDirArgumentCompletions,
  loopArgumentCompletions,
  goalArgumentCompletions,
  editorArgumentCompletions,
  themeArgumentCompletions,
  appearanceArgumentCompletions,
  personaArgumentCompletions,
} from './completion-specs';
import { improveHarnessArgumentCompletions } from '../improve-harness';
import { pluginsArgumentCompletions } from '../plugins/plugins';
import { rendererArgumentCompletions } from '../renderer';
import { transcriptArgumentCompletions } from '../session/transcript';
import { neatArgumentCompletions } from '../session/neat';

export const BUILTIN_SLASH_COMMANDS_SESSION = [
{
    name: 'model',
    aliases: [],
    description: 'Switch LLM model',
    priority: 100,
    availability: 'always',
  },
  {
    name: 'thinking',
    aliases: ['think', 'reasoning', 'effort', 'depth'],
    description: 'Set thinking effort for the current session',
    priority: 100,
    argumentHint: '[off|on|low|medium|high|xhigh|max]',
    completeArgs: thinkingArgumentCompletions,
    availability: 'idle-only',
  },
  {
    name: 'btw',
    aliases: [],
    description: 'Ask a forked side agent a question',
    priority: 90,
    availability: 'always',
  },
  {
    name: 'bench',
    aliases: [],
    description: 'Show local SuperLiora benchmark diagnostics',
    priority: 80,
    visibility: 'diagnostic',
    argumentHint: '[evidence-path]',
    availability: 'always',
  },
  {
    name: 'preflight',
    aliases: ['pf'],
    description: 'Show SuperLiora harness preflight diagnostics',
    priority: 80,
    visibility: 'diagnostic',
    argumentHint: '[bench-evidence-path] [--query=<recall query>]',
    completeArgs: preflightArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'renderer',
    aliases: ['render'],
    description: 'Inspect and control the native renderer',
    priority: 80,
    visibility: 'diagnostic',
    argumentHint: 'diagnostics [on|off|toggle|status] | trace [status|reset|export]',
    completeArgs: rendererArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'transcript',
    aliases: [],
    description: 'Set transcript detail density (minimal, compact, standard, full)',
    priority: 80,
    argumentHint: '[minimal|compact|standard|full]',
    completeArgs: transcriptArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'neat',
    aliases: [],
    description: 'Toggle structured tool result cards instead of raw output',
    priority: 80,
    argumentHint: '[on|off|toggle|status]',
    completeArgs: neatArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'help',
    aliases: ['h'],
    description: 'Open the Command Hub menu (? / Ctrl-K)',
    priority: 100,
    completeArgs: helpArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'new',
    aliases: ['clear'],
    description: 'Start a fresh session in the current workspace',
    priority: 80,
  },
  {
    name: 'sessions',
    aliases: ['resume'],
    description: 'Browse and resume sessions',
    priority: 80,
  },
  {
    name: 'dashboard',
    aliases: ['dash', 'agents'],
    description: '에이전트 대시보드 — 입력 필요 / 작업 중 / 대기',
    priority: 85,
    availability: 'always',
  },
  {
    name: 'extensions',
    aliases: ['ext', 'import-claude'],
    description: '확장 기능 — 플러그인/훅/스킬/MCP · Claude 가져오기',
    priority: 70,
    availability: 'always',
    argumentHint: '[plugins|hooks|skills|mcp|claude]',
    completeArgs: extensionsArgumentCompletions,
  },
  {
    name: 'tasks',
    aliases: ['task'],
    description: 'Browse background tasks',
    priority: 80,
    availability: 'always',
  },
  {
    name: 'jobs',
    aliases: [],
    description: 'Conductor Job desk — list, board, or deck monitor',
    priority: 88,
    argumentHint: '[board|deck [job_id]|job_id]',
    completeArgs: jobsArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'job',
    aliases: [],
    description: 'Conductor Job — desk board, deck monitor, inspect / resume / cancel',
    priority: 88,
    argumentHint: 'board | deck [id] | list | inbox | resume [id] | cancel <id> | inspect <id>',
    completeArgs: jobArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'cron',
    aliases: [],
    description: 'Manage scheduled jobs (list / delete)',
    priority: 60,
    argumentHint: 'list | delete <jobId>',
    completeArgs: cronArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'term',
    aliases: ['terminal'],
    description: 'Show detected terminal capabilities',
    priority: 62,
    visibility: 'diagnostic',
    availability: 'always',
  },
  {
    name: 'mcp',
    aliases: [],
    description: 'Manage MCP servers (install, toggle, remove, status)',
    priority: 60,
    availability: 'always',
  },
  {
    name: 'tools',
    aliases: ['tool'],
    description: 'List active agent tools (SearchTools inventory)',
    priority: 70,
    availability: 'always',
  },
  {
    name: 'eyes',
    aliases: ['eye'],
    description: 'Show browser-use / computer-use eyes readiness',
    priority: 70,
    availability: 'always',
  },
  {
    name: 'harness',
    aliases: [],
    description: 'Open harness controls (tools, eyes, premium, MCP, experiments)',
    priority: 70,
    availability: 'always',
  },
  {
    name: 'plugins',
    aliases: [],
    description: 'Manage plugins (prefer Extensions Hub)',
    priority: 60,
    visibility: 'advanced',
    availability: 'always',
    argumentHint: '[list|install|marketplace|info|mcp|enable|disable|remove|reload]',
    completeArgs: pluginsArgumentCompletions,
  },
  {
    name: 'memory',
    aliases: ['recall'],
    description: 'Manage Liora Recall long-term memory',
    priority: 60,
    availability: 'always',
    argumentHint: '[stats|list|search|wiki|remember|forget|consolidate]',
    completeArgs: memoryArgumentCompletions,
  },
  {
    name: 'add-dir',
    aliases: [],
    description: 'Add or list an additional workspace directory',
    priority: 60,
    availability: 'idle-only',
    argumentHint: '[list] | <path>',
    completeArgs: addDirArgumentCompletions,
  },
  {
    name: 'experiments',
    aliases: ['experimental'],
    description: 'Manage experimental features',
    priority: 60,
    visibility: 'advanced',
    availability: 'idle-only',
  },
  {
    name: 'reload',
    aliases: [],
    description: 'Reload session and apply config.toml settings plus tui.toml UI preferences',
    priority: 60,
    visibility: 'advanced',
    availability: 'idle-only',
  },
  {
    name: 'reload-tui',
    aliases: [],
    description: 'Reload only tui.toml UI preferences',
    priority: 60,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'compact',
    aliases: [],
    description: 'Compact the conversation context',
    priority: 80,
    argumentHint: '<instruction>',
  },
  {
    name: 'goal',
    aliases: [],
    description: 'Simple goal loop: set objective, agent iterates until done (Ralph Loop)',
    priority: 80,
    argumentHint: '[status|pause|resume|cancel|replace|next] | <objective>',
    completeArgs: goalArgumentCompletions,
    // status / pause / cancel are always available; creation, replacement, and
    // resume start (or restart) a turn and so are idle-only.
    availability: (args) => {
      const trimmed = args.trim();
      if (trimmed === 'next' || trimmed.startsWith('next ')) return 'always';
      return trimmed === '' || trimmed === 'status' || trimmed === 'pause' || trimmed === 'cancel'
        ? 'always'
        : 'idle-only';
    },
  },
  {
    name: 'improve-harness',
    aliases: [],
    description: 'Analyze and improve the SuperLiora harness codebase (self-improvement mode)',
    priority: 75,
    argumentHint: '[area] [--auto]',
    completeArgs: improveHarnessArgumentCompletions,
    availability: () => 'idle-only',
  },
  {
    name: 'init',
    aliases: [],
    description: 'Analyze the codebase and generate AGENTS.md',
  },
  {
    name: 'fork',
    aliases: [],
    description: 'Fork the current session (`/fork --worktree [name]` for git isolation)',
    priority: 80,
  },
  {
    name: 'title',
    aliases: ['rename'],
    description: 'Set or show session title',
    priority: 60,
    argumentHint: '<title>',
    availability: 'always',
  },
  {
    name: 'usage',
    aliases: [],
    description: 'Show session tokens + context window + plan quotas',
    priority: 80,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'quota',
    aliases: [],
    description: 'Show live provider subscription quotas and API credits',
    priority: 80,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'status',
    aliases: [],
    description: 'Show current session and runtime status',
    priority: 100,
    availability: 'always',
  },
  {
    name: 'diff',
    aliases: [],
    description: 'Show working-tree changes as a review panel',
    priority: 85,
    argumentHint: '[path]',
    availability: 'always',
  },
  {
    name: 'log',
    aliases: ['git'],
    description: 'Browse recent commits',
    priority: 82,
    argumentHint: '[filter]',
    availability: 'always',
  },
  {
    name: 'errors',
    aliases: ['problems'],
    description: 'Browse errors from the current session transcript',
    priority: 81,
    availability: 'always',
  },
  {
    name: 'files',
    aliases: ['tree', 'explorer'],
    description: 'Browse project files (git-aware)',
    priority: 84,
    availability: 'always',
  },
  {
    name: 'search',
    aliases: ['grep'],
    description: 'Search project file contents',
    priority: 83,
    argumentHint: '<pattern>',
    availability: 'always',
  },
  {
    name: 'web',
    aliases: ['fetch'],
    description: 'Fetch a URL and view its readable content',
    priority: 80,
    argumentHint: '<url>',
    availability: 'always',
  },
  {
    name: 'blame',
    aliases: [],
    description: 'Show git blame for a file',
    priority: 79,
    argumentHint: '<path>',
    availability: 'always',
  },
  {
    name: 'aquarium',
    aliases: ['tank'],
    description: 'Overlay a Welcome-sized Jewel Tank (covers chat until the next message)',
    priority: 70,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'feed',
    aliases: ['food'],
    description: 'Drop food into the visible Jewel Tank',
    priority: 70,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'upgrade',
    aliases: ['update'],
    description: 'Open Upgrade Studio — check and install updates (/update same)',
    priority: 90,
    availability: 'always',
  },
  {
    name: 'context-os',
    aliases: ['ctx'],
    description: 'Diagnose Context OS continuity/evidence + privacy (ZDR) posture',
    priority: 85,
    argumentHint: '[query]',
    availability: 'always',
  },
  {
    name: 'undo',
    aliases: [],
    description: 'Withdraw the last prompt from the transcript',
    priority: 80,
    availability: 'idle-only',
  },
  {
    name: 'rewind',
    aliases: [],
    description: 'Restore files from the last agent write/edit turn snapshot',
    priority: 80,
    argumentHint: '[turnId]',
    availability: 'idle-only',
  },
  {
    name: 'loop',
    aliases: [],
    description: 'Repeat a prompt on an interval inside this conversation',
    priority: 75,
    argumentHint: '[interval] <prompt> | stop [id] | list',
    completeArgs: loopArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'retry',
    aliases: [],
    description: 'Resend your last message (also: Hub → Chat → Retry)',
    priority: 80,
    availability: 'idle-only',
  },
  {
    name: 'editor',
    aliases: [],
    description: 'Set the external editor for Ctrl-G',
    priority: 60,
    argumentHint: '[code --wait|vim|nvim|nano]',
    completeArgs: editorArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'theme',
    aliases: [],
    description: 'Set the terminal UI theme',
    priority: 60,
    argumentHint: '[auto|dark|light|import <source>]',
    completeArgs: themeArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'media',
    aliases: [],
    description: 'Set media fallback when the chat model is text-only',
    priority: 55,
    availability: 'always',
  },
  {
    name: 'appearance',
    aliases: ['skin'],
    description: 'Tune TUI motion, density, and background',
    priority: 60,
    argumentHint: '[profile|density|timestamps|particles|…]',
    completeArgs: appearanceArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'persona',
    aliases: ['character'],
    description: 'Customize agent personality, tone, and response style',
    priority: 60,
    argumentHint: '[list|set|name|tone|personality|instructions|clear|help]',
    completeArgs: personaArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'logout',
    aliases: ['disconnect'],
    description: 'Log out of a configured provider',
    priority: 40,
  },
  {
    name: 'login',
    aliases: [],
    description: 'Select a platform and authenticate',
    priority: 40,
  },
  {
    name: 'accounts',
    aliases: [],
    description: 'Manage OAuth account pools (promote, label, remove)',
    priority: 40,
    availability: 'always',
  },
  {
    name: 'export-md',
    aliases: ['export'],
    description: 'Export current session as a Markdown file',
    priority: 40,
  },
  {
    name: 'export-debug-zip',
    aliases: [],
    description: 'Export current session as a debug ZIP archive',
    priority: 40,
    visibility: 'diagnostic',
  },
  {
    name: 'exit',
    aliases: ['quit', 'q'],
    description: 'Exit the application',
    priority: 20,
  },
  {
    name: 'version',
    aliases: [],
    description: 'Show version information',
    priority: 20,
    availability: 'always',
  }
] as const satisfies readonly LioraSlashCommand[];
