/**
 * Declarative slash command metadata — session, workspace, and auth commands.
 */

import type { LioraSlashCommand } from '../types';
import { ttui } from '#/tui/utils/tui-i18n';
import {
  thinkingArgumentCompletions,
  helpArgumentCompletions,
  jobArgumentCompletions,
  jobsArgumentCompletions,
  addDirArgumentCompletions,
  folderArgumentCompletions,
  editorArgumentCompletions,
  themeArgumentCompletions,
  appearanceArgumentCompletions,
  localeArgumentCompletions,
  performanceArgumentCompletions,
  hostSetupArgumentCompletions,
} from './completion-specs';
import { transcriptArgumentCompletions } from '../session/transcript';
import { neatArgumentCompletions } from '../session/neat';

function slashDesc(name: string): string {
  return ttui(`tui.slash.${name}`);
}

export function getBuiltinSlashCommandsSession(): readonly LioraSlashCommand[] {
  return [
{
    name: 'model',
    aliases: [],
    description: slashDesc('model'),
    priority: 100,
    availability: 'always',
  },
  {
    name: 'thinking',
    aliases: ['think', 'reasoning', 'effort', 'depth'],
    description: slashDesc('thinking'),
    priority: 100,
    argumentHint: '[off|on|low|medium|high|xhigh|max]',
    completeArgs: thinkingArgumentCompletions,
    availability: 'idle-only',
  },
  {
    name: 'btw',
    aliases: [],
    description: slashDesc('btw'),
    priority: 90,
    availability: 'always',
  },
  {
    name: 'transcript',
    aliases: [],
    description: slashDesc('transcript'),
    priority: 80,
    argumentHint: '[minimal|compact|standard|full]',
    completeArgs: transcriptArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'neat',
    aliases: [],
    description: slashDesc('neat'),
    priority: 80,
    argumentHint: '[on|off|toggle|status]',
    completeArgs: neatArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'help',
    aliases: ['h'],
    description: slashDesc('help'),
    priority: 100,
    completeArgs: helpArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'new',
    aliases: ['clear'],
    description: slashDesc('new'),
    priority: 80,
  },
  {
    name: 'sessions',
    aliases: ['resume'],
    description: slashDesc('sessions'),
    priority: 80,
  },
  {
    name: 'folder',
    aliases: ['workspace', 'open', 'cd'],
    description: slashDesc('folder'),
    priority: 90,
    argumentHint: '[path]',
    completeArgs: folderArgumentCompletions,
    availability: 'idle-only',
  },
  {
    name: 'jobs',
    aliases: [],
    description: slashDesc('jobs'),
    priority: 88,
    argumentHint: '[board|deck [id]|dock|bg|job_id]',
    completeArgs: jobsArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'job',
    aliases: [],
    description: slashDesc('job'),
    priority: 88,
    argumentHint: 'board | deck [id] | dock | bg | list | inbox | resume [id] | cancel <id> | inspect <id>',
    completeArgs: jobArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'add-dir',
    aliases: [],
    description: slashDesc('add-dir'),
    priority: 60,
    availability: 'idle-only',
    argumentHint: '[list] | <path>',
    completeArgs: addDirArgumentCompletions,
  },
  {
    name: 'reload',
    aliases: [],
    description: slashDesc('reload'),
    priority: 60,
    visibility: 'advanced',
    availability: 'idle-only',
  },
  {
    name: 'reload-tui',
    aliases: [],
    description: slashDesc('reload-tui'),
    priority: 60,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'compact',
    aliases: [],
    description: slashDesc('compact'),
    priority: 80,
    argumentHint: '<instruction>',
  },
  {
    name: 'queue',
    aliases: ['clear-queue'],
    description: slashDesc('queue'),
    priority: 80,
    argumentHint: 'clear',
    // Clearing the queue is safe mid-turn: the queue is a TUI-side buffer.
    availability: 'always',
  },
  {
    name: 'fork',
    aliases: [],
    description: slashDesc('fork'),
    priority: 80,
  },
  {
    name: 'title',
    aliases: ['rename'],
    description: slashDesc('title'),
    priority: 60,
    argumentHint: '<title>',
    availability: 'always',
  },
  {
    name: 'usage',
    aliases: [],
    description: slashDesc('usage'),
    priority: 80,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'quota',
    aliases: [],
    description: slashDesc('quota'),
    priority: 80,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'status',
    aliases: [],
    description: slashDesc('status'),
    priority: 100,
    availability: 'always',
  },
  {
    name: 'host-setup',
    aliases: ['windows-setup', 'macos-setup', 'linux-setup', 'vibe-setup', 'terminal-setup'],
    description: slashDesc('host-setup'),
    priority: 85,
    argumentHint: '[status|apply]',
    completeArgs: hostSetupArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'diff',
    aliases: [],
    description: slashDesc('diff'),
    priority: 85,
    argumentHint: '[path]',
    availability: 'always',
  },
  {
    name: 'log',
    aliases: ['git'],
    description: slashDesc('log'),
    priority: 82,
    argumentHint: '[filter]',
    availability: 'always',
  },
  {
    name: 'errors',
    aliases: ['problems'],
    description: slashDesc('errors'),
    priority: 81,
    availability: 'always',
  },
  {
    name: 'files',
    aliases: ['tree', 'explorer'],
    description: slashDesc('files'),
    priority: 84,
    availability: 'always',
  },
  {
    name: 'search',
    aliases: ['grep'],
    description: slashDesc('search'),
    priority: 83,
    argumentHint: '<pattern>',
    availability: 'always',
  },
  {
    name: 'web',
    aliases: ['fetch'],
    description: slashDesc('web'),
    priority: 80,
    argumentHint: '<url>',
    availability: 'always',
  },
  {
    name: 'blame',
    aliases: [],
    description: slashDesc('blame'),
    priority: 79,
    argumentHint: '<path>',
    availability: 'always',
  },
  {
    name: 'upgrade',
    aliases: ['update'],
    description: slashDesc('upgrade'),
    argumentHint: '[--main]',
    priority: 90,
    availability: 'always',
  },
  {
    name: 'undo',
    aliases: [],
    description: slashDesc('undo'),
    priority: 80,
    availability: 'idle-only',
  },
  {
    name: 'rewind',
    aliases: [],
    description: slashDesc('rewind'),
    priority: 80,
    argumentHint: '[turnId]',
    availability: 'idle-only',
  },
  {
    name: 'retry',
    aliases: [],
    description: slashDesc('retry'),
    priority: 80,
    availability: 'idle-only',
  },
  {
    name: 'editor',
    aliases: [],
    description: slashDesc('editor'),
    priority: 60,
    argumentHint: '[code --wait|vim|nvim|nano]',
    completeArgs: editorArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'theme',
    aliases: [],
    description: slashDesc('theme'),
    priority: 60,
    argumentHint: '[auto|dark|light|import <source>]',
    completeArgs: themeArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'locale',
    aliases: [],
    description: slashDesc('locale'),
    priority: 60,
    argumentHint: '[auto|en|ko]',
    completeArgs: localeArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'appearance',
    aliases: ['skin'],
    description: slashDesc('appearance'),
    priority: 60,
    argumentHint: '[profile|density|timestamps|particles|…]',
    completeArgs: appearanceArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'performance',
    aliases: ['perf'],
    description: slashDesc('performance'),
    priority: 60,
    argumentHint: '[off|auto|on]',
    completeArgs: performanceArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'logout',
    aliases: ['disconnect'],
    description: slashDesc('logout'),
    priority: 40,
  },
  {
    name: 'login',
    aliases: [],
    description: slashDesc('login'),
    priority: 40,
  },
  {
    name: 'github-connect',
    aliases: [],
    description: slashDesc('github-connect'),
    priority: 40,
    availability: 'always',
  },
  {
    name: 'accounts',
    aliases: [],
    description: slashDesc('accounts'),
    priority: 40,
    availability: 'always',
  },
  {
    name: 'export-md',
    aliases: ['export'],
    description: slashDesc('export-md'),
    priority: 40,
  },
  {
    name: 'exit',
    aliases: ['quit', 'q'],
    description: slashDesc('exit'),
    priority: 20,
  },
  {
    name: 'version',
    aliases: [],
    description: slashDesc('version'),
    priority: 20,
    availability: 'always',
  }
] as const satisfies readonly LioraSlashCommand[];
}
