/**
 * Declarative slash command metadata — session, workspace, and auth commands.
 */

import type { LioraSlashCommand } from '../types';
import { ttui } from '#/tui/utils/tui-i18n';
import {
  toggleOnOffArgumentCompletions,
  permissionArgumentCompletions,
  contextArgumentCompletions,
  premiumArgumentCompletions,
  planArgumentCompletions,
  thinkingArgumentCompletions,
  helpArgumentCompletions,
  extensionsArgumentCompletions,
  cronArgumentCompletions,
  jobArgumentCompletions,
  jobsArgumentCompletions,
  memoryArgumentCompletions,
  addDirArgumentCompletions,
  loopArgumentCompletions,
  goalArgumentCompletions,
  editorArgumentCompletions,
  themeArgumentCompletions,
  appearanceArgumentCompletions,
  personaArgumentCompletions,
  localeArgumentCompletions,
  performanceArgumentCompletions,
  hostSetupArgumentCompletions,
} from './completion-specs';
import { pluginsArgumentCompletions } from '../plugins/plugins';
import { transcriptArgumentCompletions } from '../session/transcript';
import { neatArgumentCompletions } from '../session/neat';

function slashDesc(name: string): string {
  return ttui(`tui.slash.${name}`);
}

export function getBuiltinSlashCommandsSession(): readonly LioraSlashCommand[] {
  return [
{
    name: 'model',
    aliases: [],
    description: slashDesc('model'),
    priority: 100,
    availability: 'always',
  },
  {
    name: 'thinking',
    aliases: ['think', 'reasoning', 'effort', 'depth'],
    description: slashDesc('thinking'),
    priority: 100,
    argumentHint: '[off|on|low|medium|high|xhigh|max]',
    completeArgs: thinkingArgumentCompletions,
    availability: 'idle-only',
  },
  {
    name: 'btw',
    aliases: [],
    description: slashDesc('btw'),
    priority: 90,
    availability: 'always',
  },
  {
    name: 'transcript',
    aliases: [],
    description: slashDesc('transcript'),
    priority: 80,
    argumentHint: '[minimal|compact|standard|full]',
    completeArgs: transcriptArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'neat',
    aliases: [],
    description: slashDesc('neat'),
    priority: 80,
    argumentHint: '[on|off|toggle|status]',
    completeArgs: neatArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'help',
    aliases: ['h'],
    description: slashDesc('help'),
    priority: 100,
    completeArgs: helpArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'new',
    aliases: ['clear'],
    description: slashDesc('new'),
    priority: 80,
  },
  {
    name: 'sessions',
    aliases: ['resume'],
    description: slashDesc('sessions'),
    priority: 80,
  },
  {
    name: 'extensions',
    aliases: ['ext', 'import-claude'],
    description: slashDesc('extensions'),
    priority: 70,
    availability: 'always',
    argumentHint: '[plugins|hooks|skills|mcp|claude]',
    completeArgs: extensionsArgumentCompletions,
  },
  {
    name: 'tasks',
    aliases: ['task'],
    description: slashDesc('tasks'),
    priority: 80,
    availability: 'always',
  },
  {
    name: 'agents',
    aliases: ['workers', 'mission-control'],
    description: slashDesc('agents'),
    priority: 88,
    argumentHint: '[auto|pinned|hidden]',
    availability: 'always',
  },
  {
    name: 'jobs',
    aliases: [],
    description: slashDesc('jobs'),
    priority: 88,
    argumentHint: '[board|deck [job_id]|job_id]',
    completeArgs: jobsArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'job',
    aliases: [],
    description: slashDesc('job'),
    priority: 88,
    argumentHint: 'board | deck [id] | list | inbox | resume [id] | cancel <id> | inspect <id>',
    completeArgs: jobArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'cron',
    aliases: [],
    description: slashDesc('cron'),
    priority: 60,
    argumentHint: 'list | delete <jobId>',
    completeArgs: cronArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'mcp',
    aliases: [],
    description: slashDesc('mcp'),
    priority: 60,
    availability: 'always',
  },
  {
    name: 'tools',
    aliases: ['tool'],
    description: slashDesc('tools'),
    priority: 70,
    availability: 'always',
  },
  {
    name: 'eyes',
    aliases: ['eye'],
    description: slashDesc('eyes'),
    priority: 70,
    availability: 'always',
  },
  {
    name: 'harness',
    aliases: [],
    description: slashDesc('harness'),
    priority: 70,
    availability: 'always',
  },
  {
    name: 'plugins',
    aliases: [],
    description: slashDesc('plugins'),
    priority: 60,
    visibility: 'advanced',
    availability: 'always',
    argumentHint: '[list|install|marketplace|info|mcp|enable|disable|remove|reload]',
    completeArgs: pluginsArgumentCompletions,
  },
  {
    name: 'memory',
    aliases: [],
    description: slashDesc('memory'),
    priority: 60,
    availability: 'always',
    argumentHint: '[remember|recall|reflect|forget|inspect]',
    completeArgs: memoryArgumentCompletions,
  },
  {
    name: 'add-dir',
    aliases: [],
    description: slashDesc('add-dir'),
    priority: 60,
    availability: 'idle-only',
    argumentHint: '[list] | <path>',
    completeArgs: addDirArgumentCompletions,
  },
  {
    name: 'experiments',
    aliases: ['experimental'],
    description: slashDesc('experiments'),
    priority: 60,
    visibility: 'advanced',
    availability: 'idle-only',
  },
  {
    name: 'reload',
    aliases: [],
    description: slashDesc('reload'),
    priority: 60,
    visibility: 'advanced',
    availability: 'idle-only',
  },
  {
    name: 'reload-tui',
    aliases: [],
    description: slashDesc('reload-tui'),
    priority: 60,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'compact',
    aliases: [],
    description: slashDesc('compact'),
    priority: 80,
    argumentHint: '<instruction>',
  },
  {
    name: 'refine',
    aliases: [],
    description: slashDesc('refine'),
    priority: 80,
    argumentHint: '[--global] [status|rollback <id>] | [instructions]',
  },
  {
    name: 'goal',
    aliases: [],
    description: slashDesc('goal'),
    priority: 80,
    argumentHint: '[status|pause|resume|cancel|replace|next] | <objective>',
    completeArgs: goalArgumentCompletions,
    // status / pause / cancel are always available; creation, replacement, and
    // resume start (or restart) a turn and so are idle-only.
    availability: (args) => {
      const trimmed = args.trim();
      if (trimmed === 'next' || trimmed.startsWith('next ')) return 'always';
      return trimmed === '' || trimmed === 'status' || trimmed === 'pause' || trimmed === 'cancel'
        ? 'always'
        : 'idle-only';
    },
  },
  {
    name: 'init',
    aliases: [],
    description: slashDesc('init'),
  },
  {
    name: 'fork',
    aliases: [],
    description: slashDesc('fork'),
    priority: 80,
  },
  {
    name: 'title',
    aliases: ['rename'],
    description: slashDesc('title'),
    priority: 60,
    argumentHint: '<title>',
    availability: 'always',
  },
  {
    name: 'usage',
    aliases: [],
    description: slashDesc('usage'),
    priority: 80,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'quota',
    aliases: [],
    description: slashDesc('quota'),
    priority: 80,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'status',
    aliases: [],
    description: slashDesc('status'),
    priority: 100,
    availability: 'always',
  },
  {
    name: 'host-setup',
    aliases: ['windows-setup', 'macos-setup', 'linux-setup', 'vibe-setup', 'terminal-setup'],
    description: slashDesc('host-setup'),
    priority: 85,
    argumentHint: '[status|apply]',
    completeArgs: hostSetupArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'diff',
    aliases: [],
    description: slashDesc('diff'),
    priority: 85,
    argumentHint: '[path]',
    availability: 'always',
  },
  {
    name: 'log',
    aliases: ['git'],
    description: slashDesc('log'),
    priority: 82,
    argumentHint: '[filter]',
    availability: 'always',
  },
  {
    name: 'errors',
    aliases: ['problems'],
    description: slashDesc('errors'),
    priority: 81,
    availability: 'always',
  },
  {
    name: 'files',
    aliases: ['tree', 'explorer'],
    description: slashDesc('files'),
    priority: 84,
    availability: 'always',
  },
  {
    name: 'search',
    aliases: ['grep'],
    description: slashDesc('search'),
    priority: 83,
    argumentHint: '<pattern>',
    availability: 'always',
  },
  {
    name: 'web',
    aliases: ['fetch'],
    description: slashDesc('web'),
    priority: 80,
    argumentHint: '<url>',
    availability: 'always',
  },
  {
    name: 'blame',
    aliases: [],
    description: slashDesc('blame'),
    priority: 79,
    argumentHint: '<path>',
    availability: 'always',
  },
  {
    name: 'aquarium',
    aliases: ['tank'],
    description: slashDesc('aquarium'),
    priority: 70,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'feed',
    aliases: ['food'],
    description: slashDesc('feed'),
    priority: 70,
    visibility: 'advanced',
    availability: 'always',
  },
  {
    name: 'upgrade',
    aliases: ['update'],
    description: slashDesc('upgrade'),
    argumentHint: '[--main]',
    priority: 90,
    availability: 'always',
  },
  {
    name: 'context-os',
    aliases: ['ctx'],
    description: slashDesc('context-os'),
    priority: 85,
    argumentHint: '[query]',
    availability: 'always',
  },
  {
    name: 'undo',
    aliases: [],
    description: slashDesc('undo'),
    priority: 80,
    availability: 'idle-only',
  },
  {
    name: 'rewind',
    aliases: [],
    description: slashDesc('rewind'),
    priority: 80,
    argumentHint: '[turnId]',
    availability: 'idle-only',
  },
  {
    name: 'loop',
    aliases: [],
    description: slashDesc('loop'),
    priority: 75,
    argumentHint: '[interval] <prompt> | stop [id] | list',
    completeArgs: loopArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'retry',
    aliases: [],
    description: slashDesc('retry'),
    priority: 80,
    availability: 'idle-only',
  },
  {
    name: 'editor',
    aliases: [],
    description: slashDesc('editor'),
    priority: 60,
    argumentHint: '[code --wait|vim|nvim|nano]',
    completeArgs: editorArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'theme',
    aliases: [],
    description: slashDesc('theme'),
    priority: 60,
    argumentHint: '[auto|dark|light|import <source>]',
    completeArgs: themeArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'media',
    aliases: [],
    description: slashDesc('media'),
    priority: 55,
    availability: 'always',
  },
  {
    name: 'locale',
    aliases: [],
    description: slashDesc('locale'),
    priority: 60,
    argumentHint: '[auto|en|ko]',
    completeArgs: localeArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'appearance',
    aliases: ['skin'],
    description: slashDesc('appearance'),
    priority: 60,
    argumentHint: '[profile|density|timestamps|particles|…]',
    completeArgs: appearanceArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'performance',
    aliases: ['perf'],
    description: slashDesc('performance'),
    priority: 60,
    argumentHint: '[off|auto|on]',
    completeArgs: performanceArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'persona',
    aliases: ['character'],
    description: slashDesc('persona'),
    priority: 60,
    argumentHint: '[list|set|name|tone|personality|instructions|clear|help]',
    completeArgs: personaArgumentCompletions,
    availability: 'always',
  },
  {
    name: 'logout',
    aliases: ['disconnect'],
    description: slashDesc('logout'),
    priority: 40,
  },
  {
    name: 'login',
    aliases: [],
    description: slashDesc('login'),
    priority: 40,
  },
  {
    name: 'accounts',
    aliases: [],
    description: slashDesc('accounts'),
    priority: 40,
    availability: 'always',
  },
  {
    name: 'export-md',
    aliases: ['export'],
    description: slashDesc('export-md'),
    priority: 40,
  },
  {
    name: 'exit',
    aliases: ['quit', 'q'],
    description: slashDesc('exit'),
    priority: 20,
  },
  {
    name: 'version',
    aliases: [],
    description: slashDesc('version'),
    priority: 20,
    availability: 'always',
  }
] as const satisfies readonly LioraSlashCommand[];
}
