/**
 * Pure Seed Spec builders for Ultra Plan.
 */

import type {
  OntologyField,
  SeedSpec,
} from './ultra-plan-mode';

export function buildSeedSpec(
  goal: string,
  constraints: readonly string[],
  acceptanceCriteria: readonly string[],
  ontologyName: string,
  ontologyFields: readonly OntologyField[],
  autoGenerated = false,
  now = new Date(),
): SeedSpec {
  return {
    goal,
    taskType: 'code',
    constraints: [...constraints],
    acceptanceCriteria: acceptanceCriteria.map((desc, i) => ({
      id: `ac_${i + 1}`,
      description: desc,
      status: 'pending',
    })),
    ontology: {
      name: ontologyName,
      description: `Ontology for ${ontologyName}`,
      fields: [...ontologyFields],
    },
    evaluationPrinciples: [
      { name: 'completeness', description: 'All requirements are met', weight: 1.0 },
      { name: 'correctness', description: 'Implementation is correct', weight: 1.0 },
      { name: 'clarity', description: 'Code is clear and maintainable', weight: 0.8 },
    ],
    exitConditions: [
      {
        name: 'all_criteria_met',
        description: 'All acceptance criteria satisfied',
        criteria: '100% criteria pass',
      },
    ],
    ambiguityScore: 0.15,
    autoGenerated,
    createdAt: now.toISOString(),
  };
}
