/**
 * Pure Seed Spec / Ontology normalizers for Ultra Plan LLM extraction.
 */

import type {
  OntologyField,
  OntologySchema,
  SeedSpec,
} from './ultra-plan-mode';

export type BuildSeedSpecFn = (
  goal: string,
  constraints: string[],
  acceptanceCriteria: string[],
  ontologyName: string,
  ontologyFields: OntologyField[],
  autoGenerated?: boolean,
) => SeedSpec;

export function normalizeOntology(raw: unknown, defaultName: string): OntologySchema {
  const parsed = raw as Partial<{
    name: string;
    description: string;
    fields: unknown[];
  }>;
  const name =
    typeof parsed?.name === 'string' && parsed.name.trim().length > 0
      ? parsed.name.trim()
      : defaultName;
  const description =
    typeof parsed?.description === 'string' && parsed.description.trim().length > 0
      ? parsed.description.trim()
      : `Ontology for ${name}`;
  const fields = Array.isArray(parsed?.fields)
    ? parsed.fields
        .filter((f): f is { name: string; type: string; description: string; required: boolean } => {
          const item = f as { name?: unknown; type?: unknown; description?: unknown; required?: unknown };
          return (
            typeof item.name === 'string' &&
            typeof item.type === 'string' &&
            typeof item.description === 'string' &&
            typeof item.required === 'boolean'
          );
        })
        .map((f) => ({ name: f.name, type: f.type, description: f.description, required: f.required }))
    : [];
  return { name, description, fields: [...fields] };
}

export function normalizeSeedSpec(
  raw: unknown,
  ontologyName: string,
  autoGenerated: boolean,
  fallbackGoal: string,
  buildSeedSpec: BuildSeedSpecFn,
): SeedSpec {
  const parsed = raw as Partial<{
    goal: string;
    taskType: string;
    constraints: unknown[];
    acceptanceCriteria: unknown[];
    ontology: Partial<{
      name: string;
      description: string;
      fields: unknown[];
    }>;
    evaluationPrinciples: unknown[];
    exitConditions: unknown[];
    ambiguityScore: number;
  }>;
  const goal =
    typeof parsed.goal === 'string' && parsed.goal.trim().length > 0
      ? parsed.goal.trim()
      : fallbackGoal;
  const taskType = ['code', 'research', 'analysis'].includes(parsed.taskType as string)
    ? (parsed.taskType as SeedSpec['taskType'])
    : 'code';
  const constraints = Array.isArray(parsed.constraints)
    ? parsed.constraints.filter((c): c is string => typeof c === 'string')
    : [];
  const acceptanceCriteria = Array.isArray(parsed.acceptanceCriteria)
    ? parsed.acceptanceCriteria.filter((c): c is string => typeof c === 'string')
    : [];
  const ontology = normalizeOntology(parsed.ontology, ontologyName);
  const evaluationPrinciples = Array.isArray(parsed.evaluationPrinciples)
    ? parsed.evaluationPrinciples
        .filter((p): p is { name: string; description: string; weight: number } => {
          const item = p as { name?: unknown; description?: unknown; weight?: unknown };
          return (
            typeof item.name === 'string' &&
            typeof item.description === 'string' &&
            typeof item.weight === 'number'
          );
        })
        .map((p) => ({ name: p.name, description: p.description, weight: p.weight }))
    : [
        { name: 'completeness', description: 'All requirements are met', weight: 1.0 },
        { name: 'correctness', description: 'Implementation is correct', weight: 1.0 },
        { name: 'clarity', description: 'Code is clear and maintainable', weight: 0.8 },
      ];
  const exitConditions = Array.isArray(parsed.exitConditions)
    ? parsed.exitConditions
        .filter((c): c is { name: string; description: string; criteria: string } => {
          const item = c as { name?: unknown; description?: unknown; criteria?: unknown };
          return (
            typeof item.name === 'string' &&
            typeof item.description === 'string' &&
            typeof item.criteria === 'string'
          );
        })
        .map((c) => ({ name: c.name, description: c.description, criteria: c.criteria }))
    : [{ name: 'all_criteria_met', description: 'All acceptance criteria satisfied', criteria: '100% criteria pass' }];
  const ambiguityScore = typeof parsed.ambiguityScore === 'number' ? parsed.ambiguityScore : 0.15;
  const seed = buildSeedSpec(
    goal,
    constraints,
    acceptanceCriteria,
    ontology.name,
    [...ontology.fields],
    autoGenerated,
  );
  // buildSeedSpec overrides ambiguityScore; patch it back if LLM provided one
  return { ...seed, taskType, evaluationPrinciples, exitConditions, ambiguityScore };
}
