/**
 * Shared Ultra Plan type definitions.
 */

import type { LLMAmbiguityResult } from './ultra-plan-ambiguity-heuristic';
import type { UltraPlanRequiredSection } from './ultra-plan-section-guidance';
import type { StagnationDetection } from './ultra-plan-stagnation';

export interface SeedSpec {
  readonly goal: string;
  readonly taskType: 'code' | 'research' | 'analysis';
  readonly constraints: readonly string[];
  readonly acceptanceCriteria: readonly AcceptanceCriterion[];
  readonly ontology: OntologySchema;
  readonly evaluationPrinciples: readonly EvaluationPrinciple[];
  readonly exitConditions: readonly ExitCondition[];
  readonly ambiguityScore: number;
  readonly autoGenerated: boolean;
  readonly createdAt: string;
}

export interface AcceptanceCriterion {
  readonly id: string;
  readonly description: string;
  readonly status: 'pending' | 'in_progress' | 'passed' | 'failed';
  readonly children?: readonly AcceptanceCriterion[];
}

export interface OntologySchema {
  readonly name: string;
  readonly description: string;
  readonly fields: readonly OntologyField[];
}

export interface OntologyField {
  readonly name: string;
  readonly type: string;
  readonly description: string;
  readonly required: boolean;
}

export interface EvaluationPrinciple {
  readonly name: string;
  readonly description: string;
  readonly weight: number;
}

export interface ExitCondition {
  readonly name: string;
  readonly description: string;
  readonly criteria: string;
}

export interface DriftMetrics {
  readonly goalDrift: number;
  readonly constraintDrift: number;
  readonly ontologyDrift: number;
}

export type InterviewAnswerOrigin = 'user' | 'code' | 'research' | 'auto';

export type InterviewPerspective =
  | 'researcher'
  | 'simplifier'
  | 'architect'
  | 'breadth-keeper'
  | 'seed-closer';

export type UltraPlanPhase = 'research' | 'interview' | 'design' | 'review' | 'write' | 'exit';

export type AmbiguityMilestone = 'initial' | 'progress' | 'refined' | 'ready';

export interface InterviewRound {
  readonly roundNumber: number;
  readonly question: string;
  readonly userResponse: string;
  readonly timestamp: number;
  /** Where the answer came from. 'user' = user decided via AskUserQuestion;
   *  'code' = agent answered from codebase evidence; 'research' = external research;
   *  'auto' = Auto/YOLO short-circuited AskUserQuestion (non-user for rhythm). */
  readonly origin: InterviewAnswerOrigin;
}

export interface AmbiguityScoreBreakdown {
  readonly name: string;
  readonly clarityScore: number;
  readonly weight: number;
  readonly justification: string;
}

export interface AmbiguityScoreResult {
  readonly overallScore: number;
  readonly breakdown: readonly AmbiguityScoreBreakdown[];
  /**
   * Soft seed completeness: ambiguity floors + closed seed gaps + verifiable
   * UltraGoal. Guidance for seed quality only — does not hard-gate Design.
   */
  readonly isReadyForSeed: boolean;
  readonly milestone: AmbiguityMilestone;
  readonly floorFailures: readonly string[];
  /** True when the score was derived from the deterministic heuristic because
   *  the LLM scoring engine was unavailable or returned invalid JSON. */
  readonly usedHeuristicFallback?: boolean;
}

export interface InterviewState {
  readonly rounds: readonly InterviewRound[];
  readonly initialContext: string;
  readonly ambiguityScore: AmbiguityScoreResult | null;
  readonly completionCandidateStreak: number;
  readonly lastReadyEvidenceHash?: string;
  readonly lastReadyRoundCount?: number;
  /** Evidence hash of the last scored round — prevents re-calling the LLM
   *  when the evidence has not changed (eliminates score oscillation). */
  readonly lastScoredEvidenceHash?: string;
  /** Cached LLM ambiguity result for the current evidence hash. */
  readonly cachedLlmResult?: LLMAmbiguityResult;
  /** Once true, Design hard-readiness (verifiable UltraGoal) stays locked until
   *  a new interview round changes evidence — LLM non-determinism cannot
   *  un-ready the Design gate. Soft seed floors are not monotonic. */
  readonly monotonicReadyLocked?: boolean;
  /** Consecutive rounds where origin was 'code' or 'research' (not 'user').
   *  Reset to 0 on each 'user' answer. Drives the Dialectic Rhythm Guard. */
  readonly consecutiveNonUserAnswers: number;
  /** Wall-clock timestamp when the interview phase started. Used to filter
   *  pre-interview user prompts out of the ambiguity evidence. */
  readonly startedAtTimestamp: number;
}

export interface UltraPlanReadiness {
  /** Hard design readiness — true iff the UltraGoal is verifiable. */
  readonly ready: boolean;
  /** Hard ready held for the required completion streak. */
  readonly stableReady: boolean;
  /** Soft seed guidance: required sections still open. */
  readonly openGaps: readonly UltraPlanRequiredSection[];
  readonly ambiguityScore: AmbiguityScoreResult;
  /** Same as design hard-ready (verifiable UltraGoal, monotonic-adjusted). */
  readonly verifiableGoal: boolean;
  readonly completionCandidateStreak: number;
  /** Soft seed guidance: clarity floor failures. */
  readonly floorFailures: readonly string[];
  /** True when the ambiguity score was derived from the heuristic fallback. */
  readonly usedHeuristicFallback?: boolean;
}

export type ThinkingPersona =
  | 'hacker'
  | 'researcher'
  | 'simplifier'
  | 'architect'
  | 'contrarian';

export interface LateralThinkingResult {
  readonly persona: ThinkingPersona;
  readonly prompt: string;
  readonly approachSummary: string;
  readonly questions: readonly string[];
}

export interface EvaluationPlan {
  readonly stage1Mechanical: boolean;
  readonly stage2Semantic: boolean;
  readonly stage3Consensus: boolean;
  readonly mechanicalChecks: readonly string[];
  readonly semanticCriteria: readonly string[];
}

export interface UltraPlanData {
  readonly seedSpec: SeedSpec | null;
  readonly driftMetrics: DriftMetrics | null;
  readonly stagnationPatterns: readonly StagnationDetection[];
  readonly lateralThinking: LateralThinkingResult | null;
  readonly evaluationPlan: EvaluationPlan | null;
}

export interface StagnationHistoryEntry {
  readonly timestamp: number;
  readonly phaseOutputs: readonly string[];
  readonly errorSignatures: readonly string[];
  readonly driftScores: readonly number[];
  readonly detections: readonly StagnationDetection[];
}
