/**
 * UltraPlanMode - Ouroboros-inspired advanced planning system.
 *
 * Integrates Seed Spec, AC Tree, Ontology, Drift Detection,
 * Stagnation Detection, and Lateral Thinking into the existing PlanMode.
 *
 * This is NOT a copy of Ouroboros; it is a natural evolution of
 * SuperLiora's plan mode, borrowing the most powerful concepts and
 * adapting them to the existing architecture.
 */

import type { Agent } from '..';
import { formatInterviewReadinessGuide } from './ultra-plan-interview-guide';

export {
  formatInterviewReadinessGuide,
  pickNextInterviewFocus,
  type InterviewReadinessGuideOptions,
} from './ultra-plan-interview-guide';

export {
  MAX_INTERVIEW_ROUNDS,
  ULTRA_PLAN_REQUIRED_SECTIONS,
  ULTRA_PLAN_SECTION_GUIDANCE,
  type UltraPlanRequiredSection,
} from './ultra-plan-section-guidance';

import {
  computeAmbiguityScoreHeuristic as computeAmbiguityScoreHeuristicPure,
  type LLMAmbiguityResult,
} from './ultra-plan-ambiguity-heuristic';

export { AMBIGUITY_THRESHOLD } from './ultra-plan-ambiguity-heuristic';
import { normalizeSeedSpec } from './ultra-plan-seed-normalize';
import {
  detectAllStagnation,
  hashText,
  type StagnationDetection,
} from './ultra-plan-stagnation';
import { buildAmbiguityScoreResult, openSeedGapsFromLlmResult } from './ultra-plan-score-result';
import { buildSeedSpec as buildSeedSpecPure } from './ultra-plan-seed-build';
import { getInterviewPerspectiveDescription } from './ultra-plan-perspective';
import { buildLateralThinkingResult } from './ultra-plan-lateral';
import { buildDefaultEvaluationPlan } from './ultra-plan-evaluation';
import {
  appendInterviewRoundState,
  formatInterviewAnswerText,
  formatInterviewQuestionText,
} from './ultra-plan-interview-rounds';
import type { UltraPlanRequiredSection } from './ultra-plan-section-guidance';
import {
  buildInterviewEvidenceText,
  emitUltraPlanProgress,
} from './ultra-plan-interview-evidence';
import {
  calculateAmbiguityWithLlm,
  calculateDriftWithLlm,
  extractSeedSpecWithLlm,
} from './ultra-plan-llm-client';
import { buildHeuristicSeedSpecFromInterview } from './ultra-plan-seed-heuristic';

export type {
  AcceptanceCriterion,
  AmbiguityMilestone,
  AmbiguityScoreBreakdown,
  AmbiguityScoreResult,
  DriftMetrics,
  EvaluationPlan,
  EvaluationPrinciple,
  ExitCondition,
  InterviewAnswerOrigin,
  InterviewPerspective,
  InterviewRound,
  InterviewState,
  LateralThinkingResult,
  OntologyField,
  OntologySchema,
  SeedSpec,
  ThinkingPersona,
  UltraPlanData,
  UltraPlanPhase,
  UltraPlanReadiness,
} from './ultra-plan-types';

export {
  ULTRA_PLAN_DRIFT_THRESHOLD,
  ULTRA_PLAN_DRIFT_THRESHOLD_AUTO,
  combinedDrift,
  isDriftAcceptable,
} from './ultra-plan-drift';

export type { StagnationDetection, StagnationPatternType } from './ultra-plan-stagnation';

import type {
  AmbiguityScoreResult,
  DriftMetrics,
  EvaluationPlan,
  InterviewAnswerOrigin,
  InterviewPerspective,
  InterviewState,
  LateralThinkingResult,
  OntologyField,
  SeedSpec,
  StagnationHistoryEntry,
  ThinkingPersona,
  UltraPlanReadiness,
} from './ultra-plan-types';

const COMPLETION_STREAK_REQUIRED = 1;

export class UltraPlanModeEngine {
  private readonly agent: Agent;
  private _seedSpec: SeedSpec | null = null;
  private _driftMetrics: DriftMetrics | null = null;
  private _stagnationHistory: StagnationHistoryEntry[] = [];
  private _evaluationPlan: EvaluationPlan | null = null;
  private _lateralThinking: LateralThinkingResult | null = null;
  private _lastAmbiguityResult: LLMAmbiguityResult | null = null;

  constructor(agent: Agent) {
    this.agent = agent;
  }

  setSeedSpec(seed: SeedSpec): void {
    this._seedSpec = seed;
  }

  reopenInterviewForSeedRefinement(metrics: DriftMetrics): void {
    this._seedSpec = null;
    this._driftMetrics = metrics;
    this._lastAmbiguityResult = null;
    this._currentPerspective = 'researcher';
    this._interviewState = {
      ...this._interviewState,
      ambiguityScore: null,
      completionCandidateStreak: 0,
      lastReadyEvidenceHash: undefined,
      lastReadyRoundCount: -1,
      lastScoredEvidenceHash: undefined,
      cachedLlmResult: undefined,
      monotonicReadyLocked: false,
    };
  }

  get seedSpec(): SeedSpec | null {
    return this._seedSpec;
  }

  buildSeedSpec(
    goal: string,
    constraints: string[],
    acceptanceCriteria: string[],
    ontologyName: string,
    ontologyFields: OntologyField[],
    autoGenerated = false,
  ): SeedSpec {
    return buildSeedSpecPure(
      goal,
      constraints,
      acceptanceCriteria,
      ontologyName,
      ontologyFields,
      autoGenerated,
    );
  }

  generateSeedSpecFromInterview(
    goal: string,
    constraints: string[],
    acceptanceCriteria: string[],
    ontologyName: string,
    ontologyFields: OntologyField[],
    autoGenerated = false,
  ): SeedSpec {
    return this.buildSeedSpec(
      goal,
      constraints,
      acceptanceCriteria,
      ontologyName,
      ontologyFields,
      autoGenerated,
    );
  }

  async calculateDrift(currentOutput: string, constraintViolations: string[]): Promise<DriftMetrics> {
    if (!this._seedSpec) {
      return { goalDrift: 0, constraintDrift: 0, ontologyDrift: 0 };
    }
    const llmMetrics = await calculateDriftWithLlm(
      this.agent,
      this._seedSpec,
      currentOutput,
      constraintViolations,
    );
    if (llmMetrics !== null) {
      this._driftMetrics = llmMetrics;
      return llmMetrics;
    }
    throw new Error(
      'LLM-based drift evaluation failed: the LLM is unavailable or returned invalid JSON.',
    );
  }

  detectStagnation(
    phaseOutputs: string[],
    errorSignatures: string[],
    driftScores: number[],
  ): StagnationDetection[] {
    const results = detectAllStagnation(phaseOutputs, errorSignatures, driftScores);

    this._stagnationHistory.push({
      timestamp: Date.now(),
      phaseOutputs: [...phaseOutputs],
      errorSignatures: [...errorSignatures],
      driftScores: [...driftScores],
      detections: [...results],
    });

    return results;
  }

  private _hash(text: string): string {
    return hashText(text);
  }

  generateLateralThinking(
    persona: ThinkingPersona,
    problemContext: string,
    currentApproach: string,
  ): LateralThinkingResult {
    const result = buildLateralThinkingResult(persona, problemContext, currentApproach);
    this._lateralThinking = result;
    return result;
  }

  setEvaluationPlan(plan: EvaluationPlan): void {
    this._evaluationPlan = plan;
  }

  get evaluationPlan(): EvaluationPlan | null {
    return this._evaluationPlan;
  }

  generateDefaultEvaluationPlan(): EvaluationPlan {
    return buildDefaultEvaluationPlan();
  }

  serialize(): Record<string, unknown> {
    return {
      seedSpec: this._seedSpec,
      driftMetrics: this._driftMetrics,
      stagnationHistory: this._stagnationHistory,
      evaluationPlan: this._evaluationPlan,
      lateralThinking: this._lateralThinking,
      interviewState: this._interviewState,
      currentPerspective: this._currentPerspective,
    };
  }

  // ---------------------------------------------------------------------------
  // Interview & Ambiguity Scoring
  // ---------------------------------------------------------------------------

  private _currentPerspective: InterviewPerspective = 'researcher';
  private readonly _perspectives: InterviewPerspective[] = [
    'researcher',
    'simplifier',
    'architect',
    'breadth-keeper',
    'seed-closer',
  ];

  private _interviewState: InterviewState = {
    rounds: [],
    initialContext: '',
    ambiguityScore: null,
    completionCandidateStreak: 0,
    lastReadyEvidenceHash: undefined,
    lastReadyRoundCount: -1,
    lastScoredEvidenceHash: undefined,
    cachedLlmResult: undefined,
    monotonicReadyLocked: false,
    consecutiveNonUserAnswers: 0,
    startedAtTimestamp: 0,
  };

  get interviewState(): InterviewState {
    return this._interviewState;
  }

  get currentPerspective(): InterviewPerspective {
    return this._currentPerspective;
  }

  advancePerspective(): void {
    const idx = this._perspectives.indexOf(this._currentPerspective);
    this._currentPerspective = this._perspectives[(idx + 1) % this._perspectives.length] ?? 'researcher';
  }

  getPerspectiveDescription(): string {
    return getInterviewPerspectiveDescription(this._currentPerspective);
  }

  startInterview(initialContext: string): void {
    this._currentPerspective = 'researcher';
    this._lastAmbiguityResult = null;
    this._interviewState = {
      rounds: [],
      initialContext,
      ambiguityScore: null,
      completionCandidateStreak: 0,
      lastReadyEvidenceHash: undefined,
      lastScoredEvidenceHash: undefined,
      cachedLlmResult: undefined,
      monotonicReadyLocked: false,
      consecutiveNonUserAnswers: 0,
      startedAtTimestamp: Date.now(),
    };
  }

  addInterviewRound(
    question: string,
    userResponse: string,
    origin: InterviewAnswerOrigin = 'user',
  ): void {
    this.advancePerspective();
    this._interviewState = appendInterviewRoundState(
      this._interviewState,
      question,
      userResponse,
      origin,
    );
  }

  recordInterviewAnswers(
    questions: ReadonlyArray<{ readonly question: string; readonly header?: string }>,
    answers: Record<string, string | true>,
    origin: InterviewAnswerOrigin = 'user',
  ): void {
    this.addInterviewRound(
      formatInterviewQuestionText(questions),
      formatInterviewAnswerText(answers),
      origin,
    );
  }

  /**
   * Calculate ambiguity score from interview state using the LLM-based
   * Ouroboros-style clarity scorer. Regex heuristics have been removed; all
   * ambiguity dimensions are derived from the LLM's structured JSON response.
   *
   * Stability guarantees (prevents infinite interview loops):
   * - **Evidence-keyed cache**: if the evidence text has not changed since the
   *   last LLM call, the cached result is reused — no new LLM round, so the
   *   score cannot oscillate between calls.
   * - **Monotonic hard ready**: once the UltraGoal is verifiable for a given
   *   evidence era, Design hard-readiness stays true until a new interview
   *   round changes the evidence. Soft seed floors (`isReadyForSeed`) are
   *   not locked and do not re-block Design.
   * - **Max rounds**: after MAX_INTERVIEW_ROUNDS the readiness guide warns
   *   that the soft cap was hit; Design still requires a verifiable UltraGoal.
   */
  async calculateAmbiguityScore(
    signal?: AbortSignal,
    onProgress?: (text: string) => void,
  ): Promise<AmbiguityScoreResult> {
    const evidence = this.interviewEvidenceText();
    const evidenceHash = this._hash(evidence);

    // ── Evidence-keyed cache hit: reuse the LLM result without a new call.
    if (
      this._interviewState.lastScoredEvidenceHash === evidenceHash &&
      this._interviewState.cachedLlmResult !== undefined
    ) {
      return this.buildScoreResult(
        this._interviewState.cachedLlmResult,
        evidenceHash,
        onProgress,
        /* skipLlm */ true,
      );
    }

    emitUltraPlanProgress(onProgress, 'Analyzing your answers...');
    emitUltraPlanProgress(
      onProgress,
      'Scoring ambiguity across goal, constraints, and success criteria...',
    );

    let llmResult = await calculateAmbiguityWithLlm(this.agent, evidence, signal);
    // Automatic one-time retry before falling back to the deterministic
      // heuristic. This prevents a single transient LLM failure from blocking
      // the interview.
      llmResult ??= await calculateAmbiguityWithLlm(this.agent, evidence, signal);
    if (llmResult === null) {
      // LLM is unavailable or returning invalid JSON. Use a deterministic
      // heuristic so the interview can continue safely without throwing.
      emitUltraPlanProgress(
        onProgress,
        'Scoring engine unavailable — falling back to deterministic heuristic.',
      );
      const heuristicResult = computeAmbiguityScoreHeuristicPure(this._interviewState);
      this._lastAmbiguityResult = heuristicResult;
      this._interviewState = {
        ...this._interviewState,
        lastScoredEvidenceHash: evidenceHash,
        // cachedLlmResult is intentionally not set so the LLM is retried on
        // the next scoring attempt when it may be available again.
      };
      return this.buildScoreResult(
        heuristicResult,
        evidenceHash,
        onProgress,
        false,
        /* usedHeuristicFallback */ true,
      );
    }
    this._lastAmbiguityResult = llmResult;

    // Cache the LLM result for this evidence hash so subsequent calls
    // (e.g. interviewReadiness → calculateAmbiguityScore) don't re-call the
    // LLM and produce a different score.
    this._interviewState = {
      ...this._interviewState,
      lastScoredEvidenceHash: evidenceHash,
      cachedLlmResult: llmResult,
    };

    return this.buildScoreResult(llmResult, evidenceHash, onProgress, false);
  }

  /**
   * Build the {@link AmbiguityScoreResult} from a (possibly cached) LLM
   * result and update the interview-state streak / monotonic-ready flags.
   */
  private buildScoreResult(
    llmResult: LLMAmbiguityResult,
    evidenceHash: string,
    onProgress: ((text: string) => void) | undefined,
    _skipLlm: boolean,
    usedHeuristicFallback = false,
  ): AmbiguityScoreResult {
    const built = buildAmbiguityScoreResult({
      llmResult,
      evidenceHash,
      interviewState: this._interviewState,
      usedHeuristicFallback,
    });
    this._interviewState = built.nextInterviewState;
    for (const message of built.progressMessages) {
      emitUltraPlanProgress(onProgress, message);
    }
    return built.result;
  }

  /**
   * Soft seed auto-complete: full seed floors closed with stable hard-ready streak.
   * Design gate uses {@link interviewReadiness}.ready (verifiable UltraGoal only).
   */
  async canAutoComplete(): Promise<boolean> {
    await this.calculateAmbiguityScore();
    return (
      this._interviewState.ambiguityScore?.isReadyForSeed === true &&
      this._interviewState.completionCandidateStreak >= COMPLETION_STREAK_REQUIRED
    );
  }

  async interviewReadiness(options?: { rescore?: boolean }): Promise<UltraPlanReadiness> {
    const rescore = options?.rescore ?? true;
    const ambiguityScore = await this.resolveAmbiguityScore(rescore);
    const openGaps = this.openSeedGapsFromCache();
    const rawVerifiableGoal = this._lastAmbiguityResult?.verifiableGoal ?? false;
    // Hard design gate ≡ verifiable UltraGoal (monotonic-adjusted). Soft seed
    // gaps / floors / isReadyForSeed do not clear ready.
    const hardReady =
      this._interviewState.monotonicReadyLocked === true || rawVerifiableGoal;
    const stableReady =
      hardReady &&
      this._interviewState.completionCandidateStreak >= COMPLETION_STREAK_REQUIRED;
    return {
      ready: hardReady,
      stableReady,
      openGaps,
      ambiguityScore,
      verifiableGoal: hardReady,
      completionCandidateStreak: this._interviewState.completionCandidateStreak,
      floorFailures: ambiguityScore.floorFailures,
      usedHeuristicFallback: ambiguityScore.usedHeuristicFallback,
    };
  }

  async openSeedGaps(): Promise<readonly UltraPlanRequiredSection[]> {
    if (this._lastAmbiguityResult === null) {
      await this.calculateAmbiguityScore();
    }
    return this.openSeedGapsFromCache();
  }

  async readinessBlockerMessage(readiness?: UltraPlanReadiness): Promise<string> {
    const resolved = readiness ?? (await this.interviewReadiness({ rescore: true }));
    return formatInterviewReadinessGuide(resolved, {
      perspective: this._currentPerspective,
      interviewRoundCount: this._interviewState.rounds.length,
      consecutiveNonUserAnswers: this._interviewState.consecutiveNonUserAnswers,
    });
  }

  private async resolveAmbiguityScore(rescore: boolean): Promise<AmbiguityScoreResult> {
    if (!rescore && this.hasFreshAmbiguityCache()) {
      return this._interviewState.ambiguityScore!;
    }
    return this.calculateAmbiguityScore();
  }

  private hasFreshAmbiguityCache(): boolean {
    const evidenceHash = this._hash(this.interviewEvidenceText());
    return (
      this._interviewState.ambiguityScore !== null &&
      this._interviewState.lastScoredEvidenceHash === evidenceHash &&
      this._interviewState.cachedLlmResult !== undefined
    );
  }

  private openSeedGapsFromCache(): readonly UltraPlanRequiredSection[] {
    return openSeedGapsFromLlmResult(this._lastAmbiguityResult);
  }

  /**
   * Generate Seed Spec from interview results.
   * Prefers LLM extraction; on LLM unavailability / invalid JSON falls back to a
   * deterministic heuristic from interview evidence so interview→design is not
   * hard-blocked by a transient model failure.
   */
  async autoGenerateSeedSpecFromInterview(
    ontologyName: string,
    signal?: AbortSignal,
    onProgress?: (text: string) => void,
  ): Promise<SeedSpec> {
    emitUltraPlanProgress(onProgress, 'Extracting Seed Spec from interview evidence...');
    const allText = this.interviewEvidenceText();
    const llmResult = await extractSeedSpecWithLlm(this.agent, allText, signal);
    if (llmResult !== null) {
      emitUltraPlanProgress(onProgress, 'Seed Spec extracted.');
      return normalizeSeedSpec(
        llmResult,
        ontologyName,
        true,
        this._interviewState?.initialContext ?? '',
        this.buildSeedSpec.bind(this),
      );
    }

    // Heuristic fallback — mirrors ambiguity scoring's usedHeuristicFallback path.
    emitUltraPlanProgress(
      onProgress,
      'Seed Spec LLM unavailable; using heuristic Seed Spec from interview evidence...',
    );
    return buildHeuristicSeedSpecFromInterview(
      this._interviewState,
      ontologyName,
      this.buildSeedSpec.bind(this),
    );
  }

  private interviewEvidenceText(): string {
    return buildInterviewEvidenceText(this.agent, this._interviewState);
  }

  deserialize(data: Record<string, unknown>): void {
    if (data['seedSpec']) {
      const seed = data['seedSpec'] as SeedSpec;
      this._seedSpec = {
        ...seed,
        autoGenerated: seed.autoGenerated ?? false,
      };
    }
    if (data['driftMetrics']) this._driftMetrics = data['driftMetrics'] as DriftMetrics;
    if (data['stagnationHistory'])
      this._stagnationHistory = data['stagnationHistory'] as StagnationHistoryEntry[];
    if (data['evaluationPlan']) this._evaluationPlan = data['evaluationPlan'] as EvaluationPlan;
    if (data['lateralThinking']) this._lateralThinking = data['lateralThinking'] as LateralThinkingResult;
    if (data['interviewState']) this._interviewState = data['interviewState'] as InterviewState;
    if (data['currentPerspective']) {
      this._currentPerspective = data['currentPerspective'] as InterviewPerspective;
    }
  }
}
