/**
 * Deterministic Seed Spec fallback when LLM extraction is unavailable.
 */

import type { InterviewState, OntologyField, SeedSpec } from './ultra-plan-types';

export type BuildSeedSpecFn = (
  goal: string,
  constraints: string[],
  acceptanceCriteria: string[],
  ontologyName: string,
  ontologyFields: OntologyField[],
  autoGenerated?: boolean,
) => SeedSpec;

/**
 * Build a Seed Spec from interview rounds when structured LLM extraction fails.
 * Keeps NextPhase(interview→design) unblocked on model flakes.
 */
export function buildHeuristicSeedSpecFromInterview(
  interviewState: InterviewState,
  ontologyName: string,
  buildSeedSpec: BuildSeedSpecFn,
): SeedSpec {
  const goal =
    interviewState.initialContext.trim() ||
    'Complete the planned work with the agreed completion criterion.';

  const constraints: string[] = [];
  const acceptanceCriteria: string[] = [];
  const answerBlob: string[] = [];

  for (const round of interviewState.rounds) {
    const q = round.question.toLowerCase();
    const a = round.userResponse.trim();
    if (a.length === 0) continue;
    answerBlob.push(a);
    if (
      q.includes('완료') ||
      q.includes('completion') ||
      q.includes('criterion') ||
      q.includes('acceptance') ||
      q.includes('성공') ||
      q.includes('done when') ||
      q.includes('ultragoal')
    ) {
      acceptanceCriteria.push(a);
    } else if (
      q.includes('비범위') ||
      q.includes('non-goal') ||
      q.includes('constraint') ||
      q.includes('범위') ||
      q.includes('scope') ||
      q.includes('구조')
    ) {
      constraints.push(a);
    }
  }

  if (acceptanceCriteria.length === 0 && answerBlob.length > 0) {
    acceptanceCriteria.push(
      `Interview decisions are implemented and verified: ${answerBlob.join(' | ').slice(0, 240)}`,
    );
  }
  if (acceptanceCriteria.length === 0) {
    acceptanceCriteria.push(
      'The stated goal is met and verification commands/tests for the work pass.',
    );
  }
  if (constraints.length === 0) {
    constraints.push('Stay within the agreed scope; do not expand into deferred non-goals.');
  }

  return buildSeedSpec(
    goal,
    constraints,
    acceptanceCriteria,
    ontologyName.trim().length > 0 ? `${ontologyName}-heuristic` : 'HeuristicPlan',
    [
      {
        name: 'heuristic_note',
        type: 'string',
        description: 'Heuristic Seed Spec (LLM extraction unavailable)',
        required: false,
      },
    ],
    true,
  );
}
