/**
 * UltraPlanMode - Ouroboros-inspired advanced planning system.
 *
 * Integrates Seed Spec, AC Tree, Ontology, Drift Detection,
 * Stagnation Detection, and Lateral Thinking into the existing PlanMode.
 *
 * This is NOT a copy of Ouroboros; it is a natural evolution of
 * SuperLiora's plan mode, borrowing the most powerful concepts and
 * adapting them to the existing architecture.
 */

import { createUserMessage, extractText } from '@superliora/kosong';

import type { Agent } from '..';
import { isRealUserPromptOrigin } from '../context';
import { formatInterviewReadinessGuide } from './ultra-plan-interview-guide';

export {
  formatInterviewReadinessGuide,
  pickNextInterviewFocus,
  type InterviewReadinessGuideOptions,
} from './ultra-plan-interview-guide';

import type { UltraPlanRequiredSection } from './ultra-plan-section-guidance';

export {
  MAX_INTERVIEW_ROUNDS,
  ULTRA_PLAN_REQUIRED_SECTIONS,
  ULTRA_PLAN_SECTION_GUIDANCE,
  type UltraPlanRequiredSection,
} from './ultra-plan-section-guidance';

import {
  computeAmbiguityScoreHeuristic as computeAmbiguityScoreHeuristicPure,
  type LLMAmbiguityResult,
} from './ultra-plan-ambiguity-heuristic';

export { AMBIGUITY_THRESHOLD } from './ultra-plan-ambiguity-heuristic';
import { extractJsonFromText, extractTextFromLLMResponse } from './ultra-plan-llm-json';
import { normalizeSeedSpec } from './ultra-plan-seed-normalize';
import {
  AMBIGUITY_LLM_SYSTEM_PROMPT,
  buildDriftEvaluationUserPrompt,
  buildSeedSpecExtractionUserPrompt,
  DRIFT_LLM_SYSTEM_PROMPT,
  parseAmbiguityLlmResult,
  parseDriftLlmResult,
  SEED_SPEC_LLM_SYSTEM_PROMPT,
} from './ultra-plan-llm-scoring';
import {
  detectAllStagnation,
  hashText,
  type StagnationDetection,
} from './ultra-plan-stagnation';

export interface SeedSpec {
  readonly goal: string;
  readonly taskType: 'code' | 'research' | 'analysis';
  readonly constraints: readonly string[];
  readonly acceptanceCriteria: readonly AcceptanceCriterion[];
  readonly ontology: OntologySchema;
  readonly evaluationPrinciples: readonly EvaluationPrinciple[];
  readonly exitConditions: readonly ExitCondition[];
  readonly ambiguityScore: number;
  readonly autoGenerated: boolean;
  readonly createdAt: string;
}

export interface AcceptanceCriterion {
  readonly id: string;
  readonly description: string;
  readonly status: 'pending' | 'in_progress' | 'passed' | 'failed';
  readonly children?: readonly AcceptanceCriterion[];
}

export interface OntologySchema {
  readonly name: string;
  readonly description: string;
  readonly fields: readonly OntologyField[];
}

export interface OntologyField {
  readonly name: string;
  readonly type: string;
  readonly description: string;
  readonly required: boolean;
}

export interface EvaluationPrinciple {
  readonly name: string;
  readonly description: string;
  readonly weight: number;
}

export interface ExitCondition {
  readonly name: string;
  readonly description: string;
  readonly criteria: string;
}

export interface DriftMetrics {
  readonly goalDrift: number;
  readonly constraintDrift: number;
  readonly ontologyDrift: number;
}

export const ULTRA_PLAN_DRIFT_THRESHOLD = 0.4;

/** Tolerant drift threshold for auto-generated Seed Specs (extracted from
 *  interview answers). Stricter than full exemption but more lenient than
 *  manually-written Seeds, since interview-derived Seeds have inherent
 *  wording variance. */
export const ULTRA_PLAN_DRIFT_THRESHOLD_AUTO = 0.6;

export function combinedDrift(metrics: DriftMetrics): number {
  return metrics.goalDrift * 0.5 + metrics.constraintDrift * 0.3 + metrics.ontologyDrift * 0.2;
}

export function isDriftAcceptable(metrics: DriftMetrics): boolean {
  return combinedDrift(metrics) <= ULTRA_PLAN_DRIFT_THRESHOLD;
}

export type InterviewAnswerOrigin = 'user' | 'code' | 'research';

export type InterviewPerspective =
  | 'researcher'
  | 'simplifier'
  | 'architect'
  | 'breadth-keeper'
  | 'seed-closer';

export type UltraPlanPhase = 'research' | 'interview' | 'design' | 'review' | 'write' | 'exit';

export type AmbiguityMilestone = 'initial' | 'progress' | 'refined' | 'ready';

export interface InterviewRound {
  readonly roundNumber: number;
  readonly question: string;
  readonly userResponse: string;
  readonly timestamp: number;
  /** Where the answer came from. 'user' = user decided via AskUserQuestion;
   *  'code' = agent answered from codebase evidence; 'research' = external research. */
  readonly origin: InterviewAnswerOrigin;
}

export interface AmbiguityScoreBreakdown {
  readonly name: string;
  readonly clarityScore: number;
  readonly weight: number;
  readonly justification: string;
}

export interface AmbiguityScoreResult {
  readonly overallScore: number;
  readonly breakdown: readonly AmbiguityScoreBreakdown[];
  readonly isReadyForSeed: boolean;
  readonly milestone: AmbiguityMilestone;
  readonly floorFailures: readonly string[];
  /** True when the score was derived from the deterministic heuristic because
   *  the LLM scoring engine was unavailable or returned invalid JSON. */
  readonly usedHeuristicFallback?: boolean;
}

export interface InterviewState {
  readonly rounds: readonly InterviewRound[];
  readonly initialContext: string;
  readonly ambiguityScore: AmbiguityScoreResult | null;
  readonly completionCandidateStreak: number;
  readonly lastReadyEvidenceHash?: string;
  readonly lastReadyRoundCount?: number;
  /** Evidence hash of the last scored round — prevents re-calling the LLM
   *  when the evidence has not changed (eliminates score oscillation). */
  readonly lastScoredEvidenceHash?: string;
  /** Cached LLM ambiguity result for the current evidence hash. */
  readonly cachedLlmResult?: LLMAmbiguityResult;
  /** Once true, the interview stays "ready" until a new round is added —
   *  LLM non-determinism cannot un-ready an already-passed gate. */
  readonly monotonicReadyLocked?: boolean;
  /** Consecutive rounds where origin was 'code' or 'research' (not 'user').
   *  Reset to 0 on each 'user' answer. Drives the Dialectic Rhythm Guard. */
  readonly consecutiveNonUserAnswers: number;
  /** Wall-clock timestamp when the interview phase started. Used to filter
   *  pre-interview user prompts out of the ambiguity evidence. */
  readonly startedAtTimestamp: number;
}

const COMPLETION_STREAK_REQUIRED = 1;

/** Soft cap on interview rounds — surfaces a warning in the readiness guide but
 *  does not bypass the Design gate. */

export interface UltraPlanReadiness {
  readonly ready: boolean;
  readonly stableReady: boolean;
  readonly openGaps: readonly UltraPlanRequiredSection[];
  readonly ambiguityScore: AmbiguityScoreResult;
  readonly verifiableGoal: boolean;
  readonly completionCandidateStreak: number;
  readonly floorFailures: readonly string[];
  /** True when the ambiguity score was derived from the heuristic fallback. */
  readonly usedHeuristicFallback?: boolean;
}

export type { StagnationDetection, StagnationPatternType } from './ultra-plan-stagnation';
import { buildAmbiguityScoreResult, openSeedGapsFromLlmResult } from './ultra-plan-score-result';
import { buildSeedSpec as buildSeedSpecPure } from './ultra-plan-seed-build';
import { getInterviewPerspectiveDescription } from './ultra-plan-perspective';
import { buildLateralThinkingResult } from './ultra-plan-lateral';
import { buildDefaultEvaluationPlan } from './ultra-plan-evaluation';
import {
  appendInterviewRoundState,
  formatInterviewAnswerText,
  formatInterviewQuestionText,
} from './ultra-plan-interview-rounds';

export type ThinkingPersona =
  | 'hacker'
  | 'researcher'
  | 'simplifier'
  | 'architect'
  | 'contrarian';

export interface LateralThinkingResult {
  readonly persona: ThinkingPersona;
  readonly prompt: string;
  readonly approachSummary: string;
  readonly questions: readonly string[];
}

export interface EvaluationPlan {
  readonly stage1Mechanical: boolean;
  readonly stage2Semantic: boolean;
  readonly stage3Consensus: boolean;
  readonly mechanicalChecks: readonly string[];
  readonly semanticCriteria: readonly string[];
}

export interface UltraPlanData {
  readonly seedSpec: SeedSpec | null;
  readonly driftMetrics: DriftMetrics | null;
  readonly stagnationPatterns: readonly StagnationDetection[];
  readonly lateralThinking: LateralThinkingResult | null;
  readonly evaluationPlan: EvaluationPlan | null;
}

interface StagnationHistoryEntry {
  readonly timestamp: number;
  readonly phaseOutputs: readonly string[];
  readonly errorSignatures: readonly string[];
  readonly driftScores: readonly number[];
  readonly detections: readonly StagnationDetection[];
}

export class UltraPlanModeEngine {
  private readonly agent: Agent;
  private _seedSpec: SeedSpec | null = null;
  private _driftMetrics: DriftMetrics | null = null;
  private _stagnationHistory: StagnationHistoryEntry[] = [];
  private _evaluationPlan: EvaluationPlan | null = null;
  private _lateralThinking: LateralThinkingResult | null = null;
  private _lastAmbiguityResult: LLMAmbiguityResult | null = null;

  constructor(agent: Agent) {
    this.agent = agent;
  }

  setSeedSpec(seed: SeedSpec): void {
    this._seedSpec = seed;
  }

  reopenInterviewForSeedRefinement(metrics: DriftMetrics): void {
    this._seedSpec = null;
    this._driftMetrics = metrics;
    this._lastAmbiguityResult = null;
    this._currentPerspective = 'researcher';
    this._interviewState = {
      ...this._interviewState,
      ambiguityScore: null,
      completionCandidateStreak: 0,
      lastReadyEvidenceHash: undefined,
      lastReadyRoundCount: -1,
      lastScoredEvidenceHash: undefined,
      cachedLlmResult: undefined,
      monotonicReadyLocked: false,
    };
  }

  get seedSpec(): SeedSpec | null {
    return this._seedSpec;
  }

  buildSeedSpec(
    goal: string,
    constraints: string[],
    acceptanceCriteria: string[],
    ontologyName: string,
    ontologyFields: OntologyField[],
    autoGenerated = false,
  ): SeedSpec {
    return buildSeedSpecPure(
      goal,
      constraints,
      acceptanceCriteria,
      ontologyName,
      ontologyFields,
      autoGenerated,
    );
  }

  generateSeedSpecFromInterview(
    goal: string,
    constraints: string[],
    acceptanceCriteria: string[],
    ontologyName: string,
    ontologyFields: OntologyField[],
    autoGenerated = false,
  ): SeedSpec {
    return this.buildSeedSpec(
      goal,
      constraints,
      acceptanceCriteria,
      ontologyName,
      ontologyFields,
      autoGenerated,
    );
  }

  async calculateDrift(currentOutput: string, constraintViolations: string[]): Promise<DriftMetrics> {
    if (!this._seedSpec) {
      return { goalDrift: 0, constraintDrift: 0, ontologyDrift: 0 };
    }
    const llmMetrics = await this._calculateDriftWithLLM(currentOutput, constraintViolations);
    if (llmMetrics !== null) {
      this._driftMetrics = llmMetrics;
      return llmMetrics;
    }
    throw new Error(
      'LLM-based drift evaluation failed: the LLM is unavailable or returned invalid JSON.',
    );
  }

  detectStagnation(
    phaseOutputs: string[],
    errorSignatures: string[],
    driftScores: number[],
  ): StagnationDetection[] {
    const results = detectAllStagnation(phaseOutputs, errorSignatures, driftScores);

    this._stagnationHistory.push({
      timestamp: Date.now(),
      phaseOutputs: [...phaseOutputs],
      errorSignatures: [...errorSignatures],
      driftScores: [...driftScores],
      detections: [...results],
    });

    return results;
  }

  private _hash(text: string): string {
    return hashText(text);
  }

  generateLateralThinking(
    persona: ThinkingPersona,
    problemContext: string,
    currentApproach: string,
  ): LateralThinkingResult {
    const result = buildLateralThinkingResult(persona, problemContext, currentApproach);
    this._lateralThinking = result;
    return result;
  }

  setEvaluationPlan(plan: EvaluationPlan): void {
    this._evaluationPlan = plan;
  }

  get evaluationPlan(): EvaluationPlan | null {
    return this._evaluationPlan;
  }

  generateDefaultEvaluationPlan(): EvaluationPlan {
    return buildDefaultEvaluationPlan();
  }

  serialize(): Record<string, unknown> {
    return {
      seedSpec: this._seedSpec,
      driftMetrics: this._driftMetrics,
      stagnationHistory: this._stagnationHistory,
      evaluationPlan: this._evaluationPlan,
      lateralThinking: this._lateralThinking,
      interviewState: this._interviewState,
      currentPerspective: this._currentPerspective,
    };
  }

  // ---------------------------------------------------------------------------
  // Interview & Ambiguity Scoring
  // ---------------------------------------------------------------------------

  private _currentPerspective: InterviewPerspective = 'researcher';
  private readonly _perspectives: InterviewPerspective[] = [
    'researcher',
    'simplifier',
    'architect',
    'breadth-keeper',
    'seed-closer',
  ];

  private _interviewState: InterviewState = {
    rounds: [],
    initialContext: '',
    ambiguityScore: null,
    completionCandidateStreak: 0,
    lastReadyEvidenceHash: undefined,
    lastReadyRoundCount: -1,
    lastScoredEvidenceHash: undefined,
    cachedLlmResult: undefined,
    monotonicReadyLocked: false,
    consecutiveNonUserAnswers: 0,
    startedAtTimestamp: 0,
  };

  get interviewState(): InterviewState {
    return this._interviewState;
  }

  get currentPerspective(): InterviewPerspective {
    return this._currentPerspective;
  }

  advancePerspective(): void {
    const idx = this._perspectives.indexOf(this._currentPerspective);
    this._currentPerspective = this._perspectives[(idx + 1) % this._perspectives.length] ?? 'researcher';
  }

  getPerspectiveDescription(): string {
    return getInterviewPerspectiveDescription(this._currentPerspective);
  }

  startInterview(initialContext: string): void {
    this._currentPerspective = 'researcher';
    this._lastAmbiguityResult = null;
    this._interviewState = {
      rounds: [],
      initialContext,
      ambiguityScore: null,
      completionCandidateStreak: 0,
      lastReadyEvidenceHash: undefined,
      lastScoredEvidenceHash: undefined,
      cachedLlmResult: undefined,
      monotonicReadyLocked: false,
      consecutiveNonUserAnswers: 0,
      startedAtTimestamp: Date.now(),
    };
  }

  addInterviewRound(
    question: string,
    userResponse: string,
    origin: InterviewAnswerOrigin = 'user',
  ): void {
    this.advancePerspective();
    this._interviewState = appendInterviewRoundState(
      this._interviewState,
      question,
      userResponse,
      origin,
    );
  }

  recordInterviewAnswers(
    questions: ReadonlyArray<{ readonly question: string; readonly header?: string }>,
    answers: Record<string, string | true>,
  ): void {
    this.addInterviewRound(
      formatInterviewQuestionText(questions),
      formatInterviewAnswerText(answers),
    );
  }

  /**
   * Calculate ambiguity score from interview state using the LLM-based
   * Ouroboros-style clarity scorer. Regex heuristics have been removed; all
   * ambiguity dimensions are derived from the LLM's structured JSON response.
   *
   * Stability guarantees (prevents infinite interview loops):
   * - **Evidence-keyed cache**: if the evidence text has not changed since the
   *   last LLM call, the cached result is reused — no new LLM round, so the
   *   score cannot oscillate between calls.
   * - **Monotonic ready**: once `isReadyForSeed` is true for a given evidence
   *   hash, it stays true until a new interview round changes the evidence.
   *   LLM non-determinism cannot un-ready an already-passed gate.
   * - **Max rounds**: after MAX_INTERVIEW_ROUNDS the readiness guide warns
   *   that the soft cap was hit; the Design gate still requires real closure.
   */
  async calculateAmbiguityScore(
    signal?: AbortSignal,
    onProgress?: (text: string) => void,
  ): Promise<AmbiguityScoreResult> {
    const evidence = this.interviewEvidenceText();
    const evidenceHash = this._hash(evidence);

    // ── Evidence-keyed cache hit: reuse the LLM result without a new call.
    if (
      this._interviewState.lastScoredEvidenceHash === evidenceHash &&
      this._interviewState.cachedLlmResult !== undefined
    ) {
      return this.buildScoreResult(
        this._interviewState.cachedLlmResult,
        evidenceHash,
        onProgress,
        /* skipLlm */ true,
      );
    }

    this.emitProgress(onProgress, 'Analyzing your answers...');
    this.emitProgress(
      onProgress,
      'Scoring ambiguity across goal, constraints, and success criteria...',
    );

    let llmResult = await this._calculateAmbiguityWithLLM(evidence, signal);
    if (llmResult === null) {
      // Automatic one-time retry before falling back to the deterministic
      // heuristic. This prevents a single transient LLM failure from blocking
      // the interview.
      llmResult = await this._calculateAmbiguityWithLLM(evidence, signal);
    }
    if (llmResult === null) {
      // LLM is unavailable or returning invalid JSON. Use a deterministic
      // heuristic so the interview can continue safely without throwing.
      this.emitProgress(
        onProgress,
        'Scoring engine unavailable — falling back to deterministic heuristic.',
      );
      const heuristicResult = computeAmbiguityScoreHeuristicPure(this._interviewState);
      this._lastAmbiguityResult = heuristicResult;
      this._interviewState = {
        ...this._interviewState,
        lastScoredEvidenceHash: evidenceHash,
        // cachedLlmResult is intentionally not set so the LLM is retried on
        // the next scoring attempt when it may be available again.
      };
      return this.buildScoreResult(
        heuristicResult,
        evidenceHash,
        onProgress,
        false,
        /* usedHeuristicFallback */ true,
      );
    }
    this._lastAmbiguityResult = llmResult;

    // Cache the LLM result for this evidence hash so subsequent calls
    // (e.g. interviewReadiness → calculateAmbiguityScore) don't re-call the
    // LLM and produce a different score.
    this._interviewState = {
      ...this._interviewState,
      lastScoredEvidenceHash: evidenceHash,
      cachedLlmResult: llmResult,
    };

    return this.buildScoreResult(llmResult, evidenceHash, onProgress, false);
  }

  /**
   * Build the {@link AmbiguityScoreResult} from a (possibly cached) LLM
   * result and update the interview-state streak / monotonic-ready flags.
   */
  private buildScoreResult(
    llmResult: LLMAmbiguityResult,
    evidenceHash: string,
    onProgress: ((text: string) => void) | undefined,
    _skipLlm: boolean,
    usedHeuristicFallback = false,
  ): AmbiguityScoreResult {
    const built = buildAmbiguityScoreResult({
      llmResult,
      evidenceHash,
      interviewState: this._interviewState,
      usedHeuristicFallback,
    });
    this._interviewState = built.nextInterviewState;
    for (const message of built.progressMessages) {
      this.emitProgress(onProgress, message);
    }
    return built.result;
  }

  /**
   * Check if interview can auto-complete (ready score with stable streak).
   */
  async canAutoComplete(): Promise<boolean> {
    await this.calculateAmbiguityScore();
    return (
      this._interviewState.ambiguityScore?.isReadyForSeed === true &&
      this._interviewState.completionCandidateStreak >= COMPLETION_STREAK_REQUIRED
    );
  }

  async interviewReadiness(options?: { rescore?: boolean }): Promise<UltraPlanReadiness> {
    const rescore = options?.rescore ?? true;
    const ambiguityScore = await this.resolveAmbiguityScore(rescore);
    const openGaps = this.openSeedGapsFromCache();
    const verifiableGoal = this._lastAmbiguityResult?.verifiableGoal ?? false;
    const stableReady =
      ambiguityScore.isReadyForSeed &&
      this._interviewState.completionCandidateStreak >= COMPLETION_STREAK_REQUIRED;
    return {
      ready: ambiguityScore.isReadyForSeed && openGaps.length === 0 && verifiableGoal,
      stableReady,
      openGaps,
      ambiguityScore,
      verifiableGoal,
      completionCandidateStreak: this._interviewState.completionCandidateStreak,
      floorFailures: ambiguityScore.floorFailures,
      usedHeuristicFallback: ambiguityScore.usedHeuristicFallback,
    };
  }

  async openSeedGaps(): Promise<readonly UltraPlanRequiredSection[]> {
    if (this._lastAmbiguityResult === null) {
      await this.calculateAmbiguityScore();
    }
    return this.openSeedGapsFromCache();
  }

  async readinessBlockerMessage(readiness?: UltraPlanReadiness): Promise<string> {
    const resolved = readiness ?? (await this.interviewReadiness({ rescore: true }));
    return formatInterviewReadinessGuide(resolved, {
      perspective: this._currentPerspective,
      interviewRoundCount: this._interviewState.rounds.length,
      consecutiveNonUserAnswers: this._interviewState.consecutiveNonUserAnswers,
    });
  }

  private async resolveAmbiguityScore(rescore: boolean): Promise<AmbiguityScoreResult> {
    if (!rescore && this.hasFreshAmbiguityCache()) {
      return this._interviewState.ambiguityScore!;
    }
    return this.calculateAmbiguityScore();
  }

  private hasFreshAmbiguityCache(): boolean {
    const evidenceHash = this._hash(this.interviewEvidenceText());
    return (
      this._interviewState.ambiguityScore !== null &&
      this._interviewState.lastScoredEvidenceHash === evidenceHash &&
      this._interviewState.cachedLlmResult !== undefined
    );
  }

  private openSeedGapsFromCache(): readonly UltraPlanRequiredSection[] {
    return openSeedGapsFromLlmResult(this._lastAmbiguityResult);
  }

  /**
   * Generate Seed Spec from interview results.
   * Extracts Goal, Constraints, AC, and Ontology from Q&A.
   */
  async autoGenerateSeedSpecFromInterview(
    ontologyName: string,
    signal?: AbortSignal,
    onProgress?: (text: string) => void,
  ): Promise<SeedSpec> {
    this.emitProgress(onProgress, 'Extracting Seed Spec from interview evidence...');
    const allText = this.interviewEvidenceText();
    const llmResult = await this._extractSeedSpecFromLLM(allText, ontologyName, signal);
    if (llmResult !== null) {
      this.emitProgress(onProgress, 'Seed Spec extracted.');
      return normalizeSeedSpec(
        llmResult,
        ontologyName,
        true,
        this._interviewState.initialContext,
        this.buildSeedSpec.bind(this),
      );
    }
    throw new Error(
      'LLM-based Seed Spec extraction failed: the LLM is unavailable or returned invalid JSON.',
    );
  }

  private emitProgress(onProgress: ((text: string) => void) | undefined, text: string): void {
    if (onProgress === undefined) return;
    try {
      onProgress(text);
    } catch {
      // Progress is best-effort; do not let a listener failure break the engine.
    }
  }

  private interviewEvidenceText(): string {
    return [
      this._interviewState.initialContext,
      ...this.recentUserPromptTexts(),
      ...this._interviewState.rounds.map((r) => r.userResponse),
    ].join('\n');
  }

  private recentUserPromptTexts(): string[] {
    const startedAt = this._interviewState.startedAtTimestamp ?? 0;
    return (this.agent.context?.history ?? [])
      .filter(
        (message) =>
          message.role === 'user' &&
          isRealUserPromptOrigin(message.origin) &&
          ((message as { timestamp?: number }).timestamp ?? 0) >= startedAt,
      )
      .slice(-3)
      .map((message) => extractText(message, '\n').trim())
      .filter((text) => text.length > 0);
  }

  // ---------------------------------------------------------------------------
  // LLM-backed Seed Spec extraction, ambiguity scoring, and drift evaluation
  // ---------------------------------------------------------------------------

  private get _llmAvailable(): boolean {
    return (
      typeof this.agent.generate === 'function' &&
      this.agent.config?.provider !== undefined
    );
  }

  private async _llmJsonRequest<T>(
    system: string,
    user: string,
    signal?: AbortSignal,
  ): Promise<T | null> {
    if (!this._llmAvailable) return null;
    try {
      const response = await this.agent.generate(
        this.agent.config.provider,
        system,
        [],
        [createUserMessage(user)],
        undefined,
        { signal },
      );
      const text = extractTextFromLLMResponse(response);
      const json = extractJsonFromText(text);
      if (json === null) return null;
      return JSON.parse(json) as T;
    } catch {
      return null;
    }
  }

  private async _calculateAmbiguityWithLLM(
    evidence: string,
    signal?: AbortSignal,
  ): Promise<LLMAmbiguityResult | null> {
    const raw = await this._llmJsonRequest<{
      goal_clarity_score?: number;
      goal_clarity_justification?: string;
      constraint_clarity_score?: number;
      constraint_clarity_justification?: string;
      success_criteria_clarity_score?: number;
      success_criteria_clarity_justification?: string;
      present_sections?: unknown;
      verifiable_goal?: boolean;
      specificity_score?: number;
    }>(AMBIGUITY_LLM_SYSTEM_PROMPT, evidence, signal);
    return parseAmbiguityLlmResult(raw);
  }

  private async _extractSeedSpecFromLLM(
    evidence: string,
    _ontologyName: string,
    signal?: AbortSignal,
  ): Promise<unknown> {
    return this._llmJsonRequest<unknown>(
      SEED_SPEC_LLM_SYSTEM_PROMPT,
      buildSeedSpecExtractionUserPrompt(evidence),
      signal,
    );
  }

  private async _calculateDriftWithLLM(
    currentOutput: string,
    constraintViolations: string[],
  ): Promise<DriftMetrics | null> {
    if (!this._seedSpec) return null;
    const raw = await this._llmJsonRequest<Partial<DriftMetrics>>(
      DRIFT_LLM_SYSTEM_PROMPT,
      buildDriftEvaluationUserPrompt(this._seedSpec, currentOutput, constraintViolations),
    );
    return parseDriftLlmResult(raw);
  }

  deserialize(data: Record<string, unknown>): void {
    if (data['seedSpec']) {
      const seed = data['seedSpec'] as SeedSpec;
      this._seedSpec = {
        ...seed,
        autoGenerated: seed.autoGenerated ?? false,
      };
    }
    if (data['driftMetrics']) this._driftMetrics = data['driftMetrics'] as DriftMetrics;
    if (data['stagnationHistory'])
      this._stagnationHistory = data['stagnationHistory'] as StagnationHistoryEntry[];
    if (data['evaluationPlan']) this._evaluationPlan = data['evaluationPlan'] as EvaluationPlan;
    if (data['lateralThinking']) this._lateralThinking = data['lateralThinking'] as LateralThinkingResult;
    if (data['interviewState']) this._interviewState = data['interviewState'] as InterviewState;
    if (data['currentPerspective']) {
      this._currentPerspective = data['currentPerspective'] as InterviewPerspective;
    }
  }
}
