/**
 * UltraPlanMode - Ouroboros-inspired advanced planning system.
 *
 * Integrates Seed Spec, AC Tree, Ontology, Drift Detection,
 * Stagnation Detection, and Lateral Thinking into the existing PlanMode.
 *
 * This is NOT a copy of Ouroboros; it is a natural evolution of
 * SuperLiora's plan mode, borrowing the most powerful concepts and
 * adapting them to the existing architecture.
 */

import { createUserMessage, extractText } from '@superliora/kosong';

import type { Agent } from '..';
import { isRealUserPromptOrigin } from '../context';

export interface SeedSpec {
  readonly goal: string;
  readonly taskType: 'code' | 'research' | 'analysis';
  readonly constraints: readonly string[];
  readonly acceptanceCriteria: readonly AcceptanceCriterion[];
  readonly ontology: OntologySchema;
  readonly evaluationPrinciples: readonly EvaluationPrinciple[];
  readonly exitConditions: readonly ExitCondition[];
  readonly ambiguityScore: number;
  readonly autoGenerated: boolean;
  readonly createdAt: string;
}

export interface AcceptanceCriterion {
  readonly id: string;
  readonly description: string;
  readonly status: 'pending' | 'in_progress' | 'passed' | 'failed';
  readonly children?: readonly AcceptanceCriterion[];
}

export interface OntologySchema {
  readonly name: string;
  readonly description: string;
  readonly fields: readonly OntologyField[];
}

export interface OntologyField {
  readonly name: string;
  readonly type: string;
  readonly description: string;
  readonly required: boolean;
}

export interface EvaluationPrinciple {
  readonly name: string;
  readonly description: string;
  readonly weight: number;
}

export interface ExitCondition {
  readonly name: string;
  readonly description: string;
  readonly criteria: string;
}

export interface DriftMetrics {
  readonly goalDrift: number;
  readonly constraintDrift: number;
  readonly ontologyDrift: number;
}

export const ULTRA_PLAN_DRIFT_THRESHOLD = 0.4;

export function combinedDrift(metrics: DriftMetrics): number {
  return metrics.goalDrift * 0.5 + metrics.constraintDrift * 0.3 + metrics.ontologyDrift * 0.2;
}

export function isDriftAcceptable(metrics: DriftMetrics): boolean {
  return combinedDrift(metrics) <= ULTRA_PLAN_DRIFT_THRESHOLD;
}

export type InterviewPerspective =
  | 'researcher'
  | 'simplifier'
  | 'architect'
  | 'breadth-keeper'
  | 'seed-closer';

export type UltraPlanPhase = 'research' | 'interview' | 'design' | 'review' | 'write' | 'exit';

export type AmbiguityMilestone = 'initial' | 'progress' | 'refined' | 'ready';

export interface InterviewRound {
  readonly roundNumber: number;
  readonly question: string;
  readonly userResponse: string;
  readonly timestamp: number;
}

export interface AmbiguityScoreBreakdown {
  readonly name: string;
  readonly clarityScore: number;
  readonly weight: number;
  readonly justification: string;
}

export interface AmbiguityScoreResult {
  readonly overallScore: number;
  readonly breakdown: readonly AmbiguityScoreBreakdown[];
  readonly isReadyForSeed: boolean;
  readonly milestone: AmbiguityMilestone;
  readonly floorFailures: readonly string[];
}

export interface InterviewState {
  readonly rounds: readonly InterviewRound[];
  readonly initialContext: string;
  readonly ambiguityScore: AmbiguityScoreResult | null;
  readonly completionCandidateStreak: number;
  readonly lastReadyEvidenceHash?: string;
  readonly lastReadyRoundCount?: number;
  /** Evidence hash of the last scored round — prevents re-calling the LLM
   *  when the evidence has not changed (eliminates score oscillation). */
  readonly lastScoredEvidenceHash?: string;
  /** Cached LLM ambiguity result for the current evidence hash. */
  readonly cachedLlmResult?: LLMAmbiguityResult;
  /** Once true, the interview stays "ready" until a new round is added —
   *  LLM non-determinism cannot un-ready an already-passed gate. */
  readonly monotonicReadyLocked?: boolean;
}

export const ULTRA_PLAN_REQUIRED_SECTIONS = [
  'goal',
  'actors',
  'inputs',
  'outputs',
  'constraints',
  'non_goals',
  'acceptance_criteria',
  'verification_plan',
  'failure_modes',
  'runtime_context',
] as const;

export type UltraPlanRequiredSection = typeof ULTRA_PLAN_REQUIRED_SECTIONS[number];

export const ULTRA_PLAN_SECTION_GUIDANCE: Record<
  UltraPlanRequiredSection,
  { readonly label: string; readonly askHint: string }
> = {
  goal: {
    label: 'Goal / UltraGoal',
    askHint: 'State the single deliverable or outcome in one concrete sentence.',
  },
  actors: {
    label: 'Actors',
    askHint: 'Who is involved (user, agent, reviewer, end-user)?',
  },
  inputs: {
    label: 'Inputs',
    askHint: 'What artifacts, files, APIs, or context does the work start from?',
  },
  outputs: {
    label: 'Outputs',
    askHint: 'What concrete deliverables will exist when done (files, docs, UI, decisions)?',
  },
  constraints: {
    label: 'Constraints',
    askHint: 'What limits apply (time, tech stack, budget, brand, must-not-change rules)?',
  },
  non_goals: {
    label: 'Non-goals',
    askHint: 'What is explicitly out of scope?',
  },
  acceptance_criteria: {
    label: 'Acceptance Criteria',
    askHint: 'What checks must pass for the work to be accepted?',
  },
  verification_plan: {
    label: 'Verification Plan',
    askHint: 'How will you verify success (tests, review, demo, metrics)?',
  },
  failure_modes: {
    label: 'Failure Modes',
    askHint: 'What could go wrong or what regressions must be avoided?',
  },
  runtime_context: {
    label: 'Runtime Context',
    askHint: 'Where does this run (repo, stack, environment, audience)?',
  },
};

const AMBIGUITY_THRESHOLD = 0.2;
const COMPLETION_STREAK_REQUIRED = 1;
const GOAL_CLARITY_FLOOR = 0.75;
const CONSTRAINT_CLARITY_FLOOR = 0.65;
const SUCCESS_CRITERIA_CLARITY_FLOOR = 0.70;

/** Maximum interview rounds before the engine force-advances to Design.
 *  Prevents infinite interview loops caused by LLM score oscillation. */
const MAX_INTERVIEW_ROUNDS = 8;

export interface UltraPlanReadiness {
  readonly ready: boolean;
  readonly stableReady: boolean;
  readonly openGaps: readonly UltraPlanRequiredSection[];
  readonly ambiguityScore: AmbiguityScoreResult;
  readonly verifiableGoal: boolean;
  readonly completionCandidateStreak: number;
  readonly floorFailures: readonly string[];
}

export type StagnationPatternType =
  | 'spinning'
  | 'oscillation'
  | 'no_drift'
  | 'diminishing_returns';

export interface StagnationDetection {
  readonly pattern: StagnationPatternType;
  readonly detected: boolean;
  readonly confidence: number;
  readonly evidence: Record<string, unknown>;
}

export type ThinkingPersona =
  | 'hacker'
  | 'researcher'
  | 'simplifier'
  | 'architect'
  | 'contrarian';

export interface LateralThinkingResult {
  readonly persona: ThinkingPersona;
  readonly prompt: string;
  readonly approachSummary: string;
  readonly questions: readonly string[];
}

export interface EvaluationPlan {
  readonly stage1Mechanical: boolean;
  readonly stage2Semantic: boolean;
  readonly stage3Consensus: boolean;
  readonly mechanicalChecks: readonly string[];
  readonly semanticCriteria: readonly string[];
}

export interface UltraPlanData {
  readonly seedSpec: SeedSpec | null;
  readonly driftMetrics: DriftMetrics | null;
  readonly stagnationPatterns: readonly StagnationDetection[];
  readonly lateralThinking: LateralThinkingResult | null;
  readonly evaluationPlan: EvaluationPlan | null;
}

interface StagnationHistoryEntry {
  readonly timestamp: number;
  readonly phaseOutputs: readonly string[];
  readonly errorSignatures: readonly string[];
  readonly driftScores: readonly number[];
  readonly detections: readonly StagnationDetection[];
}

interface LLMAmbiguityResult {
  readonly goalClarity: number;
  readonly constraintClarity: number;
  readonly successCriteriaClarity: number;
  readonly presentSections: readonly string[];
  readonly verifiableGoal: boolean;
  readonly specificityScore: number;
  readonly justifications: {
    readonly goal: string;
    readonly constraints: string;
    readonly successCriteria: string;
  };
}

export class UltraPlanModeEngine {
  private readonly agent: Agent;
  private _seedSpec: SeedSpec | null = null;
  private _driftMetrics: DriftMetrics | null = null;
  private _stagnationHistory: StagnationHistoryEntry[] = [];
  private _evaluationPlan: EvaluationPlan | null = null;
  private _lateralThinking: LateralThinkingResult | null = null;
  private _lastAmbiguityResult: LLMAmbiguityResult | null = null;

  constructor(agent: Agent) {
    this.agent = agent;
  }

  setSeedSpec(seed: SeedSpec): void {
    this._seedSpec = seed;
  }

  reopenInterviewForSeedRefinement(metrics: DriftMetrics): void {
    this._seedSpec = null;
    this._driftMetrics = metrics;
    this._lastAmbiguityResult = null;
    this._interviewState = {
      ...this._interviewState,
      ambiguityScore: null,
      completionCandidateStreak: 0,
      lastReadyEvidenceHash: undefined,
      lastReadyRoundCount: -1,
      lastScoredEvidenceHash: undefined,
      cachedLlmResult: undefined,
      monotonicReadyLocked: false,
    };
  }

  get seedSpec(): SeedSpec | null {
    return this._seedSpec;
  }

  buildSeedSpec(
    goal: string,
    constraints: string[],
    acceptanceCriteria: string[],
    ontologyName: string,
    ontologyFields: OntologyField[],
    autoGenerated = false,
  ): SeedSpec {
    return {
      goal,
      taskType: 'code',
      constraints: [...constraints],
      acceptanceCriteria: acceptanceCriteria.map((desc, i) => ({
        id: `ac_${i + 1}`,
        description: desc,
        status: 'pending',
      })),
      ontology: {
        name: ontologyName,
        description: `Ontology for ${ontologyName}`,
        fields: [...ontologyFields],
      },
      evaluationPrinciples: [
        { name: 'completeness', description: 'All requirements are met', weight: 1.0 },
        { name: 'correctness', description: 'Implementation is correct', weight: 1.0 },
        { name: 'clarity', description: 'Code is clear and maintainable', weight: 0.8 },
      ],
      exitConditions: [
        {
          name: 'all_criteria_met',
          description: 'All acceptance criteria satisfied',
          criteria: '100% criteria pass',
        },
      ],
      ambiguityScore: 0.15,
      autoGenerated,
      createdAt: new Date().toISOString(),
    };
  }

  generateSeedSpecFromInterview(
    goal: string,
    constraints: string[],
    acceptanceCriteria: string[],
    ontologyName: string,
    ontologyFields: OntologyField[],
    autoGenerated = false,
  ): SeedSpec {
    return this.buildSeedSpec(
      goal,
      constraints,
      acceptanceCriteria,
      ontologyName,
      ontologyFields,
      autoGenerated,
    );
  }

  async calculateDrift(currentOutput: string, constraintViolations: string[]): Promise<DriftMetrics> {
    if (!this._seedSpec) {
      return { goalDrift: 0, constraintDrift: 0, ontologyDrift: 0 };
    }
    const llmMetrics = await this._calculateDriftWithLLM(currentOutput, constraintViolations);
    if (llmMetrics !== null) {
      this._driftMetrics = llmMetrics;
      return llmMetrics;
    }
    throw new Error(
      'LLM-based drift evaluation failed: the LLM is unavailable or returned invalid JSON.',
    );
  }

  detectStagnation(
    phaseOutputs: string[],
    errorSignatures: string[],
    driftScores: number[],
  ): StagnationDetection[] {
    const results: StagnationDetection[] = [
      this._detectSpinning(phaseOutputs, errorSignatures),
      this._detectOscillation(phaseOutputs),
      this._detectNoDrift(driftScores),
      this._detectDiminishingReturns(driftScores),
    ];

    this._stagnationHistory.push({
      timestamp: Date.now(),
      phaseOutputs: [...phaseOutputs],
      errorSignatures: [...errorSignatures],
      driftScores: [...driftScores],
      detections: [...results],
    });

    return results;
  }

  private _detectSpinning(
    _phaseOutputs: string[],
    errorSignatures: string[],
  ): StagnationDetection {
    const threshold = 3;
    const hashes = errorSignatures.map((e) => this._hash(e));
    const last = hashes.slice(-threshold);
    const detected = last.length >= threshold && last.every((h) => h === last[0]);
    return {
      pattern: 'spinning',
      detected,
      confidence: detected ? 0.9 : 0.0,
      evidence: { threshold, lastErrors: errorSignatures.slice(-threshold) },
    };
  }

  private _detectOscillation(phaseOutputs: string[]): StagnationDetection {
    const cycles = 2;
    const hashes = phaseOutputs.map((o) => this._hash(o));
    if (hashes.length < cycles * 2) {
      return { pattern: 'oscillation', detected: false, confidence: 0.0, evidence: {} };
    }
    const n = hashes.length;
    const detected =
      hashes[n - 1] === hashes[n - 3] && hashes[n - 2] === hashes[n - 4];
    return {
      pattern: 'oscillation',
      detected,
      confidence: detected ? 0.85 : 0.0,
      evidence: { cycles, lastOutputs: phaseOutputs.slice(-cycles * 2) },
    };
  }

  private _detectNoDrift(driftScores: number[]): StagnationDetection {
    const threshold = 3;
    const epsilon = 0.01;
    if (driftScores.length < threshold) {
      return { pattern: 'no_drift', detected: false, confidence: 0.0, evidence: {} };
    }
    const last = driftScores.slice(-threshold);
    const maxDiff = Math.max(...last) - Math.min(...last);
    const detected = maxDiff < epsilon;
    return {
      pattern: 'no_drift',
      detected,
      confidence: detected ? 0.8 : 0.0,
      evidence: { threshold, maxDiff, lastScores: last },
    };
  }

  private _detectDiminishingReturns(driftScores: number[]): StagnationDetection {
    const threshold = 3;
    if (driftScores.length < threshold + 1) {
      return { pattern: 'diminishing_returns', detected: false, confidence: 0.0, evidence: {} };
    }
    const improvements: number[] = [];
    for (let i = 1; i < driftScores.length; i++) {
      improvements.push((driftScores[i] ?? 0) - (driftScores[i - 1] ?? 0));
    }
    const last = improvements.slice(-threshold);
    const avgImprovement = last.reduce((a, b) => a + b, 0) / last.length;
    const detected = avgImprovement < 0.01;
    return {
      pattern: 'diminishing_returns',
      detected,
      confidence: detected ? 0.75 : 0.0,
      evidence: { threshold, avgImprovement, lastImprovements: last },
    };
  }

  private _hash(text: string): string {
    let h1 = 5381;
    let h2 = 0;
    for (let i = 0; i < text.length; i++) {
      const c = text.charCodeAt(i);
      h1 = ((h1 << 5) + h1 + c) | 0;
      h2 = (h2 * 33 + c) | 0;
    }
    return `${h1.toString(36)}:${h2.toString(36)}`;
  }

  private _normalizeSectionName(section: string): string {
    let result = '';
    let previousWasSpace = true;
    for (const c of section.trim().toLowerCase()) {
      if (c === ' ' || c === '\t' || c === '\n' || c === '\r' || c === '\f' || c === '\v') {
        if (!previousWasSpace) {
          result += '_';
          previousWasSpace = true;
        }
      } else {
        result += c;
        previousWasSpace = false;
      }
    }
    return result;
  }

  generateLateralThinking(
    persona: ThinkingPersona,
    problemContext: string,
    currentApproach: string,
  ): LateralThinkingResult {
    const summaries: Record<ThinkingPersona, string> = {
      hacker: 'Find unconventional workarounds and bypasses',
      researcher: 'Seek additional information and context',
      simplifier: 'Reduce complexity and challenge assumptions',
      architect: 'Restructure the approach fundamentally',
      contrarian: 'Challenge assumptions and invert the problem',
    };

    const prompt = `You are acting as a ${persona}.\n${summaries[persona]}.\n\nProblem context: ${problemContext}\nCurrent approach: ${currentApproach}\n\nGenerate an alternative approach from this perspective. Be specific and actionable.`;

    const questions = this._generateQuestionsForPersona(persona, problemContext);

    const result: LateralThinkingResult = {
      persona,
      prompt,
      approachSummary: summaries[persona],
      questions,
    };

    this._lateralThinking = result;
    return result;
  }

  private _generateQuestionsForPersona(
    persona: ThinkingPersona,
    _context: string,
  ): string[] {
    const questionBanks: Record<ThinkingPersona, string[]> = {
      hacker: [
        'What is the simplest workaround?',
        'What assumption can we bypass?',
        'What is the minimal viable fix?',
      ],
      researcher: [
        'What information are we missing?',
        'What similar problems have been solved?',
        'What documentation should we read?',
      ],
      simplifier: [
        'What can we remove without breaking it?',
        'What is the core problem, not the symptoms?',
        'Can we solve a smaller version first?',
      ],
      architect: [
        'What is the fundamental structure?',
        'How would we design this from scratch?',
        'What abstraction would clarify this?',
      ],
      contrarian: [
        'What if the opposite is true?',
        'What assumption is most dangerous?',
        'What would make this definitely fail?',
      ],
    };
    return questionBanks[persona];
  }

  setEvaluationPlan(plan: EvaluationPlan): void {
    this._evaluationPlan = plan;
  }

  get evaluationPlan(): EvaluationPlan | null {
    return this._evaluationPlan;
  }

  generateDefaultEvaluationPlan(): EvaluationPlan {
    return {
      stage1Mechanical: true,
      stage2Semantic: true,
      stage3Consensus: false,
      mechanicalChecks: ['lint', 'build', 'test', 'static_analysis', 'coverage'],
      semanticCriteria: ['ac_compliance', 'code_quality', 'maintainability'],
    };
  }

  serialize(): Record<string, unknown> {
    return {
      seedSpec: this._seedSpec,
      driftMetrics: this._driftMetrics,
      stagnationHistory: this._stagnationHistory,
      evaluationPlan: this._evaluationPlan,
      lateralThinking: this._lateralThinking,
      interviewState: this._interviewState,
      currentPerspective: this._currentPerspective,
    };
  }

  // ---------------------------------------------------------------------------
  // Interview & Ambiguity Scoring
  // ---------------------------------------------------------------------------

  private _currentPerspective: InterviewPerspective = 'researcher';
  private readonly _perspectives: InterviewPerspective[] = [
    'researcher',
    'simplifier',
    'architect',
    'breadth-keeper',
    'seed-closer',
  ];

  private _interviewState: InterviewState = {
    rounds: [],
    initialContext: '',
    ambiguityScore: null,
    completionCandidateStreak: 0,
    lastReadyEvidenceHash: undefined,
    lastReadyRoundCount: -1,
    lastScoredEvidenceHash: undefined,
    cachedLlmResult: undefined,
    monotonicReadyLocked: false,
  };

  get interviewState(): InterviewState {
    return this._interviewState;
  }

  get currentPerspective(): InterviewPerspective {
    return this._currentPerspective;
  }

  advancePerspective(): void {
    const idx = this._perspectives.indexOf(this._currentPerspective);
    this._currentPerspective = this._perspectives[(idx + 1) % this._perspectives.length] ?? 'researcher';
  }

  getPerspectiveDescription(): string {
    const descriptions: Record<InterviewPerspective, string> = {
      researcher:
        'Explore industry and technical context. Surface benchmarks, best practices, and opportunities the user may not know exist.',
      simplifier:
        'Contrast MVP vs premium scope. Show what to cut vs what unlocks disproportionate value with modest extra effort.',
      architect:
        'Propose structural and pattern improvements. Focus on interfaces, maintainability, and long-term design quality.',
      'breadth-keeper':
        'Balance stretch goals vs non-goals. Catch missed quality dimensions, edge cases, and expansion opportunities.',
      'seed-closer':
        'Lock the elevated UltraGoal into measurable acceptance criteria and a verifiable completion test.',
    };
    return descriptions[this._currentPerspective];
  }

  startInterview(initialContext: string): void {
    this._lastAmbiguityResult = null;
    this._interviewState = {
      rounds: [],
      initialContext,
      ambiguityScore: null,
      completionCandidateStreak: 0,
      lastReadyEvidenceHash: undefined,
      lastScoredEvidenceHash: undefined,
      cachedLlmResult: undefined,
      monotonicReadyLocked: false,
    };
  }

  addInterviewRound(question: string, userResponse: string): void {
    const round: InterviewRound = {
      roundNumber: this._interviewState.rounds.length + 1,
      question,
      userResponse,
      timestamp: Date.now(),
    };
    this.advancePerspective();
    this._interviewState = {
      ...this._interviewState,
      rounds: [...this._interviewState.rounds, round],
      // A new round changes the evidence — invalidate the LLM cache and
      // unlock monotonic ready so the gate is re-evaluated fairly.
      lastScoredEvidenceHash: undefined,
      cachedLlmResult: undefined,
      monotonicReadyLocked: false,
    };
  }

  recordInterviewAnswers(
    questions: ReadonlyArray<{ readonly question: string; readonly header?: string }>,
    answers: Record<string, string | true>,
  ): void {
    const answerText = Object.entries(answers)
      .map(([key, value]) => `${key}: ${value === true ? 'true' : value}`)
      .join('\n');
    const questionText = questions
      .map((q) => q.header === undefined || q.header.length === 0
        ? q.question
        : `${q.header}: ${q.question}`)
      .join('\n');
    this.addInterviewRound(questionText, answerText);
  }

  /**
   * Calculate ambiguity score from interview state using the LLM-based
   * Ouroboros-style clarity scorer. Regex heuristics have been removed; all
   * ambiguity dimensions are derived from the LLM's structured JSON response.
   *
   * Stability guarantees (prevents infinite interview loops):
   * - **Evidence-keyed cache**: if the evidence text has not changed since the
   *   last LLM call, the cached result is reused — no new LLM round, so the
   *   score cannot oscillate between calls.
   * - **Monotonic ready**: once `isReadyForSeed` is true for a given evidence
   *   hash, it stays true until a new interview round changes the evidence.
   *   LLM non-determinism cannot un-ready an already-passed gate.
   * - **Max rounds**: after MAX_INTERVIEW_ROUNDS the engine force-advances
   *   even if the LLM keeps producing borderline scores.
   */
  async calculateAmbiguityScore(
    signal?: AbortSignal,
    onProgress?: (text: string) => void,
  ): Promise<AmbiguityScoreResult> {
    const evidence = this.interviewEvidenceText();
    const evidenceHash = this._hash(evidence);

    // ── Evidence-keyed cache hit: reuse the LLM result without a new call.
    if (
      this._interviewState.lastScoredEvidenceHash === evidenceHash &&
      this._interviewState.cachedLlmResult !== undefined
    ) {
      return this.buildScoreResult(
        this._interviewState.cachedLlmResult,
        evidenceHash,
        onProgress,
        /* skipLlm */ true,
      );
    }

    this.emitProgress(onProgress, 'Analyzing your answers...');
    this.emitProgress(
      onProgress,
      'Scoring ambiguity across goal, constraints, and success criteria...',
    );

    const llmResult = await this._calculateAmbiguityWithLLM(evidence, signal);
    if (llmResult === null) {
      throw new Error(
        'LLM-based ambiguity scoring failed: the LLM is unavailable or returned invalid JSON.',
      );
    }
    this._lastAmbiguityResult = llmResult;

    // Cache the LLM result for this evidence hash so subsequent calls
    // (e.g. interviewReadiness → calculateAmbiguityScore) don't re-call the
    // LLM and produce a different score.
    this._interviewState = {
      ...this._interviewState,
      lastScoredEvidenceHash: evidenceHash,
      cachedLlmResult: llmResult,
    };

    return this.buildScoreResult(llmResult, evidenceHash, onProgress, false);
  }

  /**
   * Build the {@link AmbiguityScoreResult} from a (possibly cached) LLM
   * result and update the interview-state streak / monotonic-ready flags.
   */
  private buildScoreResult(
    llmResult: LLMAmbiguityResult,
    evidenceHash: string,
    onProgress: ((text: string) => void) | undefined,
    skipLlm: boolean,
  ): AmbiguityScoreResult {
    const totalRounds = this._interviewState.rounds.length;
    const answerRoundClarity = Math.min(totalRounds / 3, 1.0);
    const specificityClarity = llmResult.specificityScore;

    const goalClarity = this.clampClarity(
      llmResult.goalClarity * 0.7 + answerRoundClarity * 0.2 + specificityClarity * 0.1,
    );
    const constraintClarity = this.clampClarity(
      llmResult.constraintClarity * 0.75 + specificityClarity * 0.15 + answerRoundClarity * 0.1,
    );
    const criteriaClarity = this.clampClarity(
      llmResult.successCriteriaClarity * 0.75 + specificityClarity * 0.15 + answerRoundClarity * 0.1,
    );

    const rawOverall = 1.0 - (
      goalClarity * 0.4 +
      constraintClarity * 0.3 +
      criteriaClarity * 0.3
    );

    const presentSet = new Set(
      llmResult.presentSections.map((section) => this._normalizeSectionName(String(section))),
    );
    const openGaps = ULTRA_PLAN_REQUIRED_SECTIONS.filter((section) => !presentSet.has(section));
    const gapPressure = openGaps.length / ULTRA_PLAN_REQUIRED_SECTIONS.length;
    const verifiableGoal = llmResult.verifiableGoal;
    const floorFailures = this.floorFailures(goalClarity, constraintClarity, criteriaClarity);
    const floorPressure = floorFailures.length > 0 ? AMBIGUITY_THRESHOLD + 0.01 : 0;
    const gatedOverall = this.clampClarity(
      Math.max(rawOverall, gapPressure, verifiableGoal ? 0 : 0.45, floorPressure),
    );

    const milestone: AmbiguityMilestone =
      gatedOverall <= AMBIGUITY_THRESHOLD ? 'ready' :
      gatedOverall <= 0.3 ? 'refined' :
      gatedOverall <= 0.4 ? 'progress' : 'initial';

    let isReady = (
      gatedOverall <= AMBIGUITY_THRESHOLD &&
      openGaps.length === 0 &&
      verifiableGoal &&
      floorFailures.length === 0
    );

    // ── Monotonic ready: once locked, stay ready until evidence changes.
    if (this._interviewState.monotonicReadyLocked === true) {
      isReady = true;
    }

    // ── Max-rounds safety: force ready after too many rounds.
    const hitMaxRounds = totalRounds >= MAX_INTERVIEW_ROUNDS;
    if (hitMaxRounds && !isReady) {
      isReady = true;
      this.emitProgress(
        onProgress,
        `Reached max interview rounds (${MAX_INTERVIEW_ROUNDS}). Force-advancing to Design.`,
      );
    }

    const lastReadyRoundCount = this._interviewState.lastReadyRoundCount ?? -1;
    const hasNewRoundSinceLastReady =
      this._interviewState.rounds.length > lastReadyRoundCount;
    const evidenceChanged =
      this._interviewState.lastReadyEvidenceHash !== evidenceHash;

    if (isReady && (evidenceChanged || hasNewRoundSinceLastReady)) {
      this._interviewState = {
        ...this._interviewState,
        completionCandidateStreak: this._interviewState.completionCandidateStreak + 1,
        lastReadyEvidenceHash: evidenceHash,
        lastReadyRoundCount: this._interviewState.rounds.length,
        // Lock monotonic ready so subsequent calls with the same evidence
        // cannot un-ready the gate due to LLM non-determinism.
        monotonicReadyLocked: true,
      };
    } else {
      this._interviewState = {
        ...this._interviewState,
        completionCandidateStreak: isReady ? this._interviewState.completionCandidateStreak : 0,
        lastReadyEvidenceHash: isReady ? this._interviewState.lastReadyEvidenceHash : undefined,
        lastReadyRoundCount: isReady ? this._interviewState.lastReadyRoundCount : -1,
        // Only unlock when a genuinely new round makes isReady false.
        monotonicReadyLocked: isReady ? this._interviewState.monotonicReadyLocked : false,
      };
    }

    const result: AmbiguityScoreResult = {
      overallScore: gatedOverall,
      breakdown: [
        {
          name: 'goal_clarity',
          clarityScore: goalClarity,
          weight: 0.4,
          justification: llmResult.justifications.goal,
        },
        {
          name: 'constraint_clarity',
          clarityScore: constraintClarity,
          weight: 0.3,
          justification: llmResult.justifications.constraints,
        },
        {
          name: 'success_criteria_clarity',
          clarityScore: criteriaClarity,
          weight: 0.3,
          justification: llmResult.justifications.successCriteria,
        },
        {
          name: 'seed_ledger_gaps',
          clarityScore: 1 - gapPressure,
          weight: 1,
          justification: `Open required sections: ${openGaps.length === 0 ? 'none' : openGaps.join(', ')}`,
        },
        {
          name: 'verifiable_goal',
          clarityScore: verifiableGoal ? 1 : 0,
          weight: 1,
          justification: 'UltraGoal must be judgeable as complete or incomplete.',
        },
      ],
      isReadyForSeed: isReady,
      milestone,
      floorFailures,
    };

    this._interviewState = {
      ...this._interviewState,
      ambiguityScore: result,
    };

    this.emitProgress(
      onProgress,
      `Goal clarity: ${goalClarity.toFixed(2)} — ${llmResult.justifications.goal}`,
    );
    this.emitProgress(
      onProgress,
      `Constraint clarity: ${constraintClarity.toFixed(2)} — ${llmResult.justifications.constraints}`,
    );
    this.emitProgress(
      onProgress,
      `Success criteria clarity: ${criteriaClarity.toFixed(2)} — ${llmResult.justifications.successCriteria}`,
    );
    this.emitProgress(
      onProgress,
      `Open Seed gaps: ${openGaps.length === 0 ? 'none' : openGaps.join(', ')}`,
    );
    if (floorFailures.length > 0) {
      this.emitProgress(onProgress, `Dimension floor failures: ${floorFailures.join('; ')}`);
    }
    this.emitProgress(
      onProgress,
      result.isReadyForSeed
        ? 'Seed Spec is ready. Preparing next question...'
        : 'Preparing next question...',
    );

    return result;
  }

  /**
   * Check if interview can auto-complete (2 consecutive ready scores).
   */
  async canAutoComplete(): Promise<boolean> {
    await this.calculateAmbiguityScore();
    return (
      this._interviewState.ambiguityScore?.isReadyForSeed === true &&
      this._interviewState.completionCandidateStreak >= COMPLETION_STREAK_REQUIRED
    );
  }

  async interviewReadiness(): Promise<UltraPlanReadiness> {
    const ambiguityScore = await this.calculateAmbiguityScore();
    const openGaps = await this.openSeedGaps();
    const verifiableGoal = this._lastAmbiguityResult?.verifiableGoal ?? false;
    const stableReady =
      ambiguityScore.isReadyForSeed &&
      this._interviewState.completionCandidateStreak >= COMPLETION_STREAK_REQUIRED;
    return {
      ready: ambiguityScore.isReadyForSeed && openGaps.length === 0 && verifiableGoal,
      stableReady,
      openGaps,
      ambiguityScore,
      verifiableGoal,
      completionCandidateStreak: this._interviewState.completionCandidateStreak,
      floorFailures: ambiguityScore.floorFailures,
    };
  }

  async openSeedGaps(): Promise<readonly UltraPlanRequiredSection[]> {
    if (this._lastAmbiguityResult === null) {
      await this.calculateAmbiguityScore();
    }
    const presentSet = new Set(
      (this._lastAmbiguityResult?.presentSections ?? []).map((section) =>
        this._normalizeSectionName(String(section)),
      ),
    );
    return ULTRA_PLAN_REQUIRED_SECTIONS.filter((section) => !presentSet.has(section));
  }

  async readinessBlockerMessage(readiness?: UltraPlanReadiness): Promise<string> {
    const resolved = readiness ?? (await this.interviewReadiness());
    return formatInterviewReadinessGuide(resolved);
  }

  /**
   * Generate Seed Spec from interview results.
   * Extracts Goal, Constraints, AC, and Ontology from Q&A.
   */
  async autoGenerateSeedSpecFromInterview(
    ontologyName: string,
    signal?: AbortSignal,
    onProgress?: (text: string) => void,
  ): Promise<SeedSpec> {
    this.emitProgress(onProgress, 'Extracting Seed Spec from interview evidence...');
    const allText = this.interviewEvidenceText();
    const llmResult = await this._extractSeedSpecFromLLM(allText, ontologyName, signal);
    if (llmResult !== null) {
      this.emitProgress(onProgress, 'Seed Spec extracted.');
      return this._normalizeSeedSpec(llmResult, ontologyName, true);
    }
    throw new Error(
      'LLM-based Seed Spec extraction failed: the LLM is unavailable or returned invalid JSON.',
    );
  }

  private emitProgress(onProgress: ((text: string) => void) | undefined, text: string): void {
    if (onProgress === undefined) return;
    try {
      onProgress(text);
    } catch {
      // Progress is best-effort; do not let a listener failure break the engine.
    }
  }

  private interviewEvidenceText(): string {
    return [
      this._interviewState.initialContext,
      ...this.recentUserPromptTexts(),
      ...this._interviewState.rounds.map((r) => r.userResponse),
    ].join('\n');
  }

  private recentUserPromptTexts(): string[] {
    return (this.agent.context?.history ?? [])
      .filter((message) => message.role === 'user' && isRealUserPromptOrigin(message.origin))
      .slice(-3)
      .map((message) => extractText(message, '\n').trim())
      .filter((text) => text.length > 0);
  }

  private clampClarity(value: number): number {
    return Math.max(0, Math.min(1, value));
  }

  private floorFailures(
    goalClarity: number,
    constraintClarity: number,
    criteriaClarity: number,
  ): readonly string[] {
    const failures: string[] = [];
    if (goalClarity < GOAL_CLARITY_FLOOR) {
      failures.push(`Goal Clarity ${goalClarity.toFixed(2)} < ${GOAL_CLARITY_FLOOR.toFixed(2)}`);
    }
    if (constraintClarity < CONSTRAINT_CLARITY_FLOOR) {
      failures.push(`Constraint Clarity ${constraintClarity.toFixed(2)} < ${CONSTRAINT_CLARITY_FLOOR.toFixed(2)}`);
    }
    if (criteriaClarity < SUCCESS_CRITERIA_CLARITY_FLOOR) {
      failures.push(`Success Criteria Clarity ${criteriaClarity.toFixed(2)} < ${SUCCESS_CRITERIA_CLARITY_FLOOR.toFixed(2)}`);
    }
    return failures;
  }

  // ---------------------------------------------------------------------------
  // LLM-backed Seed Spec extraction, ambiguity scoring, and drift evaluation
  // ---------------------------------------------------------------------------

  private get _llmAvailable(): boolean {
    return (
      typeof this.agent.generate === 'function' &&
      this.agent.config?.provider !== undefined
    );
  }

  private async _llmJsonRequest<T>(
    system: string,
    user: string,
    signal?: AbortSignal,
  ): Promise<T | null> {
    if (!this._llmAvailable) return null;
    try {
      const response = await this.agent.generate(
        this.agent.config.provider,
        system,
        [],
        [createUserMessage(user)],
        undefined,
        { signal },
      );
      const text = this._extractTextFromLLMResponse(response);
      const json = this._extractJsonFromText(text);
      if (json === null) return null;
      return JSON.parse(json) as T;
    } catch {
      return null;
    }
  }

  private _extractTextFromLLMResponse(response: unknown): string {
    const msg = response as {
      message?: {
        content?: ReadonlyArray<{ type?: string; text?: string }>;
      };
    };
    const parts = msg.message?.content ?? [];
    for (const part of parts) {
      if (part.type === 'text' && typeof part.text === 'string') return part.text;
    }
    return '';
  }

  private _extractJsonFromText(text: string): string | null {
    const trimmed = text.trim();
    if (trimmed.startsWith('```')) {
      const match = trimmed.match(/^```(?:json)?\s*\n([\s\S]*?)\n```$/);
      if (match?.[1]) return match[1].trim();
    }
    const start = trimmed.indexOf('{');
    const end = trimmed.lastIndexOf('}');
    if (start !== -1 && end !== -1 && end > start) return trimmed.slice(start, end + 1);
    return null;
  }

  private async _calculateAmbiguityWithLLM(
    evidence: string,
    signal?: AbortSignal,
  ): Promise<LLMAmbiguityResult | null> {
    const system = `You are an expert requirements analyst. Evaluate the clarity of the requirements captured in the interview evidence.

Evaluate three components:
1. Goal Clarity (40%): Is the goal specific and well-defined? Are actors, inputs, and outputs clear?
2. Constraint Clarity (30%): Are constraints, non-goals, failure modes, and runtime context clear?
3. Success Criteria Clarity (30%): Are acceptance criteria, verification plan, and completion criterion measurable?

Score each component from 0.0 (unclear) to 1.0 (perfectly clear).

Also report:
- present_sections: list of section names present in the evidence from [goal, actors, inputs, outputs, constraints, non_goals, acceptance_criteria, verification_plan, failure_modes, runtime_context]
- verifiable_goal: boolean, whether the goal has a clear true/false or pass/fail completion criterion
- specificity_score: 0.0-1.0, how specific the requirements are (files, commands, APIs, concrete paths, etc.)

Respond ONLY with valid JSON. No other text before or after.

{
  "goal_clarity_score": 0.0,
  "goal_clarity_justification": "...",
  "constraint_clarity_score": 0.0,
  "constraint_clarity_justification": "...",
  "success_criteria_clarity_score": 0.0,
  "success_criteria_clarity_justification": "...",
  "present_sections": ["goal"],
  "verifiable_goal": false,
  "specificity_score": 0.0
}`;

    const raw = await this._llmJsonRequest<{
      goal_clarity_score?: number;
      goal_clarity_justification?: string;
      constraint_clarity_score?: number;
      constraint_clarity_justification?: string;
      success_criteria_clarity_score?: number;
      success_criteria_clarity_justification?: string;
      present_sections?: unknown;
      verifiable_goal?: boolean;
      specificity_score?: number;
    }>(system, evidence, signal);

    if (raw === null) return null;

    const clamp = (value: number): number => {
      if (typeof value !== 'number' || Number.isNaN(value)) return 0;
      return Math.max(0, Math.min(1, value));
    };

    const presentSections = Array.isArray(raw.present_sections)
      ? raw.present_sections.map((section) => String(section))
      : [];

    return {
      goalClarity: clamp(raw.goal_clarity_score ?? 0),
      constraintClarity: clamp(raw.constraint_clarity_score ?? 0),
      successCriteriaClarity: clamp(raw.success_criteria_clarity_score ?? 0),
      presentSections,
      verifiableGoal: raw.verifiable_goal === true,
      specificityScore: clamp(raw.specificity_score ?? 0),
      justifications: {
        goal: typeof raw.goal_clarity_justification === 'string' ? raw.goal_clarity_justification : '',
        constraints: typeof raw.constraint_clarity_justification === 'string' ? raw.constraint_clarity_justification : '',
        successCriteria: typeof raw.success_criteria_clarity_justification === 'string' ? raw.success_criteria_clarity_justification : '',
      },
    };
  }

  private async _extractSeedSpecFromLLM(
    evidence: string,
    ontologyName: string,
    signal?: AbortSignal,
  ): Promise<unknown | null> {
    const system = `You are an expert planning assistant. Extract a structured Seed Spec from the provided evidence. Return ONLY a JSON object matching the requested schema. Do not wrap it in markdown code fences. Use the same language as the evidence.`;
    const user = [
      `Extract a Seed Spec from the following interview evidence.`,
      ``,
      `Required JSON schema (omit fields that are empty):`,
      JSON.stringify({
        goal: 'string',
        taskType: 'code | research | analysis',
        constraints: ['string'],
        acceptanceCriteria: ['string'],
        ontology: {
          name: 'string',
          description: 'string',
          fields: [{ name: 'string', type: 'string', description: 'string', required: true }],
        },
        evaluationPrinciples: [{ name: 'string', description: 'string', weight: 1.0 }],
        exitConditions: [{ name: 'string', description: 'string', criteria: 'string' }],
        ambiguityScore: 0.15,
      }, null, 2),
      ``,
      `Evidence:\n${evidence}`,
    ].join('\n');
    return this._llmJsonRequest<unknown>(system, user, signal);
  }

  private _normalizeSeedSpec(raw: unknown, ontologyName: string, autoGenerated: boolean): SeedSpec {
    const parsed = raw as Partial<{
      goal: string;
      taskType: string;
      constraints: unknown[];
      acceptanceCriteria: unknown[];
      ontology: Partial<{
        name: string;
        description: string;
        fields: unknown[];
      }>;
      evaluationPrinciples: unknown[];
      exitConditions: unknown[];
      ambiguityScore: number;
    }>;
    const goal =
      typeof parsed.goal === 'string' && parsed.goal.trim().length > 0
        ? parsed.goal.trim()
        : this._interviewState.initialContext;
    const taskType = ['code', 'research', 'analysis'].includes(parsed.taskType as string)
      ? (parsed.taskType as SeedSpec['taskType'])
      : 'code';
    const constraints = Array.isArray(parsed.constraints)
      ? parsed.constraints.filter((c): c is string => typeof c === 'string')
      : [];
    const acceptanceCriteria = Array.isArray(parsed.acceptanceCriteria)
      ? parsed.acceptanceCriteria.filter((c): c is string => typeof c === 'string')
      : [];
    const ontology = this._normalizeOntology(parsed.ontology, ontologyName);
    const evaluationPrinciples = Array.isArray(parsed.evaluationPrinciples)
      ? parsed.evaluationPrinciples
          .filter((p): p is { name: string; description: string; weight: number } => {
            const item = p as { name?: unknown; description?: unknown; weight?: unknown };
            return (
              typeof item.name === 'string' &&
              typeof item.description === 'string' &&
              typeof item.weight === 'number'
            );
          })
          .map((p) => ({ name: p.name, description: p.description, weight: p.weight }))
      : [
          { name: 'completeness', description: 'All requirements are met', weight: 1.0 },
          { name: 'correctness', description: 'Implementation is correct', weight: 1.0 },
          { name: 'clarity', description: 'Code is clear and maintainable', weight: 0.8 },
        ];
    const exitConditions = Array.isArray(parsed.exitConditions)
      ? parsed.exitConditions
          .filter((c): c is { name: string; description: string; criteria: string } => {
            const item = c as { name?: unknown; description?: unknown; criteria?: unknown };
            return (
              typeof item.name === 'string' &&
              typeof item.description === 'string' &&
              typeof item.criteria === 'string'
            );
          })
          .map((c) => ({ name: c.name, description: c.description, criteria: c.criteria }))
      : [{ name: 'all_criteria_met', description: 'All acceptance criteria satisfied', criteria: '100% criteria pass' }];
    const ambiguityScore = typeof parsed.ambiguityScore === 'number' ? parsed.ambiguityScore : 0.15;
    const seed = this.buildSeedSpec(
      goal,
      constraints,
      acceptanceCriteria,
      ontology.name,
      [...ontology.fields],
      autoGenerated,
    );
    // buildSeedSpec overrides ambiguityScore; patch it back if LLM provided one
    return { ...seed, taskType, evaluationPrinciples, exitConditions, ambiguityScore };
  }

  private _normalizeOntology(raw: unknown, defaultName: string): OntologySchema {
    const parsed = raw as Partial<{
      name: string;
      description: string;
      fields: unknown[];
    }>;
    const name =
      typeof parsed?.name === 'string' && parsed.name.trim().length > 0
        ? parsed.name.trim()
        : defaultName;
    const description =
      typeof parsed?.description === 'string' && parsed.description.trim().length > 0
        ? parsed.description.trim()
        : `Ontology for ${name}`;
    const fields = Array.isArray(parsed?.fields)
      ? parsed.fields
          .filter((f): f is { name: string; type: string; description: string; required: boolean } => {
            const item = f as { name?: unknown; type?: unknown; description?: unknown; required?: unknown };
            return (
              typeof item.name === 'string' &&
              typeof item.type === 'string' &&
              typeof item.description === 'string' &&
              typeof item.required === 'boolean'
            );
          })
          .map((f) => ({ name: f.name, type: f.type, description: f.description, required: f.required }))
      : [];
    return { name, description, fields: [...fields] };
  }

  private async _calculateDriftWithLLM(
    currentOutput: string,
    constraintViolations: string[],
  ): Promise<DriftMetrics | null> {
    if (!this._seedSpec) return null;
    const system = `You are a semantic drift evaluator. Compare the Seed Spec and the current plan/output. Return ONLY a JSON object with goalDrift, constraintDrift, ontologyDrift, each a number 0..1. 0 = perfectly aligned, 1 = completely divergent. Be strict about constraint violations.`;
    const user = [
      `Seed Spec:\n${JSON.stringify(this._seedSpec, null, 2)}`,
      ``,
      `Current output/plan:\n${currentOutput}`,
      ``,
      `Reported constraint violations:\n${constraintViolations.length > 0 ? constraintViolations.join('\n') : 'none'}`,
      ``,
      `Return JSON: { "goalDrift": number, "constraintDrift": number, "ontologyDrift": number }`,
    ].join('\n');
    const raw = await this._llmJsonRequest<Partial<DriftMetrics>>(system, user);
    if (raw === null) return null;
    const clamp = (v: number) => Math.max(0, Math.min(1, v));
    return {
      goalDrift: clamp(typeof raw.goalDrift === 'number' ? raw.goalDrift : 0),
      constraintDrift: clamp(typeof raw.constraintDrift === 'number' ? raw.constraintDrift : 0),
      ontologyDrift: clamp(typeof raw.ontologyDrift === 'number' ? raw.ontologyDrift : 0),
    };
  }

  deserialize(data: Record<string, unknown>): void {
    if (data['seedSpec']) {
      const seed = data['seedSpec'] as SeedSpec;
      this._seedSpec = {
        ...seed,
        autoGenerated: seed.autoGenerated ?? false,
      };
    }
    if (data['driftMetrics']) this._driftMetrics = data['driftMetrics'] as DriftMetrics;
    if (data['stagnationHistory'])
      this._stagnationHistory = data['stagnationHistory'] as StagnationHistoryEntry[];
    if (data['evaluationPlan']) this._evaluationPlan = data['evaluationPlan'] as EvaluationPlan;
    if (data['lateralThinking']) this._lateralThinking = data['lateralThinking'] as LateralThinkingResult;
    if (data['interviewState']) this._interviewState = data['interviewState'] as InterviewState;
    if (data['currentPerspective']) {
      this._currentPerspective = data['currentPerspective'] as InterviewPerspective;
    }
  }
}

export function pickNextInterviewFocus(readiness: UltraPlanReadiness): string {
  if (!readiness.verifiableGoal) {
    return [
      'Completion Criterion — ask how success is judged true/false or pass/fail.',
      'Example: "true when deliverable X exists and you approve it; false otherwise."',
    ].join(' ');
  }
  const firstGap = readiness.openGaps[0];
  if (firstGap !== undefined) {
    const guidance = ULTRA_PLAN_SECTION_GUIDANCE[firstGap];
    return `${guidance.label} — ${guidance.askHint}`;
  }
  if (readiness.floorFailures.length > 0) {
    return `Clarify ${readiness.floorFailures[0]} — ask for concrete specifics (files, commands, metrics, deliverables).`;
  }
  return 'Clarify the vaguest remaining requirement with concrete specifics.';
}

export function formatInterviewReadinessGuide(readiness: UltraPlanReadiness): string {
  if (readiness.ready) {
    return [
      'Interview readiness: READY for Design.',
      'Call NextPhase({ phase: "design" }). Seed Spec will be auto-extracted from interview evidence.',
      'Do not Write or Edit the plan file yet — that happens in Write phase.',
    ].join('\n');
  }

  const lines: string[] = [
    'Interview readiness: NOT READY for Design.',
    '',
    'WHY NextPhase is blocked (close these before retrying):',
  ];

  let blockerNum = 1;

  if (!readiness.verifiableGoal) {
    lines.push(
      `${blockerNum++}. verifiable_goal=false — no true/false Completion Criterion yet.`,
      '   The UltraGoal must be judgeable as complete/incomplete.',
      '   ambiguity stays >= 0.45 until a Completion Criterion is captured in interview answers.',
    );
  }

  if (readiness.openGaps.length > 0) {
    lines.push(
      `${blockerNum++}. open_gaps — ${readiness.openGaps.length} missing Seed section(s): ${readiness.openGaps.join(', ')}`,
    );
    for (const gap of readiness.openGaps.slice(0, 3)) {
      const guidance = ULTRA_PLAN_SECTION_GUIDANCE[gap];
      lines.push(`   - ${guidance.label}: ${guidance.askHint}`);
    }
    if (readiness.openGaps.length > 3) {
      lines.push(`   - ...then the remaining ${readiness.openGaps.length - 3} gap(s).`);
    }
  }

  if (readiness.floorFailures.length > 0) {
    lines.push(
      `${blockerNum++}. clarity floors not met: ${readiness.floorFailures.join('; ')}`,
      '   Existing answers are too vague — ask for specifics (files, commands, metrics, concrete deliverables).',
    );
  }

  if (readiness.ambiguityScore.overallScore > AMBIGUITY_THRESHOLD) {
    lines.push(
      `${blockerNum++}. ambiguity=${readiness.ambiguityScore.overallScore.toFixed(3)} (must be <= ${AMBIGUITY_THRESHOLD.toFixed(1)})`,
    );
  }

  lines.push(
    '',
    `Status: ambiguity=${readiness.ambiguityScore.overallScore.toFixed(3)} | verifiable_goal=${readiness.verifiableGoal ? 'true' : 'false'} | open_gaps=${readiness.openGaps.length === 0 ? 'none' : readiness.openGaps.join(', ')}`,
    '',
    'DO NOT (these will not unblock the gate):',
    '- Write or Edit the plan file. Seed Spec is auto-generated on Design transition; the plan file is written in Write phase.',
    '- Call NextPhase again until the blockers above are closed.',
    '- Repeat questions about sections already captured — target only open_gaps listed above.',
    '- Ask vague or duplicate questions — each round must close at least one open gap or add a Completion Criterion.',
    '',
    'NEXT TURN — AskUserQuestion with one focus only:',
    pickNextInterviewFocus(readiness),
  );

  return lines.join('\n');
}
