/**
 * Installer user-facing copy (en / ko). Standalone — no app i18n import.
 */

import { detectInstallLocale } from './locale.mjs';

export const INSTALL_STRINGS_EN = {
  'install.title': 'Installing SuperLiora',
  'install.modeLine': 'Mode: {mode}  ·  {elapsed}s',
  'install.stage.checking': 'Checking',
  'install.stage.bootstrapping': 'Bootstrapping',
  'install.stage.fetching': 'Fetching',
  'install.stage.downloading': 'Downloading',
  'install.stage.building': 'Building',
  'install.stage.installing': 'Installing',
  'install.stage.sidecars': 'Sidecars',
  'install.stage.done': 'Done',
  'install.stage.failed': 'Failed',
  'install.ready': 'Ready',
  'install.failed': 'Failed',
  'install.warning': 'warning: {message}',
  'install.probing': 'Probing environment',
  'install.homePicked':
    'Profile disk is tight. Data home is {path} ({free} free). SuperLiora needs ~100 GB free.',
  'install.homeTight':
    'Data home {path} has {free} free. SuperLiora needs ~100 GB; sessions and worktrees will fill a small disk.',
  'install.summary.home': 'Data:    {dir}',
  'install.ensuringNode': 'Ensuring Node.js runtime',
  'install.nodeInstalled': 'Installed Node {version} → ~/.superliora/runtime/node',
  'install.nodeUsing': 'Using Node {version}',
  'install.ensuringGit': 'Ensuring Git',
  'install.gitInstalled': 'Installed Git -> {root}',
  'install.gitBash': 'Using Git Bash {path}',
  'install.gitPath': 'Using Git on PATH',
  'install.gitFailed':
    'Git bootstrap failed ({message}); continuing. Install Git later if the agent needs a shell.',
  'install.fetchingManifest': 'Fetching release manifest',
  'install.placedSea': 'Placed SEA {version} ({target})',
  'install.installedBinary': 'Installed {command} binary',
  'install.fetchingMain': 'Fetching tip of main',
  'install.fetchingSource': 'Fetching SuperLiora source',
  'install.sourceVia': 'Source via {method} → {dir}',
  'install.ensuringPnpm': 'Ensuring pnpm',
  'install.pnpmInstalled': 'Installed pnpm {version} → ~/.superliora/runtime/pnpm',
  'install.pnpmUsing': 'Using pnpm {version}',
  'install.buildingCli': 'Installing dependencies and building CLI',
  'install.installingWrapper': 'Installing {command} wrapper',
  'install.sidecars': 'Installing browser / computer / retrieval',
  'install.hostSetup': 'Ensuring host setup',
  'install.hostSetupReady': 'Host setup ready',
  'install.wtInstalled': 'Installed Windows Terminal + SuperLiora profile',
  'install.nerdFontInstalled': 'Installed CaskaydiaCove Nerd Font',
  'install.ompInstalled': 'Installed Oh My Posh (Neon Noir prompt)',
  'install.zoxideInstalled': 'Installed zoxide',
  'install.fzfInstalled': 'Installed fzf',
  'install.profilePatched': 'Wrote SuperLiora shell profile',
  'install.wingetBootstrapped': 'Bootstrapped winget',
  'install.desktopShortcut': 'Wrote SuperLiora desktop shortcut',
  'install.hostSetupFailed':
    'Host setup failed ({message}); continuing. Re-run /host-setup or pass --no-host-setup.',
  'install.readyCommand': '{command} is ready',
  'install.summary.command': 'Command: {command}',
  'install.summary.binDir': 'Bin dir: {dir}',
  'install.summary.source': 'Source:  {dir}',
  'install.summary.mode': 'Mode:    {mode}',
  'install.summary.next': 'Next:    {command}   ·  {command} upgrade',
  'install.summary.desktop': 'Desktop: SuperLiora (double-click to start)',
  'install.sidecar.browserUse': 'Installing browser-use runtimes',
  'install.sidecar.cua': 'Installing cua-driver',
  'install.sidecar.retrieval': 'Bootstrapping local retrieval embedder',
  'install.host.heading': 'Host setup ({platform})',
  'install.host.needed': 'Missing pieces will be installed or written.',
  'install.host.refresh': 'Managed files can be refreshed; packages are already present.',
  'install.host.group.install': 'Install',
  'install.host.group.write': 'Write',
  'install.host.group.change': 'Change',
  'install.host.item.desktopShortcut': 'Desktop shortcut',
  'install.host.item.startMenu': 'Start Menu shortcut',
  'install.host.item.wtFragment': 'Windows Terminal SuperLiora fragment',
  'install.host.item.wtSettings': 'Windows Terminal defaults',
  'install.host.item.defaultTerminal': 'Windows default terminal',
  'install.host.item.shellProfileWin': 'PowerShell profile (5.1 + 7) managed block',
  'install.host.item.shellProfileUnix': 'Shell profile managed block (~/.zshrc, ~/.bashrc)',
  'install.host.detail.desktopWt': '{path} (Windows Terminal → liora)',
  'install.host.detail.desktopTerm': '{path} (terminal → liora)',
};

export const INSTALL_STRINGS_KO = {
  'install.title': 'SuperLiora 설치 중',
  'install.modeLine': '모드: {mode}  ·  {elapsed}s',
  'install.stage.checking': '확인',
  'install.stage.bootstrapping': '준비',
  'install.stage.fetching': '가져오는 중',
  'install.stage.downloading': '다운로드',
  'install.stage.building': '빌드',
  'install.stage.installing': '설치',
  'install.stage.sidecars': 'Sidecars',
  'install.stage.done': '완료',
  'install.stage.failed': '실패',
  'install.ready': '준비됨',
  'install.failed': '실패',
  'install.warning': '경고: {message}',
  'install.probing': '환경 확인 중',
  'install.homePicked':
    '프로필 디스크 여유가 부족합니다. 데이터 홈은 {path} ({free} 남음). SuperLiora는 여유 약 100GB가 필요합니다.',
  'install.homeTight':
    '데이터 홈 {path} 여유 {free}. SuperLiora는 약 100GB가 필요하며, 세션·worktree가 작은 디스크를 금방 채웁니다.',
  'install.summary.home': '데이터:  {dir}',
  'install.ensuringNode': 'Node.js 런타임 확인 중',
  'install.nodeInstalled': 'Node {version} 설치됨 → ~/.superliora/runtime/node',
  'install.nodeUsing': 'Node {version} 사용',
  'install.ensuringGit': 'Git 확인 중',
  'install.gitInstalled': 'Git 설치됨 -> {root}',
  'install.gitBash': 'Git Bash 사용 {path}',
  'install.gitPath': 'PATH의 Git 사용',
  'install.gitFailed':
    'Git 준비 실패 ({message}); 계속합니다. 에이전트에 셸이 필요하면 나중에 Git을 설치하세요.',
  'install.fetchingManifest': '릴리스 매니페스트 가져오는 중',
  'install.placedSea': 'SEA {version} 배치됨 ({target})',
  'install.installedBinary': '{command} 바이너리 설치됨',
  'install.fetchingMain': 'origin/main 최신 가져오는 중',
  'install.fetchingSource': 'SuperLiora 소스 가져오는 중',
  'install.sourceVia': '{method}(으)로 소스 → {dir}',
  'install.ensuringPnpm': 'pnpm 확인 중',
  'install.pnpmInstalled': 'pnpm {version} 설치됨 → ~/.superliora/runtime/pnpm',
  'install.pnpmUsing': 'pnpm {version} 사용',
  'install.buildingCli': '의존성 설치 및 CLI 빌드 중',
  'install.installingWrapper': '{command} 래퍼 설치 중',
  'install.sidecars': 'browser / computer / retrieval 설치 중',
  'install.hostSetup': '호스트 설정 적용 중',
  'install.hostSetupReady': '호스트 설정 준비됨',
  'install.wtInstalled': 'Windows Terminal + SuperLiora 프로필 설치됨',
  'install.nerdFontInstalled': 'CaskaydiaCove Nerd Font 설치됨',
  'install.ompInstalled': 'Oh My Posh (Neon Noir 프롬프트) 설치됨',
  'install.zoxideInstalled': 'zoxide 설치됨',
  'install.fzfInstalled': 'fzf 설치됨',
  'install.profilePatched': 'SuperLiora 셸 프로필 작성됨',
  'install.wingetBootstrapped': 'winget 준비됨',
  'install.desktopShortcut': 'SuperLiora 바탕화면 바로가기 작성됨',
  'install.hostSetupFailed':
    '호스트 설정 실패 ({message}); 계속합니다. /host-setup을 다시 실행하거나 --no-host-setup을 쓰세요.',
  'install.readyCommand': '{command} 준비됨',
  'install.summary.command': '명령: {command}',
  'install.summary.binDir': '실행 파일: {dir}',
  'install.summary.source': '소스:    {dir}',
  'install.summary.mode': '모드:    {mode}',
  'install.summary.next': '다음:    {command}   ·  {command} upgrade',
  'install.summary.desktop': '바탕화면: SuperLiora (더블클릭해서 시작)',
  'install.sidecar.browserUse': 'browser-use 런타임 설치 중',
  'install.sidecar.cua': 'cua-driver 설치 중',
  'install.sidecar.retrieval': '로컬 retrieval embedder 준비 중',
  'install.host.heading': '호스트 설정 ({platform})',
  'install.host.needed': '없는 구성 요소를 설치하거나 파일을 작성합니다.',
  'install.host.refresh': '관리 파일은 갱신할 수 있습니다. 패키지는 이미 있습니다.',
  'install.host.group.install': '설치',
  'install.host.group.write': '작성',
  'install.host.group.change': '변경',
  'install.host.item.desktopShortcut': '바탕화면 바로가기',
  'install.host.item.startMenu': '시작 메뉴 바로가기',
  'install.host.item.wtFragment': 'Windows Terminal SuperLiora 프로필',
  'install.host.item.wtSettings': 'Windows Terminal 기본값',
  'install.host.item.defaultTerminal': 'Windows 기본 터미널',
  'install.host.item.shellProfileWin': 'PowerShell 프로필 (5.1 + 7) 관리 블록',
  'install.host.item.shellProfileUnix': '셸 프로필 관리 블록 (~/.zshrc, ~/.bashrc)',
  'install.host.detail.desktopWt': '{path} (Windows Terminal → liora)',
  'install.host.detail.desktopTerm': '{path} (터미널 → liora)',
};

export function t(key, params, locale = detectInstallLocale()) {
  const catalog = locale === 'ko' ? INSTALL_STRINGS_KO : INSTALL_STRINGS_EN;
  const template = catalog[key] ?? INSTALL_STRINGS_EN[key] ?? key;
  if (params === undefined) return template;
  return template.replaceAll(/\{(\w+)\}/g, (_match, name) => {
    const value = params[name];
    return value === undefined ? `{${name}}` : String(value);
  });
}
