// AUTO-GENERATED by scripts/build-skill-catalog.mjs
// Do not edit manually.
export const SKILL_CATALOG_SOURCE_COUNTS = {
  "anthropic": 17,
  "ericgrill": 12,
  "luokai": 9786,
  "agentic": 1943,
  "claudeskills": 770,
  "mindrally": 240,
  "seb1n": 91,
  "deduped": 7956,
  "written": 7956
} as const;
