// AUTO-GENERATED by scripts/build-skill-catalog.mjs
// Do not edit manually.
export const SKILL_CATALOG_SOURCE_COUNTS = {
  "anthropic": 17,
  "ericgrill": 12,
  "luokai": 4146,
  "deduped": 4022,
  "written": 4022
} as const;
