/**
 * Shell completions generated from the live command tree.
 *
 * Written because a hand-maintained completion script drifts: the generator
 * walks the same Commander program the CLI runs, so a new subcommand, flag, or
 * enum choice shows up in bash/zsh/fish without a second edit. Output is static
 * (no runtime call in the shell), so completing never blocks on this binary.
 */
import type { Command, Option } from 'commander';

import { t } from '#/cli/i18n';

export const COMPLETION_SHELLS = ['bash', 'zsh', 'fish'] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

export interface CompletionOption {
  /** Every spelling without the value placeholder, e.g. `-y`, `--yolo`. */
  readonly flags: readonly string[];
  readonly description: string;
  /** Fixed values the option accepts (Commander `.choices`), if any. */
  readonly choices: readonly string[];
  readonly takesValue: boolean;
}

export interface CompletionCommand {
  readonly name: string;
  readonly description: string;
  readonly options: readonly CompletionOption[];
}

function optionFlags(option: Option): readonly string[] {
  const flags: string[] = [];
  if (option.short !== undefined) flags.push(option.short);
  if (option.long !== undefined) flags.push(option.long);
  return flags;
}

function describeOption(option: Option): CompletionOption {
  return {
    flags: optionFlags(option),
    description: option.description ?? '',
    choices: (option.argChoices ?? []).map(String),
    takesValue: option.required || option.optional,
  };
}

/** The command tree as the generators need it: names, options, choices. */
export function describeProgram(program: Command): readonly CompletionCommand[] {
  return program.commands
    .map((command) => ({
      name: command.name(),
      description: command.description(),
      options: command.options.map(describeOption),
    }))
    .toSorted((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

function rootOptions(program: Command): readonly CompletionOption[] {
  return program.options.map(describeOption).filter((option) => option.flags.length > 0);
}

function quoteSingle(value: string): string {
  return value.replaceAll("'", String.raw`'\''`);
}

function bashWords(values: readonly string[]): string {
  return [...new Set(values)].join(' ');
}

/**
 * The bash function; the zsh script reuses it under `bashcompinit` so both
 * shells cannot drift apart either.
 */
function bashFunctionBody(programName: string, program: Command): string {
  const commands = describeProgram(program);
  const root = rootOptions(program);
  const choiceCases = [...root, ...commands.flatMap((command) => command.options)]
    .filter((option) => option.choices.length > 0)
    .map(
      (option) =>
        `    ${bashWords(option.flags)}) COMPREPLY=( $(compgen -W "${bashWords(
          option.choices,
        )}" -- "$cur") ); return ;;`,
    );
  const subcommandCases = commands.map(
    (command) =>
      `    ${command.name}) opts="$opts ${bashWords(
        command.options.flatMap((option) => option.flags),
      )}" ;;`,
  );
  const rootOpts = bashWords([
    ...root.flatMap((option) => option.flags),
    '-h',
    '--help',
    '-V',
    '--version',
  ]);
  const commandWords = bashWords(commands.map((command) => command.name));

  return `_liora_completions() {
  local cur prev cmd i
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  cmd=""
  for ((i = 1; i < COMP_CWORD; i++)); do
    case "\${COMP_WORDS[i]}" in
      -*) ;;
      *) cmd="\${COMP_WORDS[i]}"; break ;;
    esac
  done

  case "$prev" in
${choiceCases.join('\n')}
  esac

  local opts="${rootOpts}"
  case "$cmd" in
${subcommandCases.join('\n')}
  esac

  if [ -z "$cmd" ]; then
    COMPREPLY=( $(compgen -W "${commandWords} $opts" -- "$cur") )
    return
  fi
  COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}
complete -F _liora_completions ${programName}`;
}

export function renderBashCompletions(programName: string, program: Command): string {
  return [
    `# ${programName} bash completions — generated by \`${programName} completions bash\``,
    '# Add to ~/.bashrc:  eval "$(' + programName + ' completions bash)"',
    bashFunctionBody(programName, program),
    '',
  ].join('\n');
}

export function renderZshCompletions(programName: string, program: Command): string {
  const body = bashFunctionBody(programName, program);
  return [
    `#compdef ${programName}`,
    `# ${programName} zsh completions — generated by \`${programName} completions zsh\``,
    '# Add to ~/.zshrc:  eval "$(' + programName + ' completions zsh)"',
    '# The bash function is reused through bashcompinit so both shells complete',
    '# from one generator; without the completion system loaded there is nothing',
    '# to register, so the script stays quiet instead of erroring.',
    'if (( $+functions[compdef] )); then',
    '  autoload -Uz bashcompinit && bashcompinit',
    body
      .split('\n')
      .map((line) => (line.length > 0 ? `  ${line}` : line))
      .join('\n'),
    'else',
    '  : # completion system unavailable (non-interactive shell)',
    'fi',
    '',
  ].join('\n');
}

export function renderFishCompletions(programName: string, program: Command): string {
  const lines = [
    `# ${programName} fish completions — generated by \`${programName} completions fish\``,
    `# Install:  ${programName} completions fish > ~/.config/fish/completions/${programName}.fish`,
  ];
  const emit = (
    option: CompletionOption,
    seenCondition: string,
  ): void => {
    const short = option.flags.find((flag) => flag.startsWith('-') && !flag.startsWith('--'));
    const long = option.flags.find((flag) => flag.startsWith('--'));
    const parts = [`complete -c ${programName}`, seenCondition];
    if (short !== undefined) parts.push(`-s ${short.slice(1)}`);
    if (long !== undefined) parts.push(`-l ${long.slice(2)}`);
    if (option.choices.length > 0) {
      parts.push('-x', `-a '${quoteSingle(option.choices.join(' '))}'`);
    } else if (option.takesValue) {
      parts.push('-r');
    }
    if (option.description.length > 0) parts.push(`-d '${quoteSingle(option.description)}'`);
    lines.push(parts.filter(Boolean).join(' '));
  };

  for (const option of rootOptions(program)) emit(option, '');
  for (const command of describeProgram(program)) {
    const condition = `-n '__fish_use_subcommand'`;
    lines.push(
      `complete -c ${programName} ${condition} -a '${quoteSingle(command.name)}' -d '${quoteSingle(
        command.description,
      )}'`,
    );
    for (const option of command.options) {
      emit(option, `-n '__fish_seen_subcommand_from ${command.name}'`);
    }
  }
  lines.push('');
  return lines.join('\n');
}

export function renderCompletions(
  shell: CompletionShell,
  programName: string,
  program: Command,
): string {
  switch (shell) {
    case 'bash':
      return renderBashCompletions(programName, program);
    case 'zsh':
      return renderZshCompletions(programName, program);
    case 'fish':
      return renderFishCompletions(programName, program);
  }
}

export interface CompletionsCommandDeps {
  readonly stdout: (text: string) => void;
}

export function registerCompletionsCommand(
  parent: Command,
  deps?: Partial<CompletionsCommandDeps>,
): void {
  const stdout = deps?.stdout ?? ((text: string) => process.stdout.write(text));
  parent
    .command('completions')
    .description(t('cli.sub.completions.description'))
    .argument('<shell>', t('cli.sub.completions.arg.shell'))
    .action((shell: string) => {
      if (!COMPLETION_SHELLS.includes(shell as CompletionShell)) {
        stdout(`Unknown shell "${shell}". Supported: ${COMPLETION_SHELLS.join(', ')}\n`);
        process.exitCode = 1;
        return;
      }
      stdout(renderCompletions(shell as CompletionShell, parent.name(), parent));
    });
}