import { describe, expect, it } from 'vitest';
import {
  UltraPlanModeEngine,
  ULTRA_PLAN_REQUIRED_SECTIONS,
  MAX_INTERVIEW_ROUNDS,
  combinedDrift,
  formatInterviewReadinessGuide,
  isDriftAcceptable,
  pickNextInterviewFocus,
  type AmbiguityScoreResult,
  type UltraPlanReadiness,
} from '../../src/agent/plan/ultra-plan-mode';
import { enforceSeedCoverage } from '../../src/tools/builtin/planning/exit-plan-mode';

// Minimal mock agent
const mockAgent = {
  context: {
    history: [],
  },
} as any;

function mockAgentWithUserPrompt(prompt: string, generateResponse?: unknown | ((...args: unknown[]) => unknown)): any {
  return {
    context: {
      history: [
        {
          role: 'user',
          origin: { kind: 'user' },
          content: [{ type: 'text', text: prompt }],
          toolCalls: [],
        },
      ],
    },
    config: { provider: { modelName: 'mock' } },
    generate: async (...args: unknown[]) => {
      if (typeof generateResponse === 'function') return generateResponse(...args);
      return generateResponse;
    },
  };
}

function createMockAgent(generateResponse?: unknown | ((...args: unknown[]) => unknown)): any {
  return {
    context: { history: [] },
    config: { provider: { modelName: 'mock' } },
    generate: async (...args: unknown[]) => {
      if (typeof generateResponse === 'function') return generateResponse(...args);
      return generateResponse;
    },
  };
}

function textResponse(text: string): unknown {
  return {
    message: { content: [{ type: 'text', text }] },
    usage: {},
    finishReason: 'stop',
  };
}

function ambiguityResponse(overrides: Record<string, unknown> = {}): unknown {
  return textResponse(
    JSON.stringify({
      goal_clarity_score: 1.0,
      goal_clarity_justification: 'Goal is clear.',
      constraint_clarity_score: 1.0,
      constraint_clarity_justification: 'Constraints are clear.',
      success_criteria_clarity_score: 1.0,
      success_criteria_clarity_justification: 'Success criteria are clear.',
      present_sections: [...ULTRA_PLAN_REQUIRED_SECTIONS],
      verifiable_goal: true,
      specificity_score: 1.0,
      ...overrides,
    }),
  );
}

describe('UltraPlanModeEngine', () => {
  describe('Seed Spec', () => {
    it('should generate a seed spec from interview data', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const seed = engine.generateSeedSpecFromInterview(
        'Build a CLI tool',
        ['Python 3.12+', 'No external DB'],
        ['Can create tasks', 'Can list tasks'],
        'TaskManager',
        [
          { name: 'tasks', type: 'array', description: 'List of tasks', required: true },
        ],
      );

      expect(seed.goal).toBe('Build a CLI tool');
      expect(seed.taskType).toBe('code');
      expect(seed.constraints).toHaveLength(2);
      expect(seed.acceptanceCriteria).toHaveLength(2);
      expect(seed.ontology.name).toBe('TaskManager');
      expect(seed.ontology.fields).toHaveLength(1);
      expect(seed.evaluationPrinciples).toHaveLength(3);
      expect(seed.exitConditions).toHaveLength(1);
      expect(seed.ambiguityScore).toBe(0.15);
      expect(seed.autoGenerated).toBe(false);
    });

    it('should set and get seed spec', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const seed = engine.generateSeedSpecFromInterview('Test', [], [], 'TestOnto', []);
      engine.setSeedSpec(seed);
      expect(engine.seedSpec).toBe(seed);
    });

    it('reopens interview for seed refinement after drift blocks exit', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      engine.startInterview('Build a verifiable CLI fix');
      const seed = engine.generateSeedSpecFromInterview('Build a verifiable CLI fix', [], [], 'CLI', []);
      engine.setSeedSpec(seed);

      engine.addInterviewRound(
        'Confirm the seed.',
        'Goal: build a verifiable CLI fix. Actors: user and agent. Inputs: repo files. Outputs: source edits. Constraints: no unrelated changes. Non-goals: no broad refactor. Acceptance Criteria: tests pass. Verification Plan: run tests. Failure Modes: regression. Runtime Context: TypeScript repo. Completion Criterion: true when tests pass, false otherwise.',
      );

      engine.reopenInterviewForSeedRefinement({
        goalDrift: 0.9,
        constraintDrift: 0,
        ontologyDrift: 0.6,
      });

      expect(engine.seedSpec).toBeNull();
      expect(engine.interviewState.ambiguityScore).toBeNull();
      expect(engine.interviewState.completionCandidateStreak).toBe(0);
      expect(engine.interviewState.lastReadyEvidenceHash).toBeUndefined();
    });

    it('extracts Seed Spec via LLM', async () => {
      const llmOutput = JSON.stringify({
        goal: 'Build a Korean danmaku game',
        taskType: 'code',
        constraints: ['Phaser 4 CDN', 'no external assets'],
        acceptanceCriteria: ['60fps', '3 spell cards'],
        ontology: {
          name: 'DanmakuEmperor',
          description: 'Game domain',
          fields: [{ name: 'spellCard', type: 'string', description: 'Boss phase', required: true }],
        },
        evaluationPrinciples: [{ name: 'performance', description: '60fps', weight: 1.0 }],
        exitConditions: [{ name: 'tests pass', description: 'All tests pass', criteria: 'CI green' }],
        ambiguityScore: 0.1,
      });
      const engine = new UltraPlanModeEngine(createMockAgent(textResponse(llmOutput)));
      engine.startInterview('Build a danmaku game');
      const seed = await engine.autoGenerateSeedSpecFromInterview('DanmakuEmperor');
      expect(seed.goal).toBe('Build a Korean danmaku game');
      expect(seed.autoGenerated).toBe(true);
      expect(seed.constraints).toContain('Phaser 4 CDN');
      expect(seed.acceptanceCriteria).toHaveLength(2);
      expect(seed.ontology.fields).toHaveLength(1);
    });

    it('throws when LLM-based Seed Spec extraction fails', async () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      engine.startInterview('Build a CLI tool');
      await expect(engine.autoGenerateSeedSpecFromInterview('CLI')).rejects.toThrow(
        'LLM-based Seed Spec extraction failed',
      );
    });
  });

  describe('Interview ambiguity scoring', () => {
    it('accumulates interview Q/A into ambiguity scoring and completion readiness', async () => {
      let callCount = 0;
      const engine = new UltraPlanModeEngine(
        createMockAgent(() => {
          callCount++;
          if (callCount === 1) {
            return ambiguityResponse({
              present_sections: [],
              verifiable_goal: false,
              goal_clarity_score: 0.3,
              constraint_clarity_score: 0.3,
              success_criteria_clarity_score: 0.3,
              specificity_score: 0.3,
            });
          }
          return ambiguityResponse();
        }),
      );
      engine.startInterview('Build SuperLiora premium Ultrawork regression protection');

      const initial = await engine.calculateAmbiguityScore();
      expect(initial.milestone).toBe('initial');
      expect(initial.isReadyForSeed).toBe(false);
      expect(engine.interviewState.ambiguityScore).toEqual(initial);

      engine.addInterviewRound(
        'What is the goal and scope?',
        'Goal: preserve the SuperLiora premium CLI workflow with a verifiable UltraGoal. Actors: CLI user, TUI agent, verification owner. Scope: TUI help, theme, UltraPlan, UltraGoal, Research, Swarm decision, and Verify surfaces.',
      );
      engine.addInterviewRound(
        'What constraints and risks must be protected?',
        'Inputs: current repository files, TUI prompt, tests, and user request. Outputs: patched TUI flow, updated tests, and verification evidence. Constraints: must keep the Ultrawork brand visible, cannot hide advanced commands, and should avoid unrelated refactors. Non-goals: do not redesign unrelated provider setup or rewrite the whole TUI. Failure modes: regression that removes terminal themes, weakens slash command access, or claims Swarm without a decision.',
      );
      engine.addInterviewRound(
        'What acceptance criteria should verify success?',
        'Acceptance Criteria: /help advanced shows Ultra access paths, /theme lists bundled themes, /plan ultra starts UltraPlan, /ultrawork connects the workflow, and tests verify each requirement. Verification Plan: run unit tests and inspect rendered TUI copy. Runtime Context: TypeScript monorepo in a local CLI workspace. Completion Criterion: true when tests pass and the workflow is visibly complete, false otherwise.',
      );

      const scored = await engine.calculateAmbiguityScore();

      expect(engine.interviewState.rounds).toMatchObject([
        { roundNumber: 1, question: 'What is the goal and scope?' },
        { roundNumber: 2, question: 'What constraints and risks must be protected?' },
        { roundNumber: 3, question: 'What acceptance criteria should verify success?' },
      ]);
      expect(scored.overallScore).toBeLessThan(initial.overallScore);
      expect(scored.milestone).toBe('ready');
      expect(scored.isReadyForSeed).toBe(true);
      expect(engine.interviewState.ambiguityScore).toEqual(scored);
      expect(engine.interviewState.completionCandidateStreak).toBe(1);
      expect(await engine.canAutoComplete()).toBe(true);

      engine.addInterviewRound(
        'Confirm the Seed is complete without changing scope.',
        'Confirmed: the Seed is complete. Completion Criterion remains true when tests pass and the workflow is visibly complete, false otherwise. No extra scope is added.',
      );
      await engine.calculateAmbiguityScore();

      expect(engine.interviewState.completionCandidateStreak).toBe(2);
      expect(await engine.canAutoComplete()).toBe(true);
    });

    it('emits progress messages while scoring ambiguity', async () => {
      const engine = new UltraPlanModeEngine(createMockAgent(ambiguityResponse()));
      engine.startInterview('Build a simple CLI tool');
      engine.addInterviewRound('What is the goal?', 'Goal: build a simple CLI tool.');

      const progress: string[] = [];
      const result = await engine.calculateAmbiguityScore(undefined, (text) => progress.push(text));

      expect(progress).toContain('Analyzing your answers...');
      expect(progress).toContain(
        'Scoring ambiguity across goal, constraints, and success criteria...',
      );
      expect(progress.some((text) => text.startsWith('Goal clarity:'))).toBe(true);
      expect(progress.some((text) => text.startsWith('Constraint clarity:'))).toBe(true);
      expect(progress.some((text) => text.startsWith('Success criteria clarity:'))).toBe(true);
      expect(progress.some((text) => text.startsWith('Open Seed gaps:'))).toBe(true);
      expect(progress.some((text) => text.includes('Seed Spec is ready.'))).toBe(true);
      expect(result.isReadyForSeed).toBe(true);
    });

    it('emits progress messages for open gaps while scoring ambiguity', async () => {
      const engine = new UltraPlanModeEngine(
        createMockAgent(
          ambiguityResponse({
            present_sections: ['goal'],
            goal_clarity_score: 0.6,
            constraint_clarity_score: 0.5,
            success_criteria_clarity_score: 0.5,
            specificity_score: 0.5,
          }),
        ),
      );
      engine.startInterview('Implement a guarded Ultrawork mode');
      engine.addInterviewRound(
        'What is the goal?',
        'Goal: implement a verifiable UltraGoal.',
      );

      const progress: string[] = [];
      const result = await engine.calculateAmbiguityScore(undefined, (text) => progress.push(text));

      expect(progress.some((text) => text.startsWith('Open Seed gaps:'))).toBe(true);
      expect(progress.some((text) => text.includes('Preparing next question...'))).toBe(true);
      expect(result.isReadyForSeed).toBe(false);
    });

    it('emits progress messages while extracting Seed Spec', async () => {
      const llmOutput = JSON.stringify({
        goal: 'Build a Korean danmaku game',
        taskType: 'code',
        constraints: ['Phaser 4 CDN', 'no external assets'],
        acceptanceCriteria: ['60fps', '3 spell cards'],
        ontology: {
          name: 'DanmakuEmperor',
          description: 'Game domain',
          fields: [{ name: 'spellCard', type: 'string', description: 'Boss phase', required: true }],
        },
        evaluationPrinciples: [{ name: 'performance', description: '60fps', weight: 1.0 }],
        exitConditions: [{ name: 'tests pass', description: 'All tests pass', criteria: 'CI green' }],
        ambiguityScore: 0.1,
      });
      const engine = new UltraPlanModeEngine(createMockAgent(textResponse(llmOutput)));
      engine.startInterview('Build a danmaku game');

      const progress: string[] = [];
      await engine.autoGenerateSeedSpecFromInterview('DanmakuEmperor', undefined, (text) =>
        progress.push(text),
      );

      expect(progress).toContain('Extracting Seed Spec from interview evidence...');
      expect(progress).toContain('Seed Spec extracted.');
    });

    it('keeps interview blocked until every required seed ledger gap is closed', async () => {
      const engine = new UltraPlanModeEngine(
        createMockAgent(
          ambiguityResponse({
            present_sections: ['goal', 'acceptance_criteria', 'verification_plan'],
            goal_clarity_score: 0.6,
            constraint_clarity_score: 0.5,
            success_criteria_clarity_score: 0.5,
            specificity_score: 0.5,
          }),
        ),
      );
      engine.startInterview('Implement a guarded Ultrawork mode');

      engine.addInterviewRound(
        'What is the goal?',
        'Goal: implement a verifiable UltraGoal that is true when Shift-Tab starts Ultrawork and false otherwise. Acceptance Criteria: status and footer tests pass. Verification Plan: run the focused TUI tests.',
      );

      const readiness = await engine.interviewReadiness();

      expect(readiness.ready).toBe(false);
      expect(readiness.verifiableGoal).toBe(true);
      expect(readiness.openGaps).toContain('actors');
      expect(readiness.openGaps).toContain('inputs');
      expect(readiness.openGaps).toContain('runtime_context');
      expect(readiness.ambiguityScore.overallScore).toBeGreaterThan(0.2);
      const blocker = await engine.readinessBlockerMessage();
      expect(blocker).toContain('NOT READY for Design');
      expect(blocker).toContain('open_gaps');
      expect(blocker).toContain('NEXT TURN');
      expect(blocker).toContain('Write or Edit the plan file');
    });

    it('does not close seed gaps from section labels in the question text alone', async () => {
      const engine = new UltraPlanModeEngine(
        createMockAgent(ambiguityResponse({ present_sections: [], verifiable_goal: false })),
      );
      engine.startInterview('Make a game');

      engine.addInterviewRound(
        'Please answer Goal, Actors, Inputs, Outputs, Constraints, Non-goals, Acceptance Criteria, Verification Plan, Failure Modes, and Runtime Context.',
        'yes',
      );

      const readiness = await engine.interviewReadiness();

      expect(readiness.ready).toBe(false);
      expect(readiness.openGaps).toContain('actors');
      expect(readiness.openGaps).toContain('acceptance_criteria');
      expect(readiness.ambiguityScore.overallScore).toBeGreaterThan(0.2);
    });

    it('increments completion streak on a new ready round even when evidence hash collides', async () => {
      const engine = new UltraPlanModeEngine(createMockAgent(ambiguityResponse()));
      engine.startInterview('Build SuperLiora premium Ultrawork regression protection');

      engine.addInterviewRound(
        'What is the goal and scope?',
        'Goal: preserve the SuperLiora premium CLI workflow with a verifiable UltraGoal. Actors: CLI user, TUI agent, verification owner. Scope: TUI help, theme, UltraPlan, UltraGoal, Research, Swarm decision, and Verify surfaces.',
      );
      engine.addInterviewRound(
        'What constraints and risks must be protected?',
        'Inputs: current repository files, TUI prompt, tests, and user request. Outputs: patched TUI flow, updated tests, and verification evidence. Constraints: must keep the Ultrawork brand visible, cannot hide advanced commands, and should avoid unrelated refactors. Non-goals: do not redesign unrelated provider setup or rewrite the whole TUI. Failure modes: regression that removes terminal themes, weakens slash command access, or claims Swarm without a decision.',
      );
      engine.addInterviewRound(
        'What acceptance criteria should verify success?',
        'Acceptance Criteria: /help advanced shows Ultra access paths, /theme lists bundled themes, /plan ultra starts UltraPlan, /ultrawork connects the workflow, and tests verify each requirement. Verification Plan: run unit tests and inspect rendered TUI copy. Runtime Context: TypeScript monorepo in a local CLI workspace. Completion Criterion: true when tests pass and the workflow is visibly complete, false otherwise.',
      );
      await engine.calculateAmbiguityScore();
      expect(engine.interviewState.completionCandidateStreak).toBe(1);
      expect(await engine.canAutoComplete()).toBe(true);

      // Simulate a hash collision: all evidence hashes look identical, so the old
      // evidence-hash-only check would never count the second ready round.
      (engine as any)._hash = () => 'collision';

      engine.addInterviewRound(
        'Confirm the Seed is complete without changing scope.',
        'Confirmed: the Seed is complete. Completion Criterion remains true when tests pass and the workflow is visibly complete, false otherwise. No extra scope is added.',
      );
      await engine.calculateAmbiguityScore();

      expect(engine.interviewState.completionCandidateStreak).toBe(2);
      expect(await engine.canAutoComplete()).toBe(true);
    });

    it('uses the current user prompt as interview context for already-bounded tasks', async () => {
      const engine = new UltraPlanModeEngine(
        mockAgentWithUserPrompt(
          [
            'Use Ultrawork for this bounded source/test verification task.',
            'You are the implementation agent and verification owner.',
            'Task: edit apps/liora/src/tui/commands/ultrawork-contract.ts and apps/liora/test/tui/commands/ultrawork.test.ts.',
            'Inputs: the named source file, test file, and prompt.',
            'Outputs: add SUPER_KIMI_REAL_WORKFLOW_EVIDENCE and report concise evidence.',
            'Constraints: do not edit the harness verifier and make no other changes.',
            'Non-goals: no broad refactor and no unrelated provider changes.',
            'Acceptance Criteria: the check script and targeted test pass.',
            'Verification Plan: run node .super-kimi-real-workflow/check.mjs and the targeted vitest command.',
            'Failure Modes: wrong file edited, verifier edited, or tests fail.',
            'Runtime Context: disposable repository worktree.',
            'Completion Criterion: true when both verification commands pass, false otherwise.',
          ].join('\n'),
          ambiguityResponse(),
        ),
      );
      engine.startInterview('');

      const readiness = await engine.interviewReadiness();

      expect(readiness.ready).toBe(true);
      expect(readiness.openGaps).toEqual([]);
      expect(readiness.verifiableGoal).toBe(true);
      expect(readiness.ambiguityScore.overallScore).toBeLessThanOrEqual(0.2);
      expect(readiness.stableReady).toBe(true);
      expect(readiness.completionCandidateStreak).toBe(1);
    });

    it('explains blockers and the next interview focus in readinessBlockerMessage', async () => {
      const engine = new UltraPlanModeEngine(
        createMockAgent(
          ambiguityResponse({
            present_sections: ['goal'],
            verifiable_goal: false,
            goal_clarity_score: 0.5,
            constraint_clarity_score: 0.5,
            success_criteria_clarity_score: 0.5,
            specificity_score: 0.4,
          }),
        ),
      );
      engine.startInterview('Design a premium landing page art direction');

      const readiness = await engine.interviewReadiness();
      const guide = formatInterviewReadinessGuide(readiness, {
        perspective: engine.currentPerspective,
        interviewRoundCount: engine.interviewState.rounds.length,
      });

      expect(readiness.ready).toBe(false);
      expect(guide).toContain('verifiable_goal=false');
      expect(guide).toContain('Completion Criterion');
      expect(guide).toContain('Write or Edit the plan file');
      expect(guide).toContain('perspective=researcher');
      expect(guide).toContain('through the researcher perspective');
      expect(pickNextInterviewFocus(readiness, 'researcher')).toContain('Researcher lens');
      expect(pickNextInterviewFocus(readiness, 'architect')).toContain('Architect lens');
    });

    it('resets interview perspective when a new interview starts', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      engine.advancePerspective();
      engine.advancePerspective();
      expect(engine.currentPerspective).toBe('architect');

      engine.startInterview('Fresh task');
      expect(engine.currentPerspective).toBe('researcher');
    });

    it('tracks origin and resets consecutiveNonUserAnswers on user answer', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      engine.startInterview('Ship feature X');

      engine.addInterviewRound('What framework?', 'Next.js 14', 'code');
      expect(engine.interviewState.consecutiveNonUserAnswers).toBe(1);

      engine.addInterviewRound('What ORM?', 'Prisma', 'code');
      expect(engine.interviewState.consecutiveNonUserAnswers).toBe(2);

      engine.addInterviewRound('What is the goal?', 'Build feature X', 'user');
      expect(engine.interviewState.consecutiveNonUserAnswers).toBe(0);
    });

    it('records origin on interview rounds', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      engine.startInterview('Ship feature X');

      engine.addInterviewRound('Q1', 'code answer', 'code');
      engine.addInterviewRound('Q2', 'user answer', 'user');

      const rounds = engine.interviewState.rounds;
      expect(rounds[0]?.origin).toBe('code');
      expect(rounds[1]?.origin).toBe('user');
    });

    it('initializes startedAtTimestamp when interview starts', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      expect(engine.interviewState.startedAtTimestamp).toBe(0);
      engine.startInterview('Ship feature X');
      expect(engine.interviewState.startedAtTimestamp).toBeGreaterThan(0);
    });

    it('includes Rhythm Guard alert in readiness guide after 3 non-user answers', async () => {
      const engine = new UltraPlanModeEngine(
        createMockAgent(() =>
          ambiguityResponse({
            present_sections: ['goal'],
            verifiable_goal: false,
            goal_clarity_score: 0.4,
            constraint_clarity_score: 0.4,
            success_criteria_clarity_score: 0.4,
            specificity_score: 0.3,
          }),
        ),
      );
      engine.startInterview('Ship feature X');
      engine.addInterviewRound('Q1', 'code 1', 'code');
      engine.addInterviewRound('Q2', 'code 2', 'code');
      engine.addInterviewRound('Q3', 'code 3', 'code');
      await engine.calculateAmbiguityScore();
      const readiness = await engine.interviewReadiness();
      const guide = formatInterviewReadinessGuide(readiness, {
        perspective: engine.currentPerspective,
        interviewRoundCount: engine.interviewState.rounds.length,
        consecutiveNonUserAnswers: engine.interviewState.consecutiveNonUserAnswers,
      });
      expect(guide).toContain('RHYTHM GUARD');
      expect(guide).toContain('AskUserQuestion');
    });

    it('does not force-ready after the interview round cap when blockers remain', async () => {
      let callCount = 0;
      const engine = new UltraPlanModeEngine(
        createMockAgent(() => {
          callCount++;
          return ambiguityResponse({
            present_sections: ['goal'],
            verifiable_goal: false,
            goal_clarity_score: 0.4,
            constraint_clarity_score: 0.4,
            success_criteria_clarity_score: 0.4,
            specificity_score: 0.3,
          });
        }),
      );
      engine.startInterview('Ship a guarded feature');

      for (let round = 1; round <= MAX_INTERVIEW_ROUNDS; round++) {
        engine.addInterviewRound(`Round ${round}`, `Partial answer ${round}`);
      }

      const scored = await engine.calculateAmbiguityScore();
      const readiness = await engine.interviewReadiness();

      expect(engine.interviewState.rounds).toHaveLength(MAX_INTERVIEW_ROUNDS);
      expect(scored.isReadyForSeed).toBe(false);
      expect(readiness.ready).toBe(false);
      expect(
        formatInterviewReadinessGuide(readiness, {
          perspective: engine.currentPerspective,
          interviewRoundCount: engine.interviewState.rounds.length,
        }),
      ).toContain(`Round cap: ${MAX_INTERVIEW_ROUNDS}`);
    });

    it('reuses cached ambiguity scoring for injection-style readiness checks', async () => {
      let generateCalls = 0;
      const engine = new UltraPlanModeEngine(
        createMockAgent(() => {
          generateCalls++;
          return ambiguityResponse({
            present_sections: ['goal'],
            verifiable_goal: false,
            goal_clarity_score: 0.5,
            constraint_clarity_score: 0.5,
            success_criteria_clarity_score: 0.5,
            specificity_score: 0.4,
          });
        }),
      );
      engine.startInterview('Implement a guarded Ultrawork mode');
      engine.addInterviewRound('What is the goal?', 'Goal: implement a verifiable UltraGoal.');

      await engine.interviewReadiness({ rescore: true });
      const callsAfterScore = generateCalls;

      await engine.interviewReadiness({ rescore: false });
      expect(generateCalls).toBe(callsAfterScore);
    });
  });

  describe('Drift Detection', () => {
    it('should calculate drift when no seed spec exists', async () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const drift = await engine.calculateDrift('some output', []);
      expect(drift.goalDrift).toBe(0);
      expect(drift.constraintDrift).toBe(0);
      expect(drift.ontologyDrift).toBe(0);
    });

    it('should detect goal drift', async () => {
      const engine = new UltraPlanModeEngine(
        createMockAgent(textResponse(JSON.stringify({ goalDrift: 0.8, constraintDrift: 0, ontologyDrift: 0 }))),
      );
      engine.setSeedSpec(
        engine.generateSeedSpecFromInterview(
          'build a fast api',
          [],
          [],
          'API',
          [{ name: 'endpoints', type: 'array', description: 'API endpoints', required: true }],
        ),
      );
      const drift = await engine.calculateDrift('build a slow database', []);
      expect(drift.goalDrift).toBe(0.8);
    });

    it('should keep goal drift low when a detailed plan reflects the seed terms', async () => {
      const engine = new UltraPlanModeEngine(
        createMockAgent(textResponse(JSON.stringify({ goalDrift: 0.1, constraintDrift: 0, ontologyDrift: 0 }))),
      );
      engine.setSeedSpec(
        engine.generateSeedSpecFromInterview(
          'build a fast api',
          ['use TypeScript', 'add unit tests'],
          ['endpoint latency under 100ms', 'passing test suite'],
          'API',
          [{ name: 'endpoints', type: 'array', description: 'API endpoints', required: true }],
        ),
      );
      const drift = await engine.calculateDrift('any plan text', []);
      expect(drift.goalDrift).toBeLessThanOrEqual(0.3);
    });

    it('should calculate constraint drift', async () => {
      const engine = new UltraPlanModeEngine(
        createMockAgent(textResponse(JSON.stringify({ goalDrift: 0, constraintDrift: 0.2, ontologyDrift: 0 }))),
      );
      engine.setSeedSpec(engine.generateSeedSpecFromInterview('test', [], [], 'Test', []));
      const drift = await engine.calculateDrift('output', ['violation1', 'violation2']);
      expect(drift.constraintDrift).toBe(0.2);
    });

    it('should cap constraint drift at 1.0', async () => {
      const engine = new UltraPlanModeEngine(
        createMockAgent(textResponse(JSON.stringify({ goalDrift: 0, constraintDrift: 1.0, ontologyDrift: 0 }))),
      );
      engine.setSeedSpec(engine.generateSeedSpecFromInterview('test', [], [], 'Test', []));
      const drift = await engine.calculateDrift('output', Array.from({ length: 20 }, () => 'v'));
      expect(drift.constraintDrift).toBe(1.0);
    });

    it('calculates drift via LLM', async () => {
      const llmOutput = JSON.stringify({ goalDrift: 0.1, constraintDrift: 0.2, ontologyDrift: 0.0 });
      const engine = new UltraPlanModeEngine(createMockAgent(textResponse(llmOutput)));
      engine.setSeedSpec(
        engine.generateSeedSpecFromInterview('build a fast api', [], [], 'API', []),
      );
      const drift = await engine.calculateDrift('build a fast api', []);
      expect(drift.goalDrift).toBe(0.1);
      expect(drift.constraintDrift).toBe(0.2);
    });

    it('throws when LLM-based drift evaluation fails', async () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      engine.setSeedSpec(engine.generateSeedSpecFromInterview('test', [], [], 'Test', []));
      await expect(engine.calculateDrift('output', [])).rejects.toThrow('LLM-based drift evaluation failed');
    });
  });

  describe('Drift Utilities', () => {
    it('should calculate combined drift', () => {
      const metrics = { goalDrift: 0.2, constraintDrift: 0.1, ontologyDrift: 0.5 };
      expect(combinedDrift(metrics)).toBe(0.2 * 0.5 + 0.1 * 0.3 + 0.5 * 0.2);
    });

    it('should determine acceptable drift', () => {
      expect(isDriftAcceptable({ goalDrift: 0, constraintDrift: 0, ontologyDrift: 0 })).toBe(true);
      expect(isDriftAcceptable({ goalDrift: 1, constraintDrift: 0, ontologyDrift: 0 })).toBe(false);
    });
  });

  describe('Stagnation Detection', () => {
    it('should detect spinning', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const results = engine.detectStagnation(
        ['a', 'b', 'c'],
        ['error1', 'error1', 'error1'],
        [0.1, 0.1, 0.1],
      );
      const spinning = results.find((r) => r.pattern === 'spinning');
      expect(spinning).toBeDefined();
      expect(spinning!.detected).toBe(true);
      expect(spinning!.confidence).toBe(0.9);
    });

    it('should detect oscillation', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const results = engine.detectStagnation(
        ['a', 'b', 'a', 'b'],
        [],
        [0.1, 0.1, 0.1, 0.1],
      );
      const oscillation = results.find((r) => r.pattern === 'oscillation');
      expect(oscillation).toBeDefined();
      expect(oscillation!.detected).toBe(true);
      expect(oscillation!.confidence).toBe(0.85);
    });

    it('should detect no drift', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const results = engine.detectStagnation(
        ['a', 'b', 'c'],
        [],
        [0.1, 0.1, 0.1],
      );
      const noDrift = results.find((r) => r.pattern === 'no_drift');
      expect(noDrift).toBeDefined();
      expect(noDrift!.detected).toBe(true);
      expect(noDrift!.confidence).toBe(0.8);
    });

    it('should detect diminishing returns', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const results = engine.detectStagnation(
        ['a', 'b', 'c', 'd'],
        [],
        [0.1, 0.1001, 0.1002, 0.1003],
      );
      const diminishing = results.find((r) => r.pattern === 'diminishing_returns');
      expect(diminishing).toBeDefined();
      expect(diminishing!.detected).toBe(true);
      expect(diminishing!.confidence).toBe(0.75);
    });

    it('should not detect patterns with insufficient data', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const results = engine.detectStagnation(['a'], ['e1'], [0.1]);
      expect(results.every((r) => !r.detected)).toBe(true);
    });
  });

  describe('Interview perspectives', () => {
    it('describes each interview lens as an expert-leader improvement angle', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const lenses: Array<{ perspective: string; fragment: string }> = [
        { perspective: 'researcher', fragment: 'benchmarks' },
        { perspective: 'simplifier', fragment: 'MVP vs premium' },
        { perspective: 'architect', fragment: 'maintainability' },
        { perspective: 'breadth-keeper', fragment: 'stretch goals' },
        { perspective: 'seed-closer', fragment: 'measurable acceptance criteria' },
      ];

      for (const { perspective, fragment } of lenses) {
        while (engine.currentPerspective !== perspective) {
          engine.advancePerspective();
        }
        expect(engine.getPerspectiveDescription()).toContain(fragment);
      }
    });
  });

  describe('Lateral Thinking', () => {
    it('should generate lateral thinking for each persona', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const personas = ['hacker', 'researcher', 'simplifier', 'architect', 'contrarian'] as const;

      for (const persona of personas) {
        const result = engine.generateLateralThinking(persona, 'problem', 'current approach');
        expect(result.persona).toBe(persona);
        expect(result.prompt).toContain(persona);
        expect(result.questions.length).toBeGreaterThan(0);
      }
    });
  });

  describe('Evaluation Plan', () => {
    it('should generate default evaluation plan', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const plan = engine.generateDefaultEvaluationPlan();
      expect(plan.stage1Mechanical).toBe(true);
      expect(plan.stage2Semantic).toBe(true);
      expect(plan.stage3Consensus).toBe(false);
      expect(plan.mechanicalChecks).toContain('lint');
      expect(plan.semanticCriteria).toContain('ac_compliance');
    });

    it('should set and get evaluation plan', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const plan = engine.generateDefaultEvaluationPlan();
      engine.setEvaluationPlan(plan);
      expect(engine.evaluationPlan).toBe(plan);
    });
  });

  describe('Serialization', () => {
    it('should serialize and deserialize seed spec and evaluation plan', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      const seed = engine.generateSeedSpecFromInterview('test', [], [], 'Test', []);
      engine.setSeedSpec(seed);
      engine.setEvaluationPlan(engine.generateDefaultEvaluationPlan());

      const serialized = engine.serialize();
      expect(serialized['seedSpec']).toBeDefined();
      expect(serialized['evaluationPlan']).toBeDefined();

      const newEngine = new UltraPlanModeEngine(mockAgent);
      newEngine.deserialize(serialized);
      expect(newEngine.seedSpec).toEqual(seed);
      expect(newEngine.evaluationPlan).toEqual(engine.evaluationPlan);
    });

    it('should serialize and deserialize interview state', () => {
      const engine = new UltraPlanModeEngine(mockAgent);
      engine.startInterview('Ship feature X');
      engine.addInterviewRound('What is the scope?', 'README and landing page only');

      const serialized = engine.serialize();
      expect(serialized['interviewState']).toBeDefined();

      const newEngine = new UltraPlanModeEngine(mockAgent);
      newEngine.deserialize(serialized);
      expect(newEngine.interviewState.rounds).toHaveLength(1);
      expect(newEngine.interviewState.initialContext).toBe('Ship feature X');
    });
  });

  describe('UltraPlan flow improvements (regression)', () => {
    it('AC-1: exposes the auto-answer origin counter in the readiness guide', () => {
      const score: AmbiguityScoreResult = {
        overallScore: 0.5,
        breakdown: [],
        isReadyForSeed: false,
        milestone: 'initial',
        floorFailures: [],
      };
      const readiness: UltraPlanReadiness = {
        ready: false,
        stableReady: false,
        openGaps: ['goal'],
        ambiguityScore: score,
        verifiableGoal: false,
        completionCandidateStreak: 0,
        floorFailures: [],
      };
      const guide = formatInterviewReadinessGuide(readiness, {
        consecutiveNonUserAnswers: 2,
      });
      expect(guide).toContain('Auto-answers: 2/3');
    });

    it('AC-2: falls back to deterministic heuristic when LLM scoring returns null', async () => {
      let generateCalls = 0;
      const engine = new UltraPlanModeEngine(
        createMockAgent(() => {
          generateCalls++;
          return textResponse('not valid json');
        }),
      );
      engine.startInterview('Build a heuristic-tested CLI tool');
      engine.addInterviewRound('What is the goal?', 'Goal: build a CLI tool.');

      const result = await engine.calculateAmbiguityScore();

      expect(generateCalls).toBe(2);
      expect(result.usedHeuristicFallback).toBe(true);
      expect(result.isReadyForSeed).toBe(false);
    });

    it('AC-3: enforceSeedCoverage flags a plan missing a Seed section', () => {
      const plan = [
        '## Seed Spec',
        'Verifiable UltraGoal: build a thing',
        'Constraints: none',
        'Acceptance Criteria: tests pass',
        'Ontology: Thing',
        // Evaluation Plan is intentionally missing.
        '## WorkGraph',
        '## Execution Plan',
      ].join('\n');
      const missing = enforceSeedCoverage(plan);
      expect(missing).toContain('Missing section: Evaluation');
    });
  });
});
