/* Generated by scripts/sync-provider-catalog.mjs — do not edit by hand. */
/* Facts come from https://models.dev/api.json — the catalog /login reads. */
/* Refresh with `pnpm -C apps/site run catalog:sync`; the Pages workflow runs it per deploy. */

export interface CatalogProviderChip {
  readonly name: string;
  readonly models: number;
}

export interface ProviderCatalogSnapshot {
  /** Where the numbers come from, shown next to the strip so the claim is checkable. */
  readonly source: string;
  /** UTC date of the snapshot the counts below were taken from. */
  readonly snapshotDate: string;
  readonly providerCount: number;
  readonly modelCount: number;
  /** Largest / most-used catalogs first; the marquee renders these, then "+N more". */
  readonly providers: readonly CatalogProviderChip[];
}

export const PROVIDER_CATALOG: ProviderCatalogSnapshot = {
  source: "models.dev",
  snapshotDate: "2026-10-04",
  providerCount: 226,
  modelCount: 8393,
  providers: [
    { name: "Anthropic", models: 16 },
    { name: "OpenAI", models: 53 },
    { name: "Google", models: 39 },
    { name: "xAI", models: 13 },
    { name: "OpenRouter", models: 390 },
    { name: "DeepSeek", models: 4 },
    { name: "Groq", models: 16 },
    { name: "Mistral", models: 34 },
    { name: "Together AI", models: 29 },
    { name: "Cerebras", models: 2 },
    { name: "Perplexity", models: 4 },
    { name: "Azure", models: 94 },
    { name: "Amazon Bedrock", models: 191 },
    { name: "Alibaba", models: 59 },
    { name: "NanoGPT", models: 600 },
    { name: "LLM Gateway", models: 438 },
    { name: "Vercel AI Gateway", models: 403 },
    { name: "Kilo Gateway", models: 397 },
    { name: "Eden AI", models: 291 },
    { name: "DevPass (LLM Gateway)", models: 214 },
    { name: "Merge Gateway", models: 195 },
    { name: "Requesty", models: 166 },
    { name: "Ofox", models: 151 },
    { name: "AIHubMix", models: 137 },
    { name: "Poe", models: 137 },
    { name: "ZenMux", models: 129 },
    { name: "302.AI", models: 122 },
    { name: "OrcaRouter", models: 117 },
  ],
};
