/* Generated by scripts/sync-provider-catalog.mjs — do not edit by hand. */
/* Facts come from https://models.dev/api.json — the catalog /login reads. */
/* Refresh with `pnpm -C apps/site run catalog:sync`; the Pages workflow runs it per deploy. */

export interface CatalogProviderChip {
  readonly name: string;
  readonly models: number;
}

export interface ProviderCatalogSnapshot {
  /** Where the numbers come from, shown next to the strip so the claim is checkable. */
  readonly source: string;
  /** UTC date of the snapshot the counts below were taken from. */
  readonly snapshotDate: string;
  readonly providerCount: number;
  readonly modelCount: number;
  /** Largest / most-used catalogs first; the marquee renders these, then "+N more". */
  readonly providers: readonly CatalogProviderChip[];
}

export const PROVIDER_CATALOG: ProviderCatalogSnapshot = {
  source: "models.dev",
  snapshotDate: "2026-09-09",
  providerCount: 213,
  modelCount: 7617,
  providers: [
    { name: "Anthropic", models: 14 },
    { name: "OpenAI", models: 48 },
    { name: "Google", models: 39 },
    { name: "xAI", models: 12 },
    { name: "OpenRouter", models: 358 },
    { name: "DeepSeek", models: 3 },
    { name: "Groq", models: 16 },
    { name: "Mistral", models: 34 },
    { name: "Together AI", models: 38 },
    { name: "Cerebras", models: 2 },
    { name: "Perplexity", models: 4 },
    { name: "Azure", models: 87 },
    { name: "Amazon Bedrock", models: 153 },
    { name: "Alibaba", models: 55 },
    { name: "NanoGPT", models: 589 },
    { name: "Vercel AI Gateway", models: 373 },
    { name: "LLM Gateway", models: 372 },
    { name: "Kilo Gateway", models: 367 },
    { name: "Eden AI", models: 258 },
    { name: "DevPass (LLM Gateway)", models: 186 },
    { name: "Merge Gateway", models: 181 },
    { name: "Requesty", models: 153 },
    { name: "Poe", models: 137 },
    { name: "ZenMux", models: 120 },
    { name: "OrcaRouter", models: 117 },
    { name: "302.AI", models: 116 },
    { name: "Ofox", models: 115 },
    { name: "Abacus", models: 108 },
  ],
};
