import { describe, expect, it } from 'vitest';

import { buildSeedSpec } from '#/agent/plan/ultra-plan-seed-build';
import type { OntologyField } from '#/agent/plan/ultra-plan-mode';

const FIELDS: readonly OntologyField[] = [
  { name: 'kind', type: 'string', required: true, description: 'kind' },
  { name: 'count', type: 'number', required: false, description: 'count' },
];

describe('agent/plan/ultra-plan-seed-build — buildSeedSpec', () => {
  it('produces a fully populated SeedSpec with default evaluation principles', () => {
    const spec = buildSeedSpec(
      'ship the harness',
      ['no external network', 'single command'],
      ['runs unit tests', 'produces artifact'],
      'code-ontology',
      FIELDS,
    );
    expect(spec.goal).toBe('ship the harness');
    expect(spec.taskType).toBe('code');
    expect(spec.constraints).toEqual(['no external network', 'single command']);
    expect(spec.acceptanceCriteria).toEqual([
      { id: 'ac_1', description: 'runs unit tests', status: 'pending' },
      { id: 'ac_2', description: 'produces artifact', status: 'pending' },
    ]);
    expect(spec.ontology.name).toBe('code-ontology');
    expect(spec.ontology.description).toMatch(/code-ontology/);
    expect(spec.ontology.fields).toEqual(FIELDS);
    expect(spec.evaluationPrinciples.map((p) => p.name)).toEqual([
      'completeness',
      'correctness',
      'clarity',
    ]);
    expect(spec.exitConditions).toHaveLength(1);
    expect(spec.exitConditions[0].name).toBe('all_criteria_met');
    expect(spec.ambiguityScore).toBeCloseTo(0.15);
    expect(spec.autoGenerated).toBe(false);
    expect(typeof spec.createdAt).toBe('string');
    expect(Number.isNaN(Date.parse(spec.createdAt))).toBe(false);
  });

  it('copies the constraints list so external mutations do not leak in', () => {
    const constraints = ['a', 'b'];
    const spec = buildSeedSpec('g', constraints, ['ac'], 'onto', FIELDS);
    constraints.push('mutated');
    expect(spec.constraints).toEqual(['a', 'b']);
  });

  it('copies the ontology fields so external mutations do not leak in', () => {
    const fields: OntologyField[] = [
      { name: 'kind', type: 'string', required: true, description: 'kind' },
    ];
    const spec = buildSeedSpec('g', [], ['ac'], 'onto', fields);
    fields.pop();
    expect(spec.ontology.fields).toHaveLength(1);
  });

  it('flags autoGenerated=true when explicitly requested', () => {
    const spec = buildSeedSpec('g', [], ['ac'], 'onto', [], true);
    expect(spec.autoGenerated).toBe(true);
  });

  it('uses the supplied timestamp for createdAt', () => {
    const fixed = new Date('2026-01-02T03:04:05.000Z');
    const spec = buildSeedSpec('g', [], ['ac'], 'onto', [], false, fixed);
    expect(spec.createdAt).toBe('2026-01-02T03:04:05.000Z');
  });

  it('numbers acceptance criteria deterministically as ac_1, ac_2, …', () => {
    const spec = buildSeedSpec('g', [], ['one', 'two', 'three'], 'onto', []);
    expect(spec.acceptanceCriteria.map((ac) => ac.id)).toEqual(['ac_1', 'ac_2', 'ac_3']);
    expect(spec.acceptanceCriteria.every((ac) => ac.status === 'pending')).toBe(true);
  });
});
