import { describe, expect, it } from 'vitest';

import {
  normalizeOntology,
  normalizeSeedSpec,
  type BuildSeedSpecFn,
} from '#/agent/plan/ultra-plan-seed-normalize';

const makeBuildSeedSpec = (): BuildSeedSpecFn =>
  (goal, constraints, acceptanceCriteria, ontologyName, ontologyFields, autoGenerated) => ({
    goal,
    taskType: 'code',
    constraints: [...constraints],
    acceptanceCriteria: acceptanceCriteria.map((desc, i) => ({
      id: `ac_${i + 1}`,
      description: desc,
      status: 'pending' as const,
    })),
    ontology: {
      name: ontologyName,
      description: `Ontology for ${ontologyName}`,
      fields: [...ontologyFields],
    },
    evaluationPrinciples: [],
    exitConditions: [],
    ambiguityScore: 0.15,
    autoGenerated: autoGenerated ?? false,
    createdAt: '2026-01-01T00:00:00.000Z',
  });

describe('ultra-plan-seed-normalize — normalizeOntology', () => {
  it('returns defaults for null / non-object', () => {
    expect(normalizeOntology(null, 'fallback')).toEqual({
      name: 'fallback',
      description: 'Ontology for fallback',
      fields: [],
    });
    expect(normalizeOntology(undefined, 'fallback').name).toBe('fallback');
  });

  it('trims name/description and falls back when blank', () => {
    expect(normalizeOntology({ name: '  spec  ', description: '  raw  ' }, 'x')).toEqual({
      name: 'spec',
      description: 'raw',
      fields: [],
    });
    expect(normalizeOntology({ name: '   ', description: '' }, 'def').name).toBe('def');
    expect(normalizeOntology({ name: 'spec' }, 'def').description).toBe('Ontology for spec');
  });

  it('keeps only fully-typed fields and copies them', () => {
    const out = normalizeOntology(
      {
        name: 'spec',
        fields: [
          { name: 'a', type: 'string', description: 'd', required: true },
          { name: 'b', type: 'number', description: 'd' }, // missing required
          { name: 'c', type: 'boolean', description: 'd', required: false },
        ],
      },
      'x',
    );
    expect(out.fields).toHaveLength(2);
    expect(out.fields[0]).toEqual({ name: 'a', type: 'string', description: 'd', required: true });
    expect(out.fields[1]).toEqual({ name: 'c', type: 'boolean', description: 'd', required: false });
  });

  it('returns empty fields array when raw.fields is not an array', () => {
    expect(normalizeOntology({ name: 's', fields: 'oops' }, 'd').fields).toEqual([]);
  });
});

describe('ultra-plan-seed-normalize — normalizeSeedSpec', () => {
  const build = makeBuildSeedSpec();

  it('returns a complete SeedSpec for a fully-shaped raw input', () => {
    const out = normalizeSeedSpec(
      {
        goal: '  ship plan  ',
        taskType: 'research',
        constraints: ['fast', 1, 'safe'],
        acceptanceCriteria: ['works', null, 'tests'],
        ontology: {
          name: 's',
          fields: [{ name: 'k', type: 'string', description: 'd', required: true }],
        },
        evaluationPrinciples: [
          { name: 'p1', description: 'd', weight: 0.7 },
          { name: 1, description: 'd', weight: 0.2 },
        ],
        exitConditions: [
          { name: 'done', description: 'd', criteria: 'c' },
          { name: 'done2', description: 'd' },
        ],
        ambiguityScore: 0.42,
      },
      'default-name',
      true,
      'fallback',
      build,
    );
    expect(out.goal).toBe('ship plan');
    expect(out.taskType).toBe('research');
    expect(out.constraints).toEqual(['fast', 'safe']);
    expect(out.acceptanceCriteria).toEqual([
      { id: 'ac_1', description: 'works', status: 'pending' },
      { id: 'ac_2', description: 'tests', status: 'pending' },
    ]);
    expect(out.ontology.fields).toEqual([
      { name: 'k', type: 'string', description: 'd', required: true },
    ]);
    expect(out.evaluationPrinciples).toEqual([
      { name: 'p1', description: 'd', weight: 0.7 },
    ]);
    expect(out.exitConditions).toEqual([{ name: 'done', description: 'd', criteria: 'c' }]);
    expect(out.ambiguityScore).toBe(0.42);
    expect(out.autoGenerated).toBe(true);
    expect(out.createdAt).toBe('2026-01-01T00:00:00.000Z');
  });

  it('falls back to default taskType / goal / principle / exit defaults', () => {
    const out = normalizeSeedSpec(
      {
        goal: '',
        taskType: 'bogus',
        constraints: 'not-array',
        acceptanceCriteria: undefined,
        evaluationPrinciples: 'not-array',
        exitConditions: undefined,
      },
      'def',
      false,
      'fallback-goal',
      build,
    );
    expect(out.goal).toBe('fallback-goal');
    expect(out.taskType).toBe('code');
    expect(out.constraints).toEqual([]);
    expect(out.acceptanceCriteria).toEqual([]);
    expect(out.evaluationPrinciples).toEqual([
      { name: 'completeness', description: 'All requirements are met', weight: 1.0 },
      { name: 'correctness', description: 'Implementation is correct', weight: 1.0 },
      { name: 'clarity', description: 'Code is clear and maintainable', weight: 0.8 },
    ]);
    expect(out.exitConditions).toEqual([
      { name: 'all_criteria_met', description: 'All acceptance criteria satisfied', criteria: '100% criteria pass' },
    ]);
    expect(out.ambiguityScore).toBe(0.15);
    expect(out.autoGenerated).toBe(false);
  });

  it('overrides buildSeedSpec ambiguityScore back to raw value when present', () => {
    const out = normalizeSeedSpec(
      { goal: 'g', ambiguityScore: 0.7 },
      'd',
      false,
      'fallback',
      build,
    );
    expect(out.ambiguityScore).toBe(0.7);
  });
});
