/**
 * Fleet facade aliases — mirrors agent-core `#/fleet` soft path (W5).
 * Canonical wire types remain `ultrawork.collaboration.*` / `ultrawork.swarm.*` until hard rename.
 */
export {
  FLEET_DUAL_EMIT_ENV,
  FLEET_EVENT_PREFIX,
  FLEET_ULTRAWORK_EVENT_SUFFIXES,
  FLEET_WORKTREE_ENV,
  FLEET_WORKTREE_FALLBACK_TIP,
  applyFleetWorktreeToSpawnTasks,
  dualEmitFleetUltraworkAlias,
  fleetDualEmitStatusLine,
  fleetUltraworkEventAlias,
  isFleetDualEmitEnabled,
  isFleetUltraworkEventType,
  isFleetWorktreeEnvEnabled,
  isUltraworkOrFleetEventType,
  maybeEmitFleetUltraworkAliasLive,
  normalizeFleetUltraworkEventAlias,
  normalizeMissionOrFleetUltraworkEventAlias,
  resolveFleetWorkerWorktreeDir,
  ultraworkFleetEventAlias,
  SWARM_MAKER_CHECKER_AGENT_SWARM_TIP,
  SWARM_MAKER_CHECKER_SOFT_TIP,
  classifyExpertRoleString,
  classifySwarmLaneRole,
  classifySwarmPhaseRole,
  detectAgentSwarmItemRoleCollision,
  detectMakerCheckerCollisions,
  detectMakerCheckerCollisionsFromAssignments,
  detectMakerCheckerCollisionsFromSwarmOutput,
  detectMakerCheckerCollisionsFromUltraSwarmResults,
  formatMakerCheckerSoftWarn,
  makerCheckerSoftWarnFromAgentSwarmItems,
  makerCheckerSoftWarnFromSwarmOutput,
  makerCheckerSoftWarnFromUltraSwarmResults,
  FLEET_BUDGET_USD_ENV,
  SWARM_COST_GUARD_SOFT_TIP,
  evaluateFleetCostGuardSoft,
  estimateSessionCostUsd,
  fleetCostGuardSoftTipFromAgent,
  fleetCostGuardSoftTipFromSwarmOutput,
  fleetCostGuardSoftTipFromUsage,
  formatFleetCostGuardSoftTip,
  loadFleetBudgetGlance,
} from '@superliora/agent-core/fleet';

export type { FleetUltraworkEventSuffix } from '@superliora/agent-core/fleet';
