/**
 * Shared language id normalization for path maps, markdown fences, Shiki,
 * and transcript sniffers. One table so engines never disagree on aliases.
 */

/** Alias / extension → canonical highlight language id. */
export const LANG_ALIASES: Readonly<Record<string, string>> = {
  ts: 'typescript',
  tsx: 'tsx',
  mts: 'typescript',
  cts: 'typescript',
  js: 'javascript',
  jsx: 'jsx',
  mjs: 'javascript',
  cjs: 'javascript',
  py: 'python',
  pyw: 'python',
  pyi: 'python',
  rb: 'ruby',
  rs: 'rust',
  go: 'go',
  java: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'fish',
  shell: 'bash',
  shellscript: 'bash',
  json: 'json',
  jsonc: 'jsonc',
  json5: 'json5',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  md: 'markdown',
  mdx: 'mdx',
  markdown: 'markdown',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  html: 'html',
  htm: 'html',
  xml: 'xml',
  svg: 'xml',
  sql: 'sql',
  c: 'c',
  h: 'c',
  cc: 'cpp',
  cpp: 'cpp',
  cxx: 'cpp',
  hh: 'cpp',
  hpp: 'cpp',
  cs: 'csharp',
  php: 'php',
  swift: 'swift',
  scala: 'scala',
  r: 'r',
  lua: 'lua',
  pl: 'perl',
  pm: 'perl',
  vue: 'vue',
  svelte: 'svelte',
  dockerfile: 'dockerfile',
  docker: 'dockerfile',
  makefile: 'makefile',
  mk: 'makefile',
  make: 'makefile',
  zig: 'zig',
  nim: 'nim',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hs: 'haskell',
  proto: 'protobuf',
  protobuf: 'protobuf',
  graphql: 'graphql',
  gql: 'graphql',
  nix: 'nix',
  vim: 'vim',
  diff: 'diff',
  patch: 'diff',
  ini: 'ini',
  cfg: 'ini',
  conf: 'ini',
  properties: 'properties',
  env: 'dotenv',
  tf: 'terraform',
  hcl: 'hcl',
  tfvars: 'terraform',
  cmake: 'cmake',
  dart: 'dart',
  rsx: 'rust',
  ps1: 'powershell',
  psm1: 'powershell',
  rkt: 'racket',
  clj: 'clojure',
  cljs: 'clojure',
  edn: 'clojure',
  jl: 'julia',
  fs: 'fsharp',
  fsx: 'fsharp',
  ml: 'ocaml',
  mli: 'ocaml',
  groovy: 'groovy',
  gradle: 'groovy',
  prisma: 'prisma',
  proto3: 'protobuf',
  tex: 'latex',
  latex: 'latex',
  bib: 'bibtex',
  rst: 'rst',
  mermaid: 'mermaid',
  csv: 'csv',
  tsv: 'tsv',
  nginx: 'nginx',
  apache: 'apache',
  wasm: 'wasm',
  wat: 'wat',
  asm: 'asm',
  s: 'asm',
};

/**
 * Path extension → language for Read/Write/Edit previews.
 * Prefer precise grammar ids that Shiki understands; cli-highlight may
 * fall back when the id is unknown there.
 */
export const EXT_LANG_MAP: Readonly<Record<string, string>> = {
  ts: 'typescript',
  tsx: 'tsx',
  mts: 'typescript',
  cts: 'typescript',
  js: 'javascript',
  jsx: 'jsx',
  mjs: 'javascript',
  cjs: 'javascript',
  py: 'python',
  pyw: 'python',
  pyi: 'python',
  rb: 'ruby',
  rs: 'rust',
  go: 'go',
  java: 'java',
  kt: 'kotlin',
  kts: 'kotlin',
  sh: 'bash',
  bash: 'bash',
  zsh: 'bash',
  fish: 'fish',
  json: 'json',
  jsonc: 'jsonc',
  yaml: 'yaml',
  yml: 'yaml',
  toml: 'toml',
  md: 'markdown',
  mdx: 'mdx',
  css: 'css',
  scss: 'scss',
  less: 'less',
  html: 'html',
  htm: 'html',
  xml: 'xml',
  svg: 'xml',
  sql: 'sql',
  c: 'c',
  cc: 'cpp',
  cpp: 'cpp',
  cxx: 'cpp',
  h: 'c',
  hh: 'cpp',
  hpp: 'cpp',
  cs: 'csharp',
  php: 'php',
  swift: 'swift',
  scala: 'scala',
  r: 'r',
  lua: 'lua',
  pl: 'perl',
  pm: 'perl',
  vue: 'vue',
  svelte: 'svelte',
  dockerfile: 'dockerfile',
  makefile: 'makefile',
  mk: 'makefile',
  zig: 'zig',
  nim: 'nim',
  ex: 'elixir',
  exs: 'elixir',
  erl: 'erlang',
  hs: 'haskell',
  proto: 'protobuf',
  graphql: 'graphql',
  gql: 'graphql',
  nix: 'nix',
  vim: 'vim',
  diff: 'diff',
  patch: 'diff',
  ini: 'ini',
  cfg: 'ini',
  conf: 'ini',
  properties: 'properties',
  env: 'dotenv',
  tf: 'terraform',
  hcl: 'hcl',
  tfvars: 'terraform',
  cmake: 'cmake',
  dart: 'dart',
  ps1: 'powershell',
  psm1: 'powershell',
  jl: 'julia',
  clj: 'clojure',
  groovy: 'groovy',
  prisma: 'prisma',
  tex: 'latex',
  rst: 'rst',
  csv: 'csv',
  tsv: 'tsv',
  nginx: 'nginx',
};

/** Normalize a language tag from fences, path maps, or sniffers. */
export function normalizeLangId(lang: string | undefined): string | undefined {
  if (lang === undefined) return undefined;
  const normalized = lang.trim().toLowerCase();
  if (normalized.length === 0 || normalized === 'text' || normalized === 'plain' || normalized === 'plaintext') {
    return undefined;
  }
  return LANG_ALIASES[normalized] ?? normalized;
}
