import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

import { PROVIDER_CATALOG } from '../src/data/provider-catalog.generated';
import { en } from '../src/landing/i18n/en';
import { ko } from '../src/landing/i18n/ko';

const siteRoot = resolve(import.meta.dirname, '..');

function read(rel: string): string {
  return readFileSync(resolve(siteRoot, rel), 'utf8');
}

const catalogStat = (dict: typeof en) => dict.hero.stats.find((stat) => stat.v.includes('models.dev'))?.v ?? '';

describe('landing provider catalog snapshot', () => {
  it('describes a real models.dev catalog, not a hand-picked dozen', () => {
    expect(read('src/data/provider-catalog.generated.ts').startsWith('/* Generated by')).toBe(true);
    expect(PROVIDER_CATALOG.source).toBe('models.dev');
    expect(PROVIDER_CATALOG.snapshotDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
    expect(PROVIDER_CATALOG.providerCount).toBeGreaterThanOrEqual(100);
    expect(PROVIDER_CATALOG.modelCount).toBeGreaterThan(PROVIDER_CATALOG.providerCount);
    expect(PROVIDER_CATALOG.providers.length).toBeGreaterThan(12);
    for (const row of PROVIDER_CATALOG.providers) {
      expect(row.name.trim().length, 'provider name').toBeGreaterThan(0);
      expect(row.models).toBeGreaterThan(0);
    }
  });

  it('quotes the snapshot everywhere a count is shown', () => {
    for (const dict of [ko, en]) {
      expect(catalogStat(dict)).toContain(String(PROVIDER_CATALOG.providerCount));
      expect(dict.systems.providersNote).toContain('{providers}');
      expect(dict.systems.providersNote).toContain('{models}');
      expect(dict.systems.providersNote).toContain('{date}');
      expect(dict.systems.providersMore).toContain('{count}');
    }
    const systems = read('src/landing/components/Systems.tsx');
    expect(systems).toContain('PROVIDER_CATALOG.providerCount');
    expect(systems).toContain('PROVIDER_CATALOG.modelCount');
    expect(systems).toContain('PROVIDER_CATALOG.providers');
  });

  it('keeps provider names out of the dictionaries so they cannot go stale', () => {
    for (const dict of [ko, en]) {
      expect('providers' in dict.systems, 'systems.providers').toBe(false);
    }
  });
});
